/* Autogenerated: word_by_word_montgomery fp129 32 0x1b6fd049366426c8ebfffffffffffffff */
/* curve description: fp129 */
/* machine_wordsize = 32 (from "32") */
/* requested operations: (all) */
/* m = 0x1b6fd049366426c8ebfffffffffffffff (from "0x1b6fd049366426c8ebfffffffffffffff") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) + (z[4] << 128) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) + (z[4] << 128) in */
/*                            if x1 & (2^160-1) < 2^159 then x1 & (2^160-1) else (x1 & (2^160-1)) - 2^160 */

#include <stdint.h>
typedef unsigned char fiat_fp129_uint1;
typedef signed char fiat_fp129_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_FP129_FIAT_INLINE __inline__
#else
#  define FIAT_FP129_FIAT_INLINE
#endif

/* The type fiat_fp129_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp129_montgomery_domain_field_element[5];

/* The type fiat_fp129_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp129_non_montgomery_domain_field_element[5];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_fp129_addcarryx_u32 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^32
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp129_addcarryx_u32(uint32_t* out1, fiat_fp129_uint1* out2, fiat_fp129_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  uint64_t x1;
  uint32_t x2;
  fiat_fp129_uint1 x3;
  x1 = ((arg1 + (uint64_t)arg2) + arg3);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (fiat_fp129_uint1)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp129_subborrowx_u32 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^32
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp129_subborrowx_u32(uint32_t* out1, fiat_fp129_uint1* out2, fiat_fp129_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  int64_t x1;
  fiat_fp129_int1 x2;
  uint32_t x3;
  x1 = ((arg2 - (int64_t)arg1) - arg3);
  x2 = (fiat_fp129_int1)(x1 >> 32);
  x3 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  *out1 = x3;
  *out2 = (fiat_fp129_uint1)(0x0 - x2);
}

/*
 * The function fiat_fp129_mulx_u32 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^32
 *   out2 = ⌊arg1 * arg2 / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0xffffffff]
 */
void fiat_fp129_mulx_u32(uint32_t* out1, uint32_t* out2, uint32_t arg1, uint32_t arg2) {
  uint64_t x1;
  uint32_t x2;
  uint32_t x3;
  x1 = ((uint64_t)arg1 * arg2);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (uint32_t)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp129_cmovznz_u32 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp129_cmovznz_u32(uint32_t* out1, fiat_fp129_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  fiat_fp129_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_fp129_int1)(0x0 - x1) & UINT32_C(0xffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_fp129_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_mul(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1, const fiat_fp129_montgomery_domain_field_element arg2) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  fiat_fp129_uint1 x21;
  uint32_t x22;
  fiat_fp129_uint1 x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  fiat_fp129_uint1 x34;
  uint32_t x35;
  fiat_fp129_uint1 x36;
  uint32_t x37;
  fiat_fp129_uint1 x38;
  uint32_t x39;
  fiat_fp129_uint1 x40;
  uint32_t x41;
  fiat_fp129_uint1 x42;
  uint32_t x43;
  fiat_fp129_uint1 x44;
  uint32_t x45;
  fiat_fp129_uint1 x46;
  uint32_t x47;
  fiat_fp129_uint1 x48;
  uint32_t x49;
  fiat_fp129_uint1 x50;
  uint32_t x51;
  fiat_fp129_uint1 x52;
  uint32_t x53;
  uint32_t x54;
  uint32_t x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  fiat_fp129_uint1 x64;
  uint32_t x65;
  fiat_fp129_uint1 x66;
  uint32_t x67;
  fiat_fp129_uint1 x68;
  uint32_t x69;
  fiat_fp129_uint1 x70;
  uint32_t x71;
  uint32_t x72;
  fiat_fp129_uint1 x73;
  uint32_t x74;
  fiat_fp129_uint1 x75;
  uint32_t x76;
  fiat_fp129_uint1 x77;
  uint32_t x78;
  fiat_fp129_uint1 x79;
  uint32_t x80;
  fiat_fp129_uint1 x81;
  uint32_t x82;
  fiat_fp129_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  fiat_fp129_uint1 x93;
  uint32_t x94;
  fiat_fp129_uint1 x95;
  uint32_t x96;
  fiat_fp129_uint1 x97;
  uint32_t x98;
  fiat_fp129_uint1 x99;
  uint32_t x100;
  fiat_fp129_uint1 x101;
  uint32_t x102;
  fiat_fp129_uint1 x103;
  uint32_t x104;
  fiat_fp129_uint1 x105;
  uint32_t x106;
  fiat_fp129_uint1 x107;
  uint32_t x108;
  fiat_fp129_uint1 x109;
  uint32_t x110;
  fiat_fp129_uint1 x111;
  uint32_t x112;
  uint32_t x113;
  uint32_t x114;
  uint32_t x115;
  uint32_t x116;
  uint32_t x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  fiat_fp129_uint1 x124;
  uint32_t x125;
  fiat_fp129_uint1 x126;
  uint32_t x127;
  fiat_fp129_uint1 x128;
  uint32_t x129;
  fiat_fp129_uint1 x130;
  uint32_t x131;
  uint32_t x132;
  fiat_fp129_uint1 x133;
  uint32_t x134;
  fiat_fp129_uint1 x135;
  uint32_t x136;
  fiat_fp129_uint1 x137;
  uint32_t x138;
  fiat_fp129_uint1 x139;
  uint32_t x140;
  fiat_fp129_uint1 x141;
  uint32_t x142;
  fiat_fp129_uint1 x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  fiat_fp129_uint1 x153;
  uint32_t x154;
  fiat_fp129_uint1 x155;
  uint32_t x156;
  fiat_fp129_uint1 x157;
  uint32_t x158;
  fiat_fp129_uint1 x159;
  uint32_t x160;
  fiat_fp129_uint1 x161;
  uint32_t x162;
  fiat_fp129_uint1 x163;
  uint32_t x164;
  fiat_fp129_uint1 x165;
  uint32_t x166;
  fiat_fp129_uint1 x167;
  uint32_t x168;
  fiat_fp129_uint1 x169;
  uint32_t x170;
  fiat_fp129_uint1 x171;
  uint32_t x172;
  uint32_t x173;
  uint32_t x174;
  uint32_t x175;
  uint32_t x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  uint32_t x181;
  uint32_t x182;
  uint32_t x183;
  fiat_fp129_uint1 x184;
  uint32_t x185;
  fiat_fp129_uint1 x186;
  uint32_t x187;
  fiat_fp129_uint1 x188;
  uint32_t x189;
  fiat_fp129_uint1 x190;
  uint32_t x191;
  uint32_t x192;
  fiat_fp129_uint1 x193;
  uint32_t x194;
  fiat_fp129_uint1 x195;
  uint32_t x196;
  fiat_fp129_uint1 x197;
  uint32_t x198;
  fiat_fp129_uint1 x199;
  uint32_t x200;
  fiat_fp129_uint1 x201;
  uint32_t x202;
  fiat_fp129_uint1 x203;
  uint32_t x204;
  uint32_t x205;
  uint32_t x206;
  uint32_t x207;
  uint32_t x208;
  uint32_t x209;
  uint32_t x210;
  uint32_t x211;
  uint32_t x212;
  fiat_fp129_uint1 x213;
  uint32_t x214;
  fiat_fp129_uint1 x215;
  uint32_t x216;
  fiat_fp129_uint1 x217;
  uint32_t x218;
  fiat_fp129_uint1 x219;
  uint32_t x220;
  fiat_fp129_uint1 x221;
  uint32_t x222;
  fiat_fp129_uint1 x223;
  uint32_t x224;
  fiat_fp129_uint1 x225;
  uint32_t x226;
  fiat_fp129_uint1 x227;
  uint32_t x228;
  fiat_fp129_uint1 x229;
  uint32_t x230;
  fiat_fp129_uint1 x231;
  uint32_t x232;
  uint32_t x233;
  uint32_t x234;
  uint32_t x235;
  uint32_t x236;
  uint32_t x237;
  uint32_t x238;
  uint32_t x239;
  uint32_t x240;
  uint32_t x241;
  uint32_t x242;
  uint32_t x243;
  fiat_fp129_uint1 x244;
  uint32_t x245;
  fiat_fp129_uint1 x246;
  uint32_t x247;
  fiat_fp129_uint1 x248;
  uint32_t x249;
  fiat_fp129_uint1 x250;
  uint32_t x251;
  uint32_t x252;
  fiat_fp129_uint1 x253;
  uint32_t x254;
  fiat_fp129_uint1 x255;
  uint32_t x256;
  fiat_fp129_uint1 x257;
  uint32_t x258;
  fiat_fp129_uint1 x259;
  uint32_t x260;
  fiat_fp129_uint1 x261;
  uint32_t x262;
  fiat_fp129_uint1 x263;
  uint32_t x264;
  uint32_t x265;
  uint32_t x266;
  uint32_t x267;
  uint32_t x268;
  uint32_t x269;
  uint32_t x270;
  uint32_t x271;
  uint32_t x272;
  fiat_fp129_uint1 x273;
  uint32_t x274;
  fiat_fp129_uint1 x275;
  uint32_t x276;
  fiat_fp129_uint1 x277;
  uint32_t x278;
  fiat_fp129_uint1 x279;
  uint32_t x280;
  fiat_fp129_uint1 x281;
  uint32_t x282;
  fiat_fp129_uint1 x283;
  uint32_t x284;
  fiat_fp129_uint1 x285;
  uint32_t x286;
  fiat_fp129_uint1 x287;
  uint32_t x288;
  fiat_fp129_uint1 x289;
  uint32_t x290;
  fiat_fp129_uint1 x291;
  uint32_t x292;
  uint32_t x293;
  fiat_fp129_uint1 x294;
  uint32_t x295;
  fiat_fp129_uint1 x296;
  uint32_t x297;
  fiat_fp129_uint1 x298;
  uint32_t x299;
  fiat_fp129_uint1 x300;
  uint32_t x301;
  fiat_fp129_uint1 x302;
  uint32_t x303;
  fiat_fp129_uint1 x304;
  uint32_t x305;
  uint32_t x306;
  uint32_t x307;
  uint32_t x308;
  uint32_t x309;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp129_mulx_u32(&x6, &x7, x5, (arg2[4]));
  fiat_fp129_mulx_u32(&x8, &x9, x5, (arg2[3]));
  fiat_fp129_mulx_u32(&x10, &x11, x5, (arg2[2]));
  fiat_fp129_mulx_u32(&x12, &x13, x5, (arg2[1]));
  fiat_fp129_mulx_u32(&x14, &x15, x5, (arg2[0]));
  fiat_fp129_addcarryx_u32(&x16, &x17, 0x0, x15, x12);
  fiat_fp129_addcarryx_u32(&x18, &x19, x17, x13, x10);
  fiat_fp129_addcarryx_u32(&x20, &x21, x19, x11, x8);
  fiat_fp129_addcarryx_u32(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_fp129_mulx_u32(&x25, &x26, x14, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x27, &x28, x14, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x29, &x30, x14, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x31, &x32, x14, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x33, &x34, 0x0, x32, x29);
  fiat_fp129_addcarryx_u32(&x35, &x36, x34, x30, x27);
  fiat_fp129_addcarryx_u32(&x37, &x38, x36, x28, x25);
  fiat_fp129_addcarryx_u32(&x39, &x40, x38, x26, x14);
  fiat_fp129_addcarryx_u32(&x41, &x42, 0x0, x14, x31);
  fiat_fp129_addcarryx_u32(&x43, &x44, x42, x16, x33);
  fiat_fp129_addcarryx_u32(&x45, &x46, x44, x18, x35);
  fiat_fp129_addcarryx_u32(&x47, &x48, x46, x20, x37);
  fiat_fp129_addcarryx_u32(&x49, &x50, x48, x22, x39);
  fiat_fp129_addcarryx_u32(&x51, &x52, x50, x24, x40);
  fiat_fp129_mulx_u32(&x53, &x54, x1, (arg2[4]));
  fiat_fp129_mulx_u32(&x55, &x56, x1, (arg2[3]));
  fiat_fp129_mulx_u32(&x57, &x58, x1, (arg2[2]));
  fiat_fp129_mulx_u32(&x59, &x60, x1, (arg2[1]));
  fiat_fp129_mulx_u32(&x61, &x62, x1, (arg2[0]));
  fiat_fp129_addcarryx_u32(&x63, &x64, 0x0, x62, x59);
  fiat_fp129_addcarryx_u32(&x65, &x66, x64, x60, x57);
  fiat_fp129_addcarryx_u32(&x67, &x68, x66, x58, x55);
  fiat_fp129_addcarryx_u32(&x69, &x70, x68, x56, x53);
  x71 = (x70 + x54);
  fiat_fp129_addcarryx_u32(&x72, &x73, 0x0, x43, x61);
  fiat_fp129_addcarryx_u32(&x74, &x75, x73, x45, x63);
  fiat_fp129_addcarryx_u32(&x76, &x77, x75, x47, x65);
  fiat_fp129_addcarryx_u32(&x78, &x79, x77, x49, x67);
  fiat_fp129_addcarryx_u32(&x80, &x81, x79, x51, x69);
  fiat_fp129_addcarryx_u32(&x82, &x83, x81, x52, x71);
  fiat_fp129_mulx_u32(&x84, &x85, x72, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x86, &x87, x72, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x88, &x89, x72, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x90, &x91, x72, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x92, &x93, 0x0, x91, x88);
  fiat_fp129_addcarryx_u32(&x94, &x95, x93, x89, x86);
  fiat_fp129_addcarryx_u32(&x96, &x97, x95, x87, x84);
  fiat_fp129_addcarryx_u32(&x98, &x99, x97, x85, x72);
  fiat_fp129_addcarryx_u32(&x100, &x101, 0x0, x72, x90);
  fiat_fp129_addcarryx_u32(&x102, &x103, x101, x74, x92);
  fiat_fp129_addcarryx_u32(&x104, &x105, x103, x76, x94);
  fiat_fp129_addcarryx_u32(&x106, &x107, x105, x78, x96);
  fiat_fp129_addcarryx_u32(&x108, &x109, x107, x80, x98);
  fiat_fp129_addcarryx_u32(&x110, &x111, x109, x82, x99);
  x112 = ((uint32_t)x111 + x83);
  fiat_fp129_mulx_u32(&x113, &x114, x2, (arg2[4]));
  fiat_fp129_mulx_u32(&x115, &x116, x2, (arg2[3]));
  fiat_fp129_mulx_u32(&x117, &x118, x2, (arg2[2]));
  fiat_fp129_mulx_u32(&x119, &x120, x2, (arg2[1]));
  fiat_fp129_mulx_u32(&x121, &x122, x2, (arg2[0]));
  fiat_fp129_addcarryx_u32(&x123, &x124, 0x0, x122, x119);
  fiat_fp129_addcarryx_u32(&x125, &x126, x124, x120, x117);
  fiat_fp129_addcarryx_u32(&x127, &x128, x126, x118, x115);
  fiat_fp129_addcarryx_u32(&x129, &x130, x128, x116, x113);
  x131 = (x130 + x114);
  fiat_fp129_addcarryx_u32(&x132, &x133, 0x0, x102, x121);
  fiat_fp129_addcarryx_u32(&x134, &x135, x133, x104, x123);
  fiat_fp129_addcarryx_u32(&x136, &x137, x135, x106, x125);
  fiat_fp129_addcarryx_u32(&x138, &x139, x137, x108, x127);
  fiat_fp129_addcarryx_u32(&x140, &x141, x139, x110, x129);
  fiat_fp129_addcarryx_u32(&x142, &x143, x141, x112, x131);
  fiat_fp129_mulx_u32(&x144, &x145, x132, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x146, &x147, x132, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x148, &x149, x132, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x150, &x151, x132, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x152, &x153, 0x0, x151, x148);
  fiat_fp129_addcarryx_u32(&x154, &x155, x153, x149, x146);
  fiat_fp129_addcarryx_u32(&x156, &x157, x155, x147, x144);
  fiat_fp129_addcarryx_u32(&x158, &x159, x157, x145, x132);
  fiat_fp129_addcarryx_u32(&x160, &x161, 0x0, x132, x150);
  fiat_fp129_addcarryx_u32(&x162, &x163, x161, x134, x152);
  fiat_fp129_addcarryx_u32(&x164, &x165, x163, x136, x154);
  fiat_fp129_addcarryx_u32(&x166, &x167, x165, x138, x156);
  fiat_fp129_addcarryx_u32(&x168, &x169, x167, x140, x158);
  fiat_fp129_addcarryx_u32(&x170, &x171, x169, x142, x159);
  x172 = ((uint32_t)x171 + x143);
  fiat_fp129_mulx_u32(&x173, &x174, x3, (arg2[4]));
  fiat_fp129_mulx_u32(&x175, &x176, x3, (arg2[3]));
  fiat_fp129_mulx_u32(&x177, &x178, x3, (arg2[2]));
  fiat_fp129_mulx_u32(&x179, &x180, x3, (arg2[1]));
  fiat_fp129_mulx_u32(&x181, &x182, x3, (arg2[0]));
  fiat_fp129_addcarryx_u32(&x183, &x184, 0x0, x182, x179);
  fiat_fp129_addcarryx_u32(&x185, &x186, x184, x180, x177);
  fiat_fp129_addcarryx_u32(&x187, &x188, x186, x178, x175);
  fiat_fp129_addcarryx_u32(&x189, &x190, x188, x176, x173);
  x191 = (x190 + x174);
  fiat_fp129_addcarryx_u32(&x192, &x193, 0x0, x162, x181);
  fiat_fp129_addcarryx_u32(&x194, &x195, x193, x164, x183);
  fiat_fp129_addcarryx_u32(&x196, &x197, x195, x166, x185);
  fiat_fp129_addcarryx_u32(&x198, &x199, x197, x168, x187);
  fiat_fp129_addcarryx_u32(&x200, &x201, x199, x170, x189);
  fiat_fp129_addcarryx_u32(&x202, &x203, x201, x172, x191);
  fiat_fp129_mulx_u32(&x204, &x205, x192, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x206, &x207, x192, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x208, &x209, x192, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x210, &x211, x192, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x212, &x213, 0x0, x211, x208);
  fiat_fp129_addcarryx_u32(&x214, &x215, x213, x209, x206);
  fiat_fp129_addcarryx_u32(&x216, &x217, x215, x207, x204);
  fiat_fp129_addcarryx_u32(&x218, &x219, x217, x205, x192);
  fiat_fp129_addcarryx_u32(&x220, &x221, 0x0, x192, x210);
  fiat_fp129_addcarryx_u32(&x222, &x223, x221, x194, x212);
  fiat_fp129_addcarryx_u32(&x224, &x225, x223, x196, x214);
  fiat_fp129_addcarryx_u32(&x226, &x227, x225, x198, x216);
  fiat_fp129_addcarryx_u32(&x228, &x229, x227, x200, x218);
  fiat_fp129_addcarryx_u32(&x230, &x231, x229, x202, x219);
  x232 = ((uint32_t)x231 + x203);
  fiat_fp129_mulx_u32(&x233, &x234, x4, (arg2[4]));
  fiat_fp129_mulx_u32(&x235, &x236, x4, (arg2[3]));
  fiat_fp129_mulx_u32(&x237, &x238, x4, (arg2[2]));
  fiat_fp129_mulx_u32(&x239, &x240, x4, (arg2[1]));
  fiat_fp129_mulx_u32(&x241, &x242, x4, (arg2[0]));
  fiat_fp129_addcarryx_u32(&x243, &x244, 0x0, x242, x239);
  fiat_fp129_addcarryx_u32(&x245, &x246, x244, x240, x237);
  fiat_fp129_addcarryx_u32(&x247, &x248, x246, x238, x235);
  fiat_fp129_addcarryx_u32(&x249, &x250, x248, x236, x233);
  x251 = (x250 + x234);
  fiat_fp129_addcarryx_u32(&x252, &x253, 0x0, x222, x241);
  fiat_fp129_addcarryx_u32(&x254, &x255, x253, x224, x243);
  fiat_fp129_addcarryx_u32(&x256, &x257, x255, x226, x245);
  fiat_fp129_addcarryx_u32(&x258, &x259, x257, x228, x247);
  fiat_fp129_addcarryx_u32(&x260, &x261, x259, x230, x249);
  fiat_fp129_addcarryx_u32(&x262, &x263, x261, x232, x251);
  fiat_fp129_mulx_u32(&x264, &x265, x252, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x266, &x267, x252, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x268, &x269, x252, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x270, &x271, x252, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x272, &x273, 0x0, x271, x268);
  fiat_fp129_addcarryx_u32(&x274, &x275, x273, x269, x266);
  fiat_fp129_addcarryx_u32(&x276, &x277, x275, x267, x264);
  fiat_fp129_addcarryx_u32(&x278, &x279, x277, x265, x252);
  fiat_fp129_addcarryx_u32(&x280, &x281, 0x0, x252, x270);
  fiat_fp129_addcarryx_u32(&x282, &x283, x281, x254, x272);
  fiat_fp129_addcarryx_u32(&x284, &x285, x283, x256, x274);
  fiat_fp129_addcarryx_u32(&x286, &x287, x285, x258, x276);
  fiat_fp129_addcarryx_u32(&x288, &x289, x287, x260, x278);
  fiat_fp129_addcarryx_u32(&x290, &x291, x289, x262, x279);
  x292 = ((uint32_t)x291 + x263);
  fiat_fp129_subborrowx_u32(&x293, &x294, 0x0, x282, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x295, &x296, x294, x284, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x297, &x298, x296, x286, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x299, &x300, x298, x288, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x301, &x302, x300, x290, 0x1);
  fiat_fp129_subborrowx_u32(&x303, &x304, x302, x292, 0x0);
  fiat_fp129_cmovznz_u32(&x305, x304, x293, x282);
  fiat_fp129_cmovznz_u32(&x306, x304, x295, x284);
  fiat_fp129_cmovznz_u32(&x307, x304, x297, x286);
  fiat_fp129_cmovznz_u32(&x308, x304, x299, x288);
  fiat_fp129_cmovznz_u32(&x309, x304, x301, x290);
  out1[0] = x305;
  out1[1] = x306;
  out1[2] = x307;
  out1[3] = x308;
  out1[4] = x309;
}

/*
 * The function fiat_fp129_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_square(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  fiat_fp129_uint1 x21;
  uint32_t x22;
  fiat_fp129_uint1 x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  fiat_fp129_uint1 x34;
  uint32_t x35;
  fiat_fp129_uint1 x36;
  uint32_t x37;
  fiat_fp129_uint1 x38;
  uint32_t x39;
  fiat_fp129_uint1 x40;
  uint32_t x41;
  fiat_fp129_uint1 x42;
  uint32_t x43;
  fiat_fp129_uint1 x44;
  uint32_t x45;
  fiat_fp129_uint1 x46;
  uint32_t x47;
  fiat_fp129_uint1 x48;
  uint32_t x49;
  fiat_fp129_uint1 x50;
  uint32_t x51;
  fiat_fp129_uint1 x52;
  uint32_t x53;
  uint32_t x54;
  uint32_t x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  fiat_fp129_uint1 x64;
  uint32_t x65;
  fiat_fp129_uint1 x66;
  uint32_t x67;
  fiat_fp129_uint1 x68;
  uint32_t x69;
  fiat_fp129_uint1 x70;
  uint32_t x71;
  uint32_t x72;
  fiat_fp129_uint1 x73;
  uint32_t x74;
  fiat_fp129_uint1 x75;
  uint32_t x76;
  fiat_fp129_uint1 x77;
  uint32_t x78;
  fiat_fp129_uint1 x79;
  uint32_t x80;
  fiat_fp129_uint1 x81;
  uint32_t x82;
  fiat_fp129_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  fiat_fp129_uint1 x93;
  uint32_t x94;
  fiat_fp129_uint1 x95;
  uint32_t x96;
  fiat_fp129_uint1 x97;
  uint32_t x98;
  fiat_fp129_uint1 x99;
  uint32_t x100;
  fiat_fp129_uint1 x101;
  uint32_t x102;
  fiat_fp129_uint1 x103;
  uint32_t x104;
  fiat_fp129_uint1 x105;
  uint32_t x106;
  fiat_fp129_uint1 x107;
  uint32_t x108;
  fiat_fp129_uint1 x109;
  uint32_t x110;
  fiat_fp129_uint1 x111;
  uint32_t x112;
  uint32_t x113;
  uint32_t x114;
  uint32_t x115;
  uint32_t x116;
  uint32_t x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  fiat_fp129_uint1 x124;
  uint32_t x125;
  fiat_fp129_uint1 x126;
  uint32_t x127;
  fiat_fp129_uint1 x128;
  uint32_t x129;
  fiat_fp129_uint1 x130;
  uint32_t x131;
  uint32_t x132;
  fiat_fp129_uint1 x133;
  uint32_t x134;
  fiat_fp129_uint1 x135;
  uint32_t x136;
  fiat_fp129_uint1 x137;
  uint32_t x138;
  fiat_fp129_uint1 x139;
  uint32_t x140;
  fiat_fp129_uint1 x141;
  uint32_t x142;
  fiat_fp129_uint1 x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  fiat_fp129_uint1 x153;
  uint32_t x154;
  fiat_fp129_uint1 x155;
  uint32_t x156;
  fiat_fp129_uint1 x157;
  uint32_t x158;
  fiat_fp129_uint1 x159;
  uint32_t x160;
  fiat_fp129_uint1 x161;
  uint32_t x162;
  fiat_fp129_uint1 x163;
  uint32_t x164;
  fiat_fp129_uint1 x165;
  uint32_t x166;
  fiat_fp129_uint1 x167;
  uint32_t x168;
  fiat_fp129_uint1 x169;
  uint32_t x170;
  fiat_fp129_uint1 x171;
  uint32_t x172;
  uint32_t x173;
  uint32_t x174;
  uint32_t x175;
  uint32_t x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  uint32_t x181;
  uint32_t x182;
  uint32_t x183;
  fiat_fp129_uint1 x184;
  uint32_t x185;
  fiat_fp129_uint1 x186;
  uint32_t x187;
  fiat_fp129_uint1 x188;
  uint32_t x189;
  fiat_fp129_uint1 x190;
  uint32_t x191;
  uint32_t x192;
  fiat_fp129_uint1 x193;
  uint32_t x194;
  fiat_fp129_uint1 x195;
  uint32_t x196;
  fiat_fp129_uint1 x197;
  uint32_t x198;
  fiat_fp129_uint1 x199;
  uint32_t x200;
  fiat_fp129_uint1 x201;
  uint32_t x202;
  fiat_fp129_uint1 x203;
  uint32_t x204;
  uint32_t x205;
  uint32_t x206;
  uint32_t x207;
  uint32_t x208;
  uint32_t x209;
  uint32_t x210;
  uint32_t x211;
  uint32_t x212;
  fiat_fp129_uint1 x213;
  uint32_t x214;
  fiat_fp129_uint1 x215;
  uint32_t x216;
  fiat_fp129_uint1 x217;
  uint32_t x218;
  fiat_fp129_uint1 x219;
  uint32_t x220;
  fiat_fp129_uint1 x221;
  uint32_t x222;
  fiat_fp129_uint1 x223;
  uint32_t x224;
  fiat_fp129_uint1 x225;
  uint32_t x226;
  fiat_fp129_uint1 x227;
  uint32_t x228;
  fiat_fp129_uint1 x229;
  uint32_t x230;
  fiat_fp129_uint1 x231;
  uint32_t x232;
  uint32_t x233;
  uint32_t x234;
  uint32_t x235;
  uint32_t x236;
  uint32_t x237;
  uint32_t x238;
  uint32_t x239;
  uint32_t x240;
  uint32_t x241;
  uint32_t x242;
  uint32_t x243;
  fiat_fp129_uint1 x244;
  uint32_t x245;
  fiat_fp129_uint1 x246;
  uint32_t x247;
  fiat_fp129_uint1 x248;
  uint32_t x249;
  fiat_fp129_uint1 x250;
  uint32_t x251;
  uint32_t x252;
  fiat_fp129_uint1 x253;
  uint32_t x254;
  fiat_fp129_uint1 x255;
  uint32_t x256;
  fiat_fp129_uint1 x257;
  uint32_t x258;
  fiat_fp129_uint1 x259;
  uint32_t x260;
  fiat_fp129_uint1 x261;
  uint32_t x262;
  fiat_fp129_uint1 x263;
  uint32_t x264;
  uint32_t x265;
  uint32_t x266;
  uint32_t x267;
  uint32_t x268;
  uint32_t x269;
  uint32_t x270;
  uint32_t x271;
  uint32_t x272;
  fiat_fp129_uint1 x273;
  uint32_t x274;
  fiat_fp129_uint1 x275;
  uint32_t x276;
  fiat_fp129_uint1 x277;
  uint32_t x278;
  fiat_fp129_uint1 x279;
  uint32_t x280;
  fiat_fp129_uint1 x281;
  uint32_t x282;
  fiat_fp129_uint1 x283;
  uint32_t x284;
  fiat_fp129_uint1 x285;
  uint32_t x286;
  fiat_fp129_uint1 x287;
  uint32_t x288;
  fiat_fp129_uint1 x289;
  uint32_t x290;
  fiat_fp129_uint1 x291;
  uint32_t x292;
  uint32_t x293;
  fiat_fp129_uint1 x294;
  uint32_t x295;
  fiat_fp129_uint1 x296;
  uint32_t x297;
  fiat_fp129_uint1 x298;
  uint32_t x299;
  fiat_fp129_uint1 x300;
  uint32_t x301;
  fiat_fp129_uint1 x302;
  uint32_t x303;
  fiat_fp129_uint1 x304;
  uint32_t x305;
  uint32_t x306;
  uint32_t x307;
  uint32_t x308;
  uint32_t x309;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp129_mulx_u32(&x6, &x7, x5, (arg1[4]));
  fiat_fp129_mulx_u32(&x8, &x9, x5, (arg1[3]));
  fiat_fp129_mulx_u32(&x10, &x11, x5, (arg1[2]));
  fiat_fp129_mulx_u32(&x12, &x13, x5, (arg1[1]));
  fiat_fp129_mulx_u32(&x14, &x15, x5, (arg1[0]));
  fiat_fp129_addcarryx_u32(&x16, &x17, 0x0, x15, x12);
  fiat_fp129_addcarryx_u32(&x18, &x19, x17, x13, x10);
  fiat_fp129_addcarryx_u32(&x20, &x21, x19, x11, x8);
  fiat_fp129_addcarryx_u32(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_fp129_mulx_u32(&x25, &x26, x14, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x27, &x28, x14, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x29, &x30, x14, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x31, &x32, x14, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x33, &x34, 0x0, x32, x29);
  fiat_fp129_addcarryx_u32(&x35, &x36, x34, x30, x27);
  fiat_fp129_addcarryx_u32(&x37, &x38, x36, x28, x25);
  fiat_fp129_addcarryx_u32(&x39, &x40, x38, x26, x14);
  fiat_fp129_addcarryx_u32(&x41, &x42, 0x0, x14, x31);
  fiat_fp129_addcarryx_u32(&x43, &x44, x42, x16, x33);
  fiat_fp129_addcarryx_u32(&x45, &x46, x44, x18, x35);
  fiat_fp129_addcarryx_u32(&x47, &x48, x46, x20, x37);
  fiat_fp129_addcarryx_u32(&x49, &x50, x48, x22, x39);
  fiat_fp129_addcarryx_u32(&x51, &x52, x50, x24, x40);
  fiat_fp129_mulx_u32(&x53, &x54, x1, (arg1[4]));
  fiat_fp129_mulx_u32(&x55, &x56, x1, (arg1[3]));
  fiat_fp129_mulx_u32(&x57, &x58, x1, (arg1[2]));
  fiat_fp129_mulx_u32(&x59, &x60, x1, (arg1[1]));
  fiat_fp129_mulx_u32(&x61, &x62, x1, (arg1[0]));
  fiat_fp129_addcarryx_u32(&x63, &x64, 0x0, x62, x59);
  fiat_fp129_addcarryx_u32(&x65, &x66, x64, x60, x57);
  fiat_fp129_addcarryx_u32(&x67, &x68, x66, x58, x55);
  fiat_fp129_addcarryx_u32(&x69, &x70, x68, x56, x53);
  x71 = (x70 + x54);
  fiat_fp129_addcarryx_u32(&x72, &x73, 0x0, x43, x61);
  fiat_fp129_addcarryx_u32(&x74, &x75, x73, x45, x63);
  fiat_fp129_addcarryx_u32(&x76, &x77, x75, x47, x65);
  fiat_fp129_addcarryx_u32(&x78, &x79, x77, x49, x67);
  fiat_fp129_addcarryx_u32(&x80, &x81, x79, x51, x69);
  fiat_fp129_addcarryx_u32(&x82, &x83, x81, x52, x71);
  fiat_fp129_mulx_u32(&x84, &x85, x72, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x86, &x87, x72, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x88, &x89, x72, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x90, &x91, x72, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x92, &x93, 0x0, x91, x88);
  fiat_fp129_addcarryx_u32(&x94, &x95, x93, x89, x86);
  fiat_fp129_addcarryx_u32(&x96, &x97, x95, x87, x84);
  fiat_fp129_addcarryx_u32(&x98, &x99, x97, x85, x72);
  fiat_fp129_addcarryx_u32(&x100, &x101, 0x0, x72, x90);
  fiat_fp129_addcarryx_u32(&x102, &x103, x101, x74, x92);
  fiat_fp129_addcarryx_u32(&x104, &x105, x103, x76, x94);
  fiat_fp129_addcarryx_u32(&x106, &x107, x105, x78, x96);
  fiat_fp129_addcarryx_u32(&x108, &x109, x107, x80, x98);
  fiat_fp129_addcarryx_u32(&x110, &x111, x109, x82, x99);
  x112 = ((uint32_t)x111 + x83);
  fiat_fp129_mulx_u32(&x113, &x114, x2, (arg1[4]));
  fiat_fp129_mulx_u32(&x115, &x116, x2, (arg1[3]));
  fiat_fp129_mulx_u32(&x117, &x118, x2, (arg1[2]));
  fiat_fp129_mulx_u32(&x119, &x120, x2, (arg1[1]));
  fiat_fp129_mulx_u32(&x121, &x122, x2, (arg1[0]));
  fiat_fp129_addcarryx_u32(&x123, &x124, 0x0, x122, x119);
  fiat_fp129_addcarryx_u32(&x125, &x126, x124, x120, x117);
  fiat_fp129_addcarryx_u32(&x127, &x128, x126, x118, x115);
  fiat_fp129_addcarryx_u32(&x129, &x130, x128, x116, x113);
  x131 = (x130 + x114);
  fiat_fp129_addcarryx_u32(&x132, &x133, 0x0, x102, x121);
  fiat_fp129_addcarryx_u32(&x134, &x135, x133, x104, x123);
  fiat_fp129_addcarryx_u32(&x136, &x137, x135, x106, x125);
  fiat_fp129_addcarryx_u32(&x138, &x139, x137, x108, x127);
  fiat_fp129_addcarryx_u32(&x140, &x141, x139, x110, x129);
  fiat_fp129_addcarryx_u32(&x142, &x143, x141, x112, x131);
  fiat_fp129_mulx_u32(&x144, &x145, x132, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x146, &x147, x132, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x148, &x149, x132, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x150, &x151, x132, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x152, &x153, 0x0, x151, x148);
  fiat_fp129_addcarryx_u32(&x154, &x155, x153, x149, x146);
  fiat_fp129_addcarryx_u32(&x156, &x157, x155, x147, x144);
  fiat_fp129_addcarryx_u32(&x158, &x159, x157, x145, x132);
  fiat_fp129_addcarryx_u32(&x160, &x161, 0x0, x132, x150);
  fiat_fp129_addcarryx_u32(&x162, &x163, x161, x134, x152);
  fiat_fp129_addcarryx_u32(&x164, &x165, x163, x136, x154);
  fiat_fp129_addcarryx_u32(&x166, &x167, x165, x138, x156);
  fiat_fp129_addcarryx_u32(&x168, &x169, x167, x140, x158);
  fiat_fp129_addcarryx_u32(&x170, &x171, x169, x142, x159);
  x172 = ((uint32_t)x171 + x143);
  fiat_fp129_mulx_u32(&x173, &x174, x3, (arg1[4]));
  fiat_fp129_mulx_u32(&x175, &x176, x3, (arg1[3]));
  fiat_fp129_mulx_u32(&x177, &x178, x3, (arg1[2]));
  fiat_fp129_mulx_u32(&x179, &x180, x3, (arg1[1]));
  fiat_fp129_mulx_u32(&x181, &x182, x3, (arg1[0]));
  fiat_fp129_addcarryx_u32(&x183, &x184, 0x0, x182, x179);
  fiat_fp129_addcarryx_u32(&x185, &x186, x184, x180, x177);
  fiat_fp129_addcarryx_u32(&x187, &x188, x186, x178, x175);
  fiat_fp129_addcarryx_u32(&x189, &x190, x188, x176, x173);
  x191 = (x190 + x174);
  fiat_fp129_addcarryx_u32(&x192, &x193, 0x0, x162, x181);
  fiat_fp129_addcarryx_u32(&x194, &x195, x193, x164, x183);
  fiat_fp129_addcarryx_u32(&x196, &x197, x195, x166, x185);
  fiat_fp129_addcarryx_u32(&x198, &x199, x197, x168, x187);
  fiat_fp129_addcarryx_u32(&x200, &x201, x199, x170, x189);
  fiat_fp129_addcarryx_u32(&x202, &x203, x201, x172, x191);
  fiat_fp129_mulx_u32(&x204, &x205, x192, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x206, &x207, x192, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x208, &x209, x192, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x210, &x211, x192, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x212, &x213, 0x0, x211, x208);
  fiat_fp129_addcarryx_u32(&x214, &x215, x213, x209, x206);
  fiat_fp129_addcarryx_u32(&x216, &x217, x215, x207, x204);
  fiat_fp129_addcarryx_u32(&x218, &x219, x217, x205, x192);
  fiat_fp129_addcarryx_u32(&x220, &x221, 0x0, x192, x210);
  fiat_fp129_addcarryx_u32(&x222, &x223, x221, x194, x212);
  fiat_fp129_addcarryx_u32(&x224, &x225, x223, x196, x214);
  fiat_fp129_addcarryx_u32(&x226, &x227, x225, x198, x216);
  fiat_fp129_addcarryx_u32(&x228, &x229, x227, x200, x218);
  fiat_fp129_addcarryx_u32(&x230, &x231, x229, x202, x219);
  x232 = ((uint32_t)x231 + x203);
  fiat_fp129_mulx_u32(&x233, &x234, x4, (arg1[4]));
  fiat_fp129_mulx_u32(&x235, &x236, x4, (arg1[3]));
  fiat_fp129_mulx_u32(&x237, &x238, x4, (arg1[2]));
  fiat_fp129_mulx_u32(&x239, &x240, x4, (arg1[1]));
  fiat_fp129_mulx_u32(&x241, &x242, x4, (arg1[0]));
  fiat_fp129_addcarryx_u32(&x243, &x244, 0x0, x242, x239);
  fiat_fp129_addcarryx_u32(&x245, &x246, x244, x240, x237);
  fiat_fp129_addcarryx_u32(&x247, &x248, x246, x238, x235);
  fiat_fp129_addcarryx_u32(&x249, &x250, x248, x236, x233);
  x251 = (x250 + x234);
  fiat_fp129_addcarryx_u32(&x252, &x253, 0x0, x222, x241);
  fiat_fp129_addcarryx_u32(&x254, &x255, x253, x224, x243);
  fiat_fp129_addcarryx_u32(&x256, &x257, x255, x226, x245);
  fiat_fp129_addcarryx_u32(&x258, &x259, x257, x228, x247);
  fiat_fp129_addcarryx_u32(&x260, &x261, x259, x230, x249);
  fiat_fp129_addcarryx_u32(&x262, &x263, x261, x232, x251);
  fiat_fp129_mulx_u32(&x264, &x265, x252, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x266, &x267, x252, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x268, &x269, x252, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x270, &x271, x252, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x272, &x273, 0x0, x271, x268);
  fiat_fp129_addcarryx_u32(&x274, &x275, x273, x269, x266);
  fiat_fp129_addcarryx_u32(&x276, &x277, x275, x267, x264);
  fiat_fp129_addcarryx_u32(&x278, &x279, x277, x265, x252);
  fiat_fp129_addcarryx_u32(&x280, &x281, 0x0, x252, x270);
  fiat_fp129_addcarryx_u32(&x282, &x283, x281, x254, x272);
  fiat_fp129_addcarryx_u32(&x284, &x285, x283, x256, x274);
  fiat_fp129_addcarryx_u32(&x286, &x287, x285, x258, x276);
  fiat_fp129_addcarryx_u32(&x288, &x289, x287, x260, x278);
  fiat_fp129_addcarryx_u32(&x290, &x291, x289, x262, x279);
  x292 = ((uint32_t)x291 + x263);
  fiat_fp129_subborrowx_u32(&x293, &x294, 0x0, x282, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x295, &x296, x294, x284, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x297, &x298, x296, x286, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x299, &x300, x298, x288, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x301, &x302, x300, x290, 0x1);
  fiat_fp129_subborrowx_u32(&x303, &x304, x302, x292, 0x0);
  fiat_fp129_cmovznz_u32(&x305, x304, x293, x282);
  fiat_fp129_cmovznz_u32(&x306, x304, x295, x284);
  fiat_fp129_cmovznz_u32(&x307, x304, x297, x286);
  fiat_fp129_cmovznz_u32(&x308, x304, x299, x288);
  fiat_fp129_cmovznz_u32(&x309, x304, x301, x290);
  out1[0] = x305;
  out1[1] = x306;
  out1[2] = x307;
  out1[3] = x308;
  out1[4] = x309;
}

/*
 * The function fiat_fp129_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_add(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1, const fiat_fp129_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp129_uint1 x2;
  uint32_t x3;
  fiat_fp129_uint1 x4;
  uint32_t x5;
  fiat_fp129_uint1 x6;
  uint32_t x7;
  fiat_fp129_uint1 x8;
  uint32_t x9;
  fiat_fp129_uint1 x10;
  uint32_t x11;
  fiat_fp129_uint1 x12;
  uint32_t x13;
  fiat_fp129_uint1 x14;
  uint32_t x15;
  fiat_fp129_uint1 x16;
  uint32_t x17;
  fiat_fp129_uint1 x18;
  uint32_t x19;
  fiat_fp129_uint1 x20;
  uint32_t x21;
  fiat_fp129_uint1 x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  fiat_fp129_addcarryx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp129_addcarryx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp129_addcarryx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp129_addcarryx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp129_addcarryx_u32(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_fp129_subborrowx_u32(&x11, &x12, 0x0, x1, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x13, &x14, x12, x3, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x15, &x16, x14, x5, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x17, &x18, x16, x7, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x19, &x20, x18, x9, 0x1);
  fiat_fp129_subborrowx_u32(&x21, &x22, x20, x10, 0x0);
  fiat_fp129_cmovznz_u32(&x23, x22, x11, x1);
  fiat_fp129_cmovznz_u32(&x24, x22, x13, x3);
  fiat_fp129_cmovznz_u32(&x25, x22, x15, x5);
  fiat_fp129_cmovznz_u32(&x26, x22, x17, x7);
  fiat_fp129_cmovznz_u32(&x27, x22, x19, x9);
  out1[0] = x23;
  out1[1] = x24;
  out1[2] = x25;
  out1[3] = x26;
  out1[4] = x27;
}

/*
 * The function fiat_fp129_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_sub(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1, const fiat_fp129_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp129_uint1 x2;
  uint32_t x3;
  fiat_fp129_uint1 x4;
  uint32_t x5;
  fiat_fp129_uint1 x6;
  uint32_t x7;
  fiat_fp129_uint1 x8;
  uint32_t x9;
  fiat_fp129_uint1 x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp129_uint1 x13;
  uint32_t x14;
  fiat_fp129_uint1 x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  fiat_fp129_uint1 x21;
  fiat_fp129_subborrowx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp129_subborrowx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp129_subborrowx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp129_subborrowx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp129_subborrowx_u32(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_fp129_cmovznz_u32(&x11, x10, 0x0, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x12, &x13, 0x0, x1, x11);
  fiat_fp129_addcarryx_u32(&x14, &x15, x13, x3, (x11 & UINT32_C(0xbfffffff)));
  fiat_fp129_addcarryx_u32(&x16, &x17, x15, x5, (x11 & UINT32_C(0x66426c8e)));
  fiat_fp129_addcarryx_u32(&x18, &x19, x17, x7, (x11 & UINT32_C(0xb6fd0493)));
  fiat_fp129_addcarryx_u32(&x20, &x21, x19, x9, (fiat_fp129_uint1)(x11 & 0x1));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_fp129_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_opp(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1) {
  uint32_t x1;
  fiat_fp129_uint1 x2;
  uint32_t x3;
  fiat_fp129_uint1 x4;
  uint32_t x5;
  fiat_fp129_uint1 x6;
  uint32_t x7;
  fiat_fp129_uint1 x8;
  uint32_t x9;
  fiat_fp129_uint1 x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp129_uint1 x13;
  uint32_t x14;
  fiat_fp129_uint1 x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  fiat_fp129_uint1 x21;
  fiat_fp129_subborrowx_u32(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_fp129_subborrowx_u32(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_fp129_subborrowx_u32(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_fp129_subborrowx_u32(&x7, &x8, x6, 0x0, (arg1[3]));
  fiat_fp129_subborrowx_u32(&x9, &x10, x8, 0x0, (arg1[4]));
  fiat_fp129_cmovznz_u32(&x11, x10, 0x0, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x12, &x13, 0x0, x1, x11);
  fiat_fp129_addcarryx_u32(&x14, &x15, x13, x3, (x11 & UINT32_C(0xbfffffff)));
  fiat_fp129_addcarryx_u32(&x16, &x17, x15, x5, (x11 & UINT32_C(0x66426c8e)));
  fiat_fp129_addcarryx_u32(&x18, &x19, x17, x7, (x11 & UINT32_C(0xb6fd0493)));
  fiat_fp129_addcarryx_u32(&x20, &x21, x19, x9, (fiat_fp129_uint1)(x11 & 0x1));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_fp129_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^32)⁻¹ mod m)^5) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_from_montgomery(fiat_fp129_non_montgomery_domain_field_element out1, const fiat_fp129_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp129_uint1 x11;
  uint32_t x12;
  fiat_fp129_uint1 x13;
  uint32_t x14;
  fiat_fp129_uint1 x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  fiat_fp129_uint1 x21;
  uint32_t x22;
  fiat_fp129_uint1 x23;
  uint32_t x24;
  fiat_fp129_uint1 x25;
  uint32_t x26;
  fiat_fp129_uint1 x27;
  uint32_t x28;
  fiat_fp129_uint1 x29;
  uint32_t x30;
  fiat_fp129_uint1 x31;
  uint32_t x32;
  fiat_fp129_uint1 x33;
  uint32_t x34;
  fiat_fp129_uint1 x35;
  uint32_t x36;
  uint32_t x37;
  uint32_t x38;
  uint32_t x39;
  uint32_t x40;
  uint32_t x41;
  uint32_t x42;
  uint32_t x43;
  uint32_t x44;
  fiat_fp129_uint1 x45;
  uint32_t x46;
  fiat_fp129_uint1 x47;
  uint32_t x48;
  fiat_fp129_uint1 x49;
  uint32_t x50;
  fiat_fp129_uint1 x51;
  uint32_t x52;
  fiat_fp129_uint1 x53;
  uint32_t x54;
  fiat_fp129_uint1 x55;
  uint32_t x56;
  fiat_fp129_uint1 x57;
  uint32_t x58;
  fiat_fp129_uint1 x59;
  uint32_t x60;
  fiat_fp129_uint1 x61;
  uint32_t x62;
  fiat_fp129_uint1 x63;
  uint32_t x64;
  fiat_fp129_uint1 x65;
  uint32_t x66;
  fiat_fp129_uint1 x67;
  uint32_t x68;
  fiat_fp129_uint1 x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  fiat_fp129_uint1 x79;
  uint32_t x80;
  fiat_fp129_uint1 x81;
  uint32_t x82;
  fiat_fp129_uint1 x83;
  uint32_t x84;
  fiat_fp129_uint1 x85;
  uint32_t x86;
  fiat_fp129_uint1 x87;
  uint32_t x88;
  fiat_fp129_uint1 x89;
  uint32_t x90;
  fiat_fp129_uint1 x91;
  uint32_t x92;
  fiat_fp129_uint1 x93;
  uint32_t x94;
  fiat_fp129_uint1 x95;
  uint32_t x96;
  fiat_fp129_uint1 x97;
  uint32_t x98;
  fiat_fp129_uint1 x99;
  uint32_t x100;
  fiat_fp129_uint1 x101;
  uint32_t x102;
  fiat_fp129_uint1 x103;
  uint32_t x104;
  uint32_t x105;
  uint32_t x106;
  uint32_t x107;
  uint32_t x108;
  uint32_t x109;
  uint32_t x110;
  uint32_t x111;
  uint32_t x112;
  fiat_fp129_uint1 x113;
  uint32_t x114;
  fiat_fp129_uint1 x115;
  uint32_t x116;
  fiat_fp129_uint1 x117;
  uint32_t x118;
  fiat_fp129_uint1 x119;
  uint32_t x120;
  fiat_fp129_uint1 x121;
  uint32_t x122;
  fiat_fp129_uint1 x123;
  uint32_t x124;
  fiat_fp129_uint1 x125;
  uint32_t x126;
  fiat_fp129_uint1 x127;
  uint32_t x128;
  fiat_fp129_uint1 x129;
  uint32_t x130;
  fiat_fp129_uint1 x131;
  uint32_t x132;
  fiat_fp129_uint1 x133;
  uint32_t x134;
  fiat_fp129_uint1 x135;
  uint32_t x136;
  fiat_fp129_uint1 x137;
  uint32_t x138;
  uint32_t x139;
  uint32_t x140;
  uint32_t x141;
  uint32_t x142;
  uint32_t x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  fiat_fp129_uint1 x147;
  uint32_t x148;
  fiat_fp129_uint1 x149;
  uint32_t x150;
  fiat_fp129_uint1 x151;
  uint32_t x152;
  fiat_fp129_uint1 x153;
  uint32_t x154;
  fiat_fp129_uint1 x155;
  uint32_t x156;
  fiat_fp129_uint1 x157;
  uint32_t x158;
  fiat_fp129_uint1 x159;
  uint32_t x160;
  fiat_fp129_uint1 x161;
  uint32_t x162;
  fiat_fp129_uint1 x163;
  uint32_t x164;
  uint32_t x165;
  fiat_fp129_uint1 x166;
  uint32_t x167;
  fiat_fp129_uint1 x168;
  uint32_t x169;
  fiat_fp129_uint1 x170;
  uint32_t x171;
  fiat_fp129_uint1 x172;
  uint32_t x173;
  fiat_fp129_uint1 x174;
  uint32_t x175;
  fiat_fp129_uint1 x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  uint32_t x181;
  x1 = (arg1[0]);
  fiat_fp129_mulx_u32(&x2, &x3, x1, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x4, &x5, x1, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x6, &x7, x1, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x8, &x9, x1, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x10, &x11, 0x0, x9, x6);
  fiat_fp129_addcarryx_u32(&x12, &x13, x11, x7, x4);
  fiat_fp129_addcarryx_u32(&x14, &x15, x13, x5, x2);
  fiat_fp129_addcarryx_u32(&x16, &x17, x15, x3, x1);
  fiat_fp129_addcarryx_u32(&x18, &x19, 0x0, x1, x8);
  fiat_fp129_addcarryx_u32(&x20, &x21, x19, 0x0, x10);
  fiat_fp129_addcarryx_u32(&x22, &x23, x21, 0x0, x12);
  fiat_fp129_addcarryx_u32(&x24, &x25, x23, 0x0, x14);
  fiat_fp129_addcarryx_u32(&x26, &x27, x25, 0x0, x16);
  fiat_fp129_addcarryx_u32(&x28, &x29, 0x0, x20, (arg1[1]));
  fiat_fp129_addcarryx_u32(&x30, &x31, x29, x22, 0x0);
  fiat_fp129_addcarryx_u32(&x32, &x33, x31, x24, 0x0);
  fiat_fp129_addcarryx_u32(&x34, &x35, x33, x26, 0x0);
  fiat_fp129_mulx_u32(&x36, &x37, x28, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x38, &x39, x28, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x40, &x41, x28, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x42, &x43, x28, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x44, &x45, 0x0, x43, x40);
  fiat_fp129_addcarryx_u32(&x46, &x47, x45, x41, x38);
  fiat_fp129_addcarryx_u32(&x48, &x49, x47, x39, x36);
  fiat_fp129_addcarryx_u32(&x50, &x51, x49, x37, x28);
  fiat_fp129_addcarryx_u32(&x52, &x53, 0x0, x28, x42);
  fiat_fp129_addcarryx_u32(&x54, &x55, x53, x30, x44);
  fiat_fp129_addcarryx_u32(&x56, &x57, x55, x32, x46);
  fiat_fp129_addcarryx_u32(&x58, &x59, x57, x34, x48);
  fiat_fp129_addcarryx_u32(&x60, &x61, x59, (x35 + ((uint32_t)x27 + x17)), x50);
  fiat_fp129_addcarryx_u32(&x62, &x63, 0x0, x54, (arg1[2]));
  fiat_fp129_addcarryx_u32(&x64, &x65, x63, x56, 0x0);
  fiat_fp129_addcarryx_u32(&x66, &x67, x65, x58, 0x0);
  fiat_fp129_addcarryx_u32(&x68, &x69, x67, x60, 0x0);
  fiat_fp129_mulx_u32(&x70, &x71, x62, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x72, &x73, x62, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x74, &x75, x62, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x76, &x77, x62, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x78, &x79, 0x0, x77, x74);
  fiat_fp129_addcarryx_u32(&x80, &x81, x79, x75, x72);
  fiat_fp129_addcarryx_u32(&x82, &x83, x81, x73, x70);
  fiat_fp129_addcarryx_u32(&x84, &x85, x83, x71, x62);
  fiat_fp129_addcarryx_u32(&x86, &x87, 0x0, x62, x76);
  fiat_fp129_addcarryx_u32(&x88, &x89, x87, x64, x78);
  fiat_fp129_addcarryx_u32(&x90, &x91, x89, x66, x80);
  fiat_fp129_addcarryx_u32(&x92, &x93, x91, x68, x82);
  fiat_fp129_addcarryx_u32(&x94, &x95, x93, (x69 + ((uint32_t)x61 + x51)), x84);
  fiat_fp129_addcarryx_u32(&x96, &x97, 0x0, x88, (arg1[3]));
  fiat_fp129_addcarryx_u32(&x98, &x99, x97, x90, 0x0);
  fiat_fp129_addcarryx_u32(&x100, &x101, x99, x92, 0x0);
  fiat_fp129_addcarryx_u32(&x102, &x103, x101, x94, 0x0);
  fiat_fp129_mulx_u32(&x104, &x105, x96, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x106, &x107, x96, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x108, &x109, x96, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x110, &x111, x96, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x112, &x113, 0x0, x111, x108);
  fiat_fp129_addcarryx_u32(&x114, &x115, x113, x109, x106);
  fiat_fp129_addcarryx_u32(&x116, &x117, x115, x107, x104);
  fiat_fp129_addcarryx_u32(&x118, &x119, x117, x105, x96);
  fiat_fp129_addcarryx_u32(&x120, &x121, 0x0, x96, x110);
  fiat_fp129_addcarryx_u32(&x122, &x123, x121, x98, x112);
  fiat_fp129_addcarryx_u32(&x124, &x125, x123, x100, x114);
  fiat_fp129_addcarryx_u32(&x126, &x127, x125, x102, x116);
  fiat_fp129_addcarryx_u32(&x128, &x129, x127, (x103 + ((uint32_t)x95 + x85)), x118);
  fiat_fp129_addcarryx_u32(&x130, &x131, 0x0, x122, (arg1[4]));
  fiat_fp129_addcarryx_u32(&x132, &x133, x131, x124, 0x0);
  fiat_fp129_addcarryx_u32(&x134, &x135, x133, x126, 0x0);
  fiat_fp129_addcarryx_u32(&x136, &x137, x135, x128, 0x0);
  fiat_fp129_mulx_u32(&x138, &x139, x130, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x140, &x141, x130, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x142, &x143, x130, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x144, &x145, x130, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x146, &x147, 0x0, x145, x142);
  fiat_fp129_addcarryx_u32(&x148, &x149, x147, x143, x140);
  fiat_fp129_addcarryx_u32(&x150, &x151, x149, x141, x138);
  fiat_fp129_addcarryx_u32(&x152, &x153, x151, x139, x130);
  fiat_fp129_addcarryx_u32(&x154, &x155, 0x0, x130, x144);
  fiat_fp129_addcarryx_u32(&x156, &x157, x155, x132, x146);
  fiat_fp129_addcarryx_u32(&x158, &x159, x157, x134, x148);
  fiat_fp129_addcarryx_u32(&x160, &x161, x159, x136, x150);
  fiat_fp129_addcarryx_u32(&x162, &x163, x161, (x137 + ((uint32_t)x129 + x119)), x152);
  x164 = ((uint32_t)x163 + x153);
  fiat_fp129_subborrowx_u32(&x165, &x166, 0x0, x156, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x167, &x168, x166, x158, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x169, &x170, x168, x160, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x171, &x172, x170, x162, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x173, &x174, x172, x164, 0x1);
  fiat_fp129_subborrowx_u32(&x175, &x176, x174, 0x0, 0x0);
  fiat_fp129_cmovznz_u32(&x177, x176, x165, x156);
  fiat_fp129_cmovznz_u32(&x178, x176, x167, x158);
  fiat_fp129_cmovznz_u32(&x179, x176, x169, x160);
  fiat_fp129_cmovznz_u32(&x180, x176, x171, x162);
  fiat_fp129_cmovznz_u32(&x181, x176, x173, x164);
  out1[0] = x177;
  out1[1] = x178;
  out1[2] = x179;
  out1[3] = x180;
  out1[4] = x181;
}

/*
 * The function fiat_fp129_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_to_montgomery(fiat_fp129_montgomery_domain_field_element out1, const fiat_fp129_non_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  fiat_fp129_uint1 x15;
  uint32_t x16;
  fiat_fp129_uint1 x17;
  uint32_t x18;
  fiat_fp129_uint1 x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  fiat_fp129_uint1 x29;
  uint32_t x30;
  fiat_fp129_uint1 x31;
  uint32_t x32;
  fiat_fp129_uint1 x33;
  uint32_t x34;
  fiat_fp129_uint1 x35;
  uint32_t x36;
  fiat_fp129_uint1 x37;
  uint32_t x38;
  fiat_fp129_uint1 x39;
  uint32_t x40;
  fiat_fp129_uint1 x41;
  uint32_t x42;
  fiat_fp129_uint1 x43;
  uint32_t x44;
  fiat_fp129_uint1 x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  uint32_t x53;
  uint32_t x54;
  fiat_fp129_uint1 x55;
  uint32_t x56;
  fiat_fp129_uint1 x57;
  uint32_t x58;
  fiat_fp129_uint1 x59;
  uint32_t x60;
  fiat_fp129_uint1 x61;
  uint32_t x62;
  fiat_fp129_uint1 x63;
  uint32_t x64;
  fiat_fp129_uint1 x65;
  uint32_t x66;
  fiat_fp129_uint1 x67;
  uint32_t x68;
  uint32_t x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  fiat_fp129_uint1 x77;
  uint32_t x78;
  fiat_fp129_uint1 x79;
  uint32_t x80;
  fiat_fp129_uint1 x81;
  uint32_t x82;
  fiat_fp129_uint1 x83;
  uint32_t x84;
  fiat_fp129_uint1 x85;
  uint32_t x86;
  fiat_fp129_uint1 x87;
  uint32_t x88;
  fiat_fp129_uint1 x89;
  uint32_t x90;
  fiat_fp129_uint1 x91;
  uint32_t x92;
  fiat_fp129_uint1 x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  uint32_t x99;
  uint32_t x100;
  uint32_t x101;
  uint32_t x102;
  fiat_fp129_uint1 x103;
  uint32_t x104;
  fiat_fp129_uint1 x105;
  uint32_t x106;
  fiat_fp129_uint1 x107;
  uint32_t x108;
  fiat_fp129_uint1 x109;
  uint32_t x110;
  fiat_fp129_uint1 x111;
  uint32_t x112;
  fiat_fp129_uint1 x113;
  uint32_t x114;
  fiat_fp129_uint1 x115;
  uint32_t x116;
  uint32_t x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  fiat_fp129_uint1 x125;
  uint32_t x126;
  fiat_fp129_uint1 x127;
  uint32_t x128;
  fiat_fp129_uint1 x129;
  uint32_t x130;
  fiat_fp129_uint1 x131;
  uint32_t x132;
  fiat_fp129_uint1 x133;
  uint32_t x134;
  fiat_fp129_uint1 x135;
  uint32_t x136;
  fiat_fp129_uint1 x137;
  uint32_t x138;
  fiat_fp129_uint1 x139;
  uint32_t x140;
  fiat_fp129_uint1 x141;
  uint32_t x142;
  uint32_t x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  fiat_fp129_uint1 x151;
  uint32_t x152;
  fiat_fp129_uint1 x153;
  uint32_t x154;
  fiat_fp129_uint1 x155;
  uint32_t x156;
  fiat_fp129_uint1 x157;
  uint32_t x158;
  fiat_fp129_uint1 x159;
  uint32_t x160;
  fiat_fp129_uint1 x161;
  uint32_t x162;
  fiat_fp129_uint1 x163;
  uint32_t x164;
  uint32_t x165;
  uint32_t x166;
  uint32_t x167;
  uint32_t x168;
  uint32_t x169;
  uint32_t x170;
  uint32_t x171;
  uint32_t x172;
  fiat_fp129_uint1 x173;
  uint32_t x174;
  fiat_fp129_uint1 x175;
  uint32_t x176;
  fiat_fp129_uint1 x177;
  uint32_t x178;
  fiat_fp129_uint1 x179;
  uint32_t x180;
  fiat_fp129_uint1 x181;
  uint32_t x182;
  fiat_fp129_uint1 x183;
  uint32_t x184;
  fiat_fp129_uint1 x185;
  uint32_t x186;
  fiat_fp129_uint1 x187;
  uint32_t x188;
  fiat_fp129_uint1 x189;
  uint32_t x190;
  uint32_t x191;
  uint32_t x192;
  uint32_t x193;
  uint32_t x194;
  uint32_t x195;
  uint32_t x196;
  uint32_t x197;
  uint32_t x198;
  fiat_fp129_uint1 x199;
  uint32_t x200;
  fiat_fp129_uint1 x201;
  uint32_t x202;
  fiat_fp129_uint1 x203;
  uint32_t x204;
  fiat_fp129_uint1 x205;
  uint32_t x206;
  fiat_fp129_uint1 x207;
  uint32_t x208;
  fiat_fp129_uint1 x209;
  uint32_t x210;
  fiat_fp129_uint1 x211;
  uint32_t x212;
  uint32_t x213;
  uint32_t x214;
  uint32_t x215;
  uint32_t x216;
  uint32_t x217;
  uint32_t x218;
  uint32_t x219;
  uint32_t x220;
  fiat_fp129_uint1 x221;
  uint32_t x222;
  fiat_fp129_uint1 x223;
  uint32_t x224;
  fiat_fp129_uint1 x225;
  uint32_t x226;
  fiat_fp129_uint1 x227;
  uint32_t x228;
  fiat_fp129_uint1 x229;
  uint32_t x230;
  fiat_fp129_uint1 x231;
  uint32_t x232;
  fiat_fp129_uint1 x233;
  uint32_t x234;
  fiat_fp129_uint1 x235;
  uint32_t x236;
  fiat_fp129_uint1 x237;
  uint32_t x238;
  uint32_t x239;
  fiat_fp129_uint1 x240;
  uint32_t x241;
  fiat_fp129_uint1 x242;
  uint32_t x243;
  fiat_fp129_uint1 x244;
  uint32_t x245;
  fiat_fp129_uint1 x246;
  uint32_t x247;
  fiat_fp129_uint1 x248;
  uint32_t x249;
  fiat_fp129_uint1 x250;
  uint32_t x251;
  uint32_t x252;
  uint32_t x253;
  uint32_t x254;
  uint32_t x255;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp129_mulx_u32(&x6, &x7, x5, UINT32_C(0x220f4934));
  fiat_fp129_mulx_u32(&x8, &x9, x5, UINT32_C(0x5f9d2cab));
  fiat_fp129_mulx_u32(&x10, &x11, x5, UINT32_C(0x8de98971));
  fiat_fp129_mulx_u32(&x12, &x13, x5, UINT32_C(0x526341d8));
  fiat_fp129_addcarryx_u32(&x14, &x15, 0x0, x13, x10);
  fiat_fp129_addcarryx_u32(&x16, &x17, x15, x11, x8);
  fiat_fp129_addcarryx_u32(&x18, &x19, x17, x9, x6);
  fiat_fp129_mulx_u32(&x20, &x21, x12, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x22, &x23, x12, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x24, &x25, x12, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x26, &x27, x12, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x28, &x29, 0x0, x27, x24);
  fiat_fp129_addcarryx_u32(&x30, &x31, x29, x25, x22);
  fiat_fp129_addcarryx_u32(&x32, &x33, x31, x23, x20);
  fiat_fp129_addcarryx_u32(&x34, &x35, x33, x21, x12);
  fiat_fp129_addcarryx_u32(&x36, &x37, 0x0, x12, x26);
  fiat_fp129_addcarryx_u32(&x38, &x39, x37, x14, x28);
  fiat_fp129_addcarryx_u32(&x40, &x41, x39, x16, x30);
  fiat_fp129_addcarryx_u32(&x42, &x43, x41, x18, x32);
  fiat_fp129_addcarryx_u32(&x44, &x45, x43, (x19 + x7), x34);
  fiat_fp129_mulx_u32(&x46, &x47, x1, UINT32_C(0x220f4934));
  fiat_fp129_mulx_u32(&x48, &x49, x1, UINT32_C(0x5f9d2cab));
  fiat_fp129_mulx_u32(&x50, &x51, x1, UINT32_C(0x8de98971));
  fiat_fp129_mulx_u32(&x52, &x53, x1, UINT32_C(0x526341d8));
  fiat_fp129_addcarryx_u32(&x54, &x55, 0x0, x53, x50);
  fiat_fp129_addcarryx_u32(&x56, &x57, x55, x51, x48);
  fiat_fp129_addcarryx_u32(&x58, &x59, x57, x49, x46);
  fiat_fp129_addcarryx_u32(&x60, &x61, 0x0, x38, x52);
  fiat_fp129_addcarryx_u32(&x62, &x63, x61, x40, x54);
  fiat_fp129_addcarryx_u32(&x64, &x65, x63, x42, x56);
  fiat_fp129_addcarryx_u32(&x66, &x67, x65, x44, x58);
  fiat_fp129_mulx_u32(&x68, &x69, x60, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x70, &x71, x60, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x72, &x73, x60, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x74, &x75, x60, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x76, &x77, 0x0, x75, x72);
  fiat_fp129_addcarryx_u32(&x78, &x79, x77, x73, x70);
  fiat_fp129_addcarryx_u32(&x80, &x81, x79, x71, x68);
  fiat_fp129_addcarryx_u32(&x82, &x83, x81, x69, x60);
  fiat_fp129_addcarryx_u32(&x84, &x85, 0x0, x60, x74);
  fiat_fp129_addcarryx_u32(&x86, &x87, x85, x62, x76);
  fiat_fp129_addcarryx_u32(&x88, &x89, x87, x64, x78);
  fiat_fp129_addcarryx_u32(&x90, &x91, x89, x66, x80);
  fiat_fp129_addcarryx_u32(&x92, &x93, x91, ((x67 + ((uint32_t)x45 + x35)) + (x59 + x47)), x82);
  fiat_fp129_mulx_u32(&x94, &x95, x2, UINT32_C(0x220f4934));
  fiat_fp129_mulx_u32(&x96, &x97, x2, UINT32_C(0x5f9d2cab));
  fiat_fp129_mulx_u32(&x98, &x99, x2, UINT32_C(0x8de98971));
  fiat_fp129_mulx_u32(&x100, &x101, x2, UINT32_C(0x526341d8));
  fiat_fp129_addcarryx_u32(&x102, &x103, 0x0, x101, x98);
  fiat_fp129_addcarryx_u32(&x104, &x105, x103, x99, x96);
  fiat_fp129_addcarryx_u32(&x106, &x107, x105, x97, x94);
  fiat_fp129_addcarryx_u32(&x108, &x109, 0x0, x86, x100);
  fiat_fp129_addcarryx_u32(&x110, &x111, x109, x88, x102);
  fiat_fp129_addcarryx_u32(&x112, &x113, x111, x90, x104);
  fiat_fp129_addcarryx_u32(&x114, &x115, x113, x92, x106);
  fiat_fp129_mulx_u32(&x116, &x117, x108, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x118, &x119, x108, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x120, &x121, x108, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x122, &x123, x108, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x124, &x125, 0x0, x123, x120);
  fiat_fp129_addcarryx_u32(&x126, &x127, x125, x121, x118);
  fiat_fp129_addcarryx_u32(&x128, &x129, x127, x119, x116);
  fiat_fp129_addcarryx_u32(&x130, &x131, x129, x117, x108);
  fiat_fp129_addcarryx_u32(&x132, &x133, 0x0, x108, x122);
  fiat_fp129_addcarryx_u32(&x134, &x135, x133, x110, x124);
  fiat_fp129_addcarryx_u32(&x136, &x137, x135, x112, x126);
  fiat_fp129_addcarryx_u32(&x138, &x139, x137, x114, x128);
  fiat_fp129_addcarryx_u32(&x140, &x141, x139, ((x115 + ((uint32_t)x93 + x83)) + (x107 + x95)), x130);
  fiat_fp129_mulx_u32(&x142, &x143, x3, UINT32_C(0x220f4934));
  fiat_fp129_mulx_u32(&x144, &x145, x3, UINT32_C(0x5f9d2cab));
  fiat_fp129_mulx_u32(&x146, &x147, x3, UINT32_C(0x8de98971));
  fiat_fp129_mulx_u32(&x148, &x149, x3, UINT32_C(0x526341d8));
  fiat_fp129_addcarryx_u32(&x150, &x151, 0x0, x149, x146);
  fiat_fp129_addcarryx_u32(&x152, &x153, x151, x147, x144);
  fiat_fp129_addcarryx_u32(&x154, &x155, x153, x145, x142);
  fiat_fp129_addcarryx_u32(&x156, &x157, 0x0, x134, x148);
  fiat_fp129_addcarryx_u32(&x158, &x159, x157, x136, x150);
  fiat_fp129_addcarryx_u32(&x160, &x161, x159, x138, x152);
  fiat_fp129_addcarryx_u32(&x162, &x163, x161, x140, x154);
  fiat_fp129_mulx_u32(&x164, &x165, x156, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x166, &x167, x156, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x168, &x169, x156, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x170, &x171, x156, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x172, &x173, 0x0, x171, x168);
  fiat_fp129_addcarryx_u32(&x174, &x175, x173, x169, x166);
  fiat_fp129_addcarryx_u32(&x176, &x177, x175, x167, x164);
  fiat_fp129_addcarryx_u32(&x178, &x179, x177, x165, x156);
  fiat_fp129_addcarryx_u32(&x180, &x181, 0x0, x156, x170);
  fiat_fp129_addcarryx_u32(&x182, &x183, x181, x158, x172);
  fiat_fp129_addcarryx_u32(&x184, &x185, x183, x160, x174);
  fiat_fp129_addcarryx_u32(&x186, &x187, x185, x162, x176);
  fiat_fp129_addcarryx_u32(&x188, &x189, x187, ((x163 + ((uint32_t)x141 + x131)) + (x155 + x143)), x178);
  fiat_fp129_mulx_u32(&x190, &x191, x4, UINT32_C(0x220f4934));
  fiat_fp129_mulx_u32(&x192, &x193, x4, UINT32_C(0x5f9d2cab));
  fiat_fp129_mulx_u32(&x194, &x195, x4, UINT32_C(0x8de98971));
  fiat_fp129_mulx_u32(&x196, &x197, x4, UINT32_C(0x526341d8));
  fiat_fp129_addcarryx_u32(&x198, &x199, 0x0, x197, x194);
  fiat_fp129_addcarryx_u32(&x200, &x201, x199, x195, x192);
  fiat_fp129_addcarryx_u32(&x202, &x203, x201, x193, x190);
  fiat_fp129_addcarryx_u32(&x204, &x205, 0x0, x182, x196);
  fiat_fp129_addcarryx_u32(&x206, &x207, x205, x184, x198);
  fiat_fp129_addcarryx_u32(&x208, &x209, x207, x186, x200);
  fiat_fp129_addcarryx_u32(&x210, &x211, x209, x188, x202);
  fiat_fp129_mulx_u32(&x212, &x213, x204, UINT32_C(0xb6fd0493));
  fiat_fp129_mulx_u32(&x214, &x215, x204, UINT32_C(0x66426c8e));
  fiat_fp129_mulx_u32(&x216, &x217, x204, UINT32_C(0xbfffffff));
  fiat_fp129_mulx_u32(&x218, &x219, x204, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x220, &x221, 0x0, x219, x216);
  fiat_fp129_addcarryx_u32(&x222, &x223, x221, x217, x214);
  fiat_fp129_addcarryx_u32(&x224, &x225, x223, x215, x212);
  fiat_fp129_addcarryx_u32(&x226, &x227, x225, x213, x204);
  fiat_fp129_addcarryx_u32(&x228, &x229, 0x0, x204, x218);
  fiat_fp129_addcarryx_u32(&x230, &x231, x229, x206, x220);
  fiat_fp129_addcarryx_u32(&x232, &x233, x231, x208, x222);
  fiat_fp129_addcarryx_u32(&x234, &x235, x233, x210, x224);
  fiat_fp129_addcarryx_u32(&x236, &x237, x235, ((x211 + ((uint32_t)x189 + x179)) + (x203 + x191)), x226);
  x238 = ((uint32_t)x237 + x227);
  fiat_fp129_subborrowx_u32(&x239, &x240, 0x0, x230, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x241, &x242, x240, x232, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x243, &x244, x242, x234, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x245, &x246, x244, x236, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x247, &x248, x246, x238, 0x1);
  fiat_fp129_subborrowx_u32(&x249, &x250, x248, 0x0, 0x0);
  fiat_fp129_cmovznz_u32(&x251, x250, x239, x230);
  fiat_fp129_cmovznz_u32(&x252, x250, x241, x232);
  fiat_fp129_cmovznz_u32(&x253, x250, x243, x234);
  fiat_fp129_cmovznz_u32(&x254, x250, x245, x236);
  fiat_fp129_cmovznz_u32(&x255, x250, x247, x238);
  out1[0] = x251;
  out1[1] = x252;
  out1[2] = x253;
  out1[3] = x254;
  out1[4] = x255;
}

/*
 * The function fiat_fp129_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp129_nonzero(uint32_t* out1, const uint32_t arg1[5]) {
  uint32_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | ((arg1[2]) | ((arg1[3]) | (arg1[4])))));
  *out1 = x1;
}

/*
 * The function fiat_fp129_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp129_selectznz(uint32_t out1[5], fiat_fp129_uint1 arg1, const uint32_t arg2[5], const uint32_t arg3[5]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  fiat_fp129_cmovznz_u32(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_fp129_cmovznz_u32(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_fp129_cmovznz_u32(&x3, arg1, (arg2[2]), (arg3[2]));
  fiat_fp129_cmovznz_u32(&x4, arg1, (arg2[3]), (arg3[3]));
  fiat_fp129_cmovznz_u32(&x5, arg1, (arg2[4]), (arg3[4]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
  out1[4] = x5;
}

/*
 * The function fiat_fp129_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..16]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x1]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x1]]
 */
void fiat_fp129_to_bytes(uint8_t out1[17], const uint32_t arg1[5]) {
  fiat_fp129_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint8_t x6;
  uint32_t x7;
  uint8_t x8;
  uint32_t x9;
  uint8_t x10;
  uint8_t x11;
  uint8_t x12;
  uint32_t x13;
  uint8_t x14;
  uint32_t x15;
  uint8_t x16;
  uint8_t x17;
  uint8_t x18;
  uint32_t x19;
  uint8_t x20;
  uint32_t x21;
  uint8_t x22;
  uint8_t x23;
  uint8_t x24;
  uint32_t x25;
  uint8_t x26;
  uint32_t x27;
  uint8_t x28;
  uint8_t x29;
  x1 = (fiat_fp129_uint1)(arg1[4]);
  x2 = (arg1[3]);
  x3 = (arg1[2]);
  x4 = (arg1[1]);
  x5 = (arg1[0]);
  x6 = (uint8_t)(x5 & UINT8_C(0xff));
  x7 = (x5 >> 8);
  x8 = (uint8_t)(x7 & UINT8_C(0xff));
  x9 = (x7 >> 8);
  x10 = (uint8_t)(x9 & UINT8_C(0xff));
  x11 = (uint8_t)(x9 >> 8);
  x12 = (uint8_t)(x4 & UINT8_C(0xff));
  x13 = (x4 >> 8);
  x14 = (uint8_t)(x13 & UINT8_C(0xff));
  x15 = (x13 >> 8);
  x16 = (uint8_t)(x15 & UINT8_C(0xff));
  x17 = (uint8_t)(x15 >> 8);
  x18 = (uint8_t)(x3 & UINT8_C(0xff));
  x19 = (x3 >> 8);
  x20 = (uint8_t)(x19 & UINT8_C(0xff));
  x21 = (x19 >> 8);
  x22 = (uint8_t)(x21 & UINT8_C(0xff));
  x23 = (uint8_t)(x21 >> 8);
  x24 = (uint8_t)(x2 & UINT8_C(0xff));
  x25 = (x2 >> 8);
  x26 = (uint8_t)(x25 & UINT8_C(0xff));
  x27 = (x25 >> 8);
  x28 = (uint8_t)(x27 & UINT8_C(0xff));
  x29 = (uint8_t)(x27 >> 8);
  out1[0] = x6;
  out1[1] = x8;
  out1[2] = x10;
  out1[3] = x11;
  out1[4] = x12;
  out1[5] = x14;
  out1[6] = x16;
  out1[7] = x17;
  out1[8] = x18;
  out1[9] = x20;
  out1[10] = x22;
  out1[11] = x23;
  out1[12] = x24;
  out1[13] = x26;
  out1[14] = x28;
  out1[15] = x29;
  out1[16] = x1;
}

/*
 * The function fiat_fp129_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x1]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x1]]
 */
void fiat_fp129_from_bytes(uint32_t out1[5], const uint8_t arg1[17]) {
  fiat_fp129_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint8_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint8_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint8_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  uint8_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  x1 = (fiat_fp129_uint1)(arg1[16]);
  x2 = ((uint32_t)(arg1[15]) << 24);
  x3 = ((uint32_t)(arg1[14]) << 16);
  x4 = ((uint32_t)(arg1[13]) << 8);
  x5 = (arg1[12]);
  x6 = ((uint32_t)(arg1[11]) << 24);
  x7 = ((uint32_t)(arg1[10]) << 16);
  x8 = ((uint32_t)(arg1[9]) << 8);
  x9 = (arg1[8]);
  x10 = ((uint32_t)(arg1[7]) << 24);
  x11 = ((uint32_t)(arg1[6]) << 16);
  x12 = ((uint32_t)(arg1[5]) << 8);
  x13 = (arg1[4]);
  x14 = ((uint32_t)(arg1[3]) << 24);
  x15 = ((uint32_t)(arg1[2]) << 16);
  x16 = ((uint32_t)(arg1[1]) << 8);
  x17 = (arg1[0]);
  x18 = (x16 + (uint32_t)x17);
  x19 = (x15 + x18);
  x20 = (x14 + x19);
  x21 = (x12 + (uint32_t)x13);
  x22 = (x11 + x21);
  x23 = (x10 + x22);
  x24 = (x8 + (uint32_t)x9);
  x25 = (x7 + x24);
  x26 = (x6 + x25);
  x27 = (x4 + (uint32_t)x5);
  x28 = (x3 + x27);
  x29 = (x2 + x28);
  out1[0] = x20;
  out1[1] = x23;
  out1[2] = x26;
  out1[3] = x29;
  out1[4] = x1;
}

/*
 * The function fiat_fp129_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp129_set_one(fiat_fp129_montgomery_domain_field_element out1) {
  out1[0] = UINT32_C(0x9549e834);
  out1[1] = 0x0;
  out1[2] = UINT32_C(0xfdabd501);
  out1[3] = UINT32_C(0x6fe8ab42);
  out1[4] = 0x1;
}

/*
 * The function fiat_fp129_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp129_msat(uint32_t out1[6]) {
  out1[0] = UINT32_C(0xffffffff);
  out1[1] = UINT32_C(0xbfffffff);
  out1[2] = UINT32_C(0x66426c8e);
  out1[3] = UINT32_C(0xb6fd0493);
  out1[4] = 0x1;
  out1[5] = 0x0;
}

/*
 * The function fiat_fp129_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp129_divstep_precomp(uint32_t out1[5]) {
  out1[0] = UINT32_C(0xd0b9524a);
  out1[1] = UINT32_C(0xe1deae61);
  out1[2] = UINT32_C(0x2f6aee47);
  out1[3] = UINT32_C(0x641a163);
  out1[4] = 0x1;
}

/*
 * The function fiat_fp129_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp129_divstep(uint32_t* out1, uint32_t out2[6], uint32_t out3[6], uint32_t out4[5], uint32_t out5[5], uint32_t arg1, const uint32_t arg2[6], const uint32_t arg3[6], const uint32_t arg4[5], const uint32_t arg5[5]) {
  uint32_t x1;
  fiat_fp129_uint1 x2;
  fiat_fp129_uint1 x3;
  uint32_t x4;
  fiat_fp129_uint1 x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  fiat_fp129_uint1 x14;
  uint32_t x15;
  fiat_fp129_uint1 x16;
  uint32_t x17;
  fiat_fp129_uint1 x18;
  uint32_t x19;
  fiat_fp129_uint1 x20;
  uint32_t x21;
  fiat_fp129_uint1 x22;
  uint32_t x23;
  fiat_fp129_uint1 x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  fiat_fp129_uint1 x37;
  uint32_t x38;
  fiat_fp129_uint1 x39;
  uint32_t x40;
  fiat_fp129_uint1 x41;
  uint32_t x42;
  fiat_fp129_uint1 x43;
  uint32_t x44;
  fiat_fp129_uint1 x45;
  uint32_t x46;
  fiat_fp129_uint1 x47;
  uint32_t x48;
  fiat_fp129_uint1 x49;
  uint32_t x50;
  fiat_fp129_uint1 x51;
  uint32_t x52;
  fiat_fp129_uint1 x53;
  uint32_t x54;
  fiat_fp129_uint1 x55;
  uint32_t x56;
  fiat_fp129_uint1 x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  fiat_fp129_uint1 x64;
  uint32_t x65;
  fiat_fp129_uint1 x66;
  uint32_t x67;
  fiat_fp129_uint1 x68;
  uint32_t x69;
  fiat_fp129_uint1 x70;
  uint32_t x71;
  fiat_fp129_uint1 x72;
  uint32_t x73;
  uint32_t x74;
  fiat_fp129_uint1 x75;
  uint32_t x76;
  fiat_fp129_uint1 x77;
  uint32_t x78;
  fiat_fp129_uint1 x79;
  uint32_t x80;
  fiat_fp129_uint1 x81;
  uint32_t x82;
  fiat_fp129_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  fiat_fp129_uint1 x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  fiat_fp129_uint1 x97;
  uint32_t x98;
  fiat_fp129_uint1 x99;
  uint32_t x100;
  fiat_fp129_uint1 x101;
  uint32_t x102;
  fiat_fp129_uint1 x103;
  uint32_t x104;
  fiat_fp129_uint1 x105;
  uint32_t x106;
  fiat_fp129_uint1 x107;
  uint32_t x108;
  uint32_t x109;
  uint32_t x110;
  uint32_t x111;
  uint32_t x112;
  uint32_t x113;
  fiat_fp129_uint1 x114;
  uint32_t x115;
  fiat_fp129_uint1 x116;
  uint32_t x117;
  fiat_fp129_uint1 x118;
  uint32_t x119;
  fiat_fp129_uint1 x120;
  uint32_t x121;
  fiat_fp129_uint1 x122;
  uint32_t x123;
  fiat_fp129_uint1 x124;
  uint32_t x125;
  fiat_fp129_uint1 x126;
  uint32_t x127;
  fiat_fp129_uint1 x128;
  uint32_t x129;
  fiat_fp129_uint1 x130;
  uint32_t x131;
  fiat_fp129_uint1 x132;
  uint32_t x133;
  fiat_fp129_uint1 x134;
  uint32_t x135;
  fiat_fp129_uint1 x136;
  uint32_t x137;
  uint32_t x138;
  uint32_t x139;
  uint32_t x140;
  uint32_t x141;
  uint32_t x142;
  uint32_t x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  fiat_fp129_addcarryx_u32(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_fp129_uint1)((fiat_fp129_uint1)(x1 >> 31) & (fiat_fp129_uint1)((arg3[0]) & 0x1));
  fiat_fp129_addcarryx_u32(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_fp129_cmovznz_u32(&x6, x3, arg1, x4);
  fiat_fp129_cmovznz_u32(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_fp129_cmovznz_u32(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_fp129_cmovznz_u32(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_fp129_cmovznz_u32(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_fp129_cmovznz_u32(&x11, x3, (arg2[4]), (arg3[4]));
  fiat_fp129_cmovznz_u32(&x12, x3, (arg2[5]), (arg3[5]));
  fiat_fp129_addcarryx_u32(&x13, &x14, 0x0, 0x1, (~(arg2[0])));
  fiat_fp129_addcarryx_u32(&x15, &x16, x14, 0x0, (~(arg2[1])));
  fiat_fp129_addcarryx_u32(&x17, &x18, x16, 0x0, (~(arg2[2])));
  fiat_fp129_addcarryx_u32(&x19, &x20, x18, 0x0, (~(arg2[3])));
  fiat_fp129_addcarryx_u32(&x21, &x22, x20, 0x0, (~(arg2[4])));
  fiat_fp129_addcarryx_u32(&x23, &x24, x22, 0x0, (~(arg2[5])));
  fiat_fp129_cmovznz_u32(&x25, x3, (arg3[0]), x13);
  fiat_fp129_cmovznz_u32(&x26, x3, (arg3[1]), x15);
  fiat_fp129_cmovznz_u32(&x27, x3, (arg3[2]), x17);
  fiat_fp129_cmovznz_u32(&x28, x3, (arg3[3]), x19);
  fiat_fp129_cmovznz_u32(&x29, x3, (arg3[4]), x21);
  fiat_fp129_cmovznz_u32(&x30, x3, (arg3[5]), x23);
  fiat_fp129_cmovznz_u32(&x31, x3, (arg4[0]), (arg5[0]));
  fiat_fp129_cmovznz_u32(&x32, x3, (arg4[1]), (arg5[1]));
  fiat_fp129_cmovznz_u32(&x33, x3, (arg4[2]), (arg5[2]));
  fiat_fp129_cmovznz_u32(&x34, x3, (arg4[3]), (arg5[3]));
  fiat_fp129_cmovznz_u32(&x35, x3, (arg4[4]), (arg5[4]));
  fiat_fp129_addcarryx_u32(&x36, &x37, 0x0, x31, x31);
  fiat_fp129_addcarryx_u32(&x38, &x39, x37, x32, x32);
  fiat_fp129_addcarryx_u32(&x40, &x41, x39, x33, x33);
  fiat_fp129_addcarryx_u32(&x42, &x43, x41, x34, x34);
  fiat_fp129_addcarryx_u32(&x44, &x45, x43, x35, x35);
  fiat_fp129_subborrowx_u32(&x46, &x47, 0x0, x36, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x48, &x49, x47, x38, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x50, &x51, x49, x40, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x52, &x53, x51, x42, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x54, &x55, x53, x44, 0x1);
  fiat_fp129_subborrowx_u32(&x56, &x57, x55, x45, 0x0);
  x58 = (arg4[4]);
  x59 = (arg4[3]);
  x60 = (arg4[2]);
  x61 = (arg4[1]);
  x62 = (arg4[0]);
  fiat_fp129_subborrowx_u32(&x63, &x64, 0x0, 0x0, x62);
  fiat_fp129_subborrowx_u32(&x65, &x66, x64, 0x0, x61);
  fiat_fp129_subborrowx_u32(&x67, &x68, x66, 0x0, x60);
  fiat_fp129_subborrowx_u32(&x69, &x70, x68, 0x0, x59);
  fiat_fp129_subborrowx_u32(&x71, &x72, x70, 0x0, x58);
  fiat_fp129_cmovznz_u32(&x73, x72, 0x0, UINT32_C(0xffffffff));
  fiat_fp129_addcarryx_u32(&x74, &x75, 0x0, x63, x73);
  fiat_fp129_addcarryx_u32(&x76, &x77, x75, x65, (x73 & UINT32_C(0xbfffffff)));
  fiat_fp129_addcarryx_u32(&x78, &x79, x77, x67, (x73 & UINT32_C(0x66426c8e)));
  fiat_fp129_addcarryx_u32(&x80, &x81, x79, x69, (x73 & UINT32_C(0xb6fd0493)));
  fiat_fp129_addcarryx_u32(&x82, &x83, x81, x71, (fiat_fp129_uint1)(x73 & 0x1));
  fiat_fp129_cmovznz_u32(&x84, x3, (arg5[0]), x74);
  fiat_fp129_cmovznz_u32(&x85, x3, (arg5[1]), x76);
  fiat_fp129_cmovznz_u32(&x86, x3, (arg5[2]), x78);
  fiat_fp129_cmovznz_u32(&x87, x3, (arg5[3]), x80);
  fiat_fp129_cmovznz_u32(&x88, x3, (arg5[4]), x82);
  x89 = (fiat_fp129_uint1)(x25 & 0x1);
  fiat_fp129_cmovznz_u32(&x90, x89, 0x0, x7);
  fiat_fp129_cmovznz_u32(&x91, x89, 0x0, x8);
  fiat_fp129_cmovznz_u32(&x92, x89, 0x0, x9);
  fiat_fp129_cmovznz_u32(&x93, x89, 0x0, x10);
  fiat_fp129_cmovznz_u32(&x94, x89, 0x0, x11);
  fiat_fp129_cmovznz_u32(&x95, x89, 0x0, x12);
  fiat_fp129_addcarryx_u32(&x96, &x97, 0x0, x25, x90);
  fiat_fp129_addcarryx_u32(&x98, &x99, x97, x26, x91);
  fiat_fp129_addcarryx_u32(&x100, &x101, x99, x27, x92);
  fiat_fp129_addcarryx_u32(&x102, &x103, x101, x28, x93);
  fiat_fp129_addcarryx_u32(&x104, &x105, x103, x29, x94);
  fiat_fp129_addcarryx_u32(&x106, &x107, x105, x30, x95);
  fiat_fp129_cmovznz_u32(&x108, x89, 0x0, x31);
  fiat_fp129_cmovznz_u32(&x109, x89, 0x0, x32);
  fiat_fp129_cmovznz_u32(&x110, x89, 0x0, x33);
  fiat_fp129_cmovznz_u32(&x111, x89, 0x0, x34);
  fiat_fp129_cmovznz_u32(&x112, x89, 0x0, x35);
  fiat_fp129_addcarryx_u32(&x113, &x114, 0x0, x84, x108);
  fiat_fp129_addcarryx_u32(&x115, &x116, x114, x85, x109);
  fiat_fp129_addcarryx_u32(&x117, &x118, x116, x86, x110);
  fiat_fp129_addcarryx_u32(&x119, &x120, x118, x87, x111);
  fiat_fp129_addcarryx_u32(&x121, &x122, x120, x88, x112);
  fiat_fp129_subborrowx_u32(&x123, &x124, 0x0, x113, UINT32_C(0xffffffff));
  fiat_fp129_subborrowx_u32(&x125, &x126, x124, x115, UINT32_C(0xbfffffff));
  fiat_fp129_subborrowx_u32(&x127, &x128, x126, x117, UINT32_C(0x66426c8e));
  fiat_fp129_subborrowx_u32(&x129, &x130, x128, x119, UINT32_C(0xb6fd0493));
  fiat_fp129_subborrowx_u32(&x131, &x132, x130, x121, 0x1);
  fiat_fp129_subborrowx_u32(&x133, &x134, x132, x122, 0x0);
  fiat_fp129_addcarryx_u32(&x135, &x136, 0x0, x6, 0x1);
  x137 = ((x96 >> 1) | ((x98 << 31) & UINT32_C(0xffffffff)));
  x138 = ((x98 >> 1) | ((x100 << 31) & UINT32_C(0xffffffff)));
  x139 = ((x100 >> 1) | ((x102 << 31) & UINT32_C(0xffffffff)));
  x140 = ((x102 >> 1) | ((x104 << 31) & UINT32_C(0xffffffff)));
  x141 = ((x104 >> 1) | ((x106 << 31) & UINT32_C(0xffffffff)));
  x142 = ((x106 & UINT32_C(0x80000000)) | (x106 >> 1));
  fiat_fp129_cmovznz_u32(&x143, x57, x46, x36);
  fiat_fp129_cmovznz_u32(&x144, x57, x48, x38);
  fiat_fp129_cmovznz_u32(&x145, x57, x50, x40);
  fiat_fp129_cmovznz_u32(&x146, x57, x52, x42);
  fiat_fp129_cmovznz_u32(&x147, x57, x54, x44);
  fiat_fp129_cmovznz_u32(&x148, x134, x123, x113);
  fiat_fp129_cmovznz_u32(&x149, x134, x125, x115);
  fiat_fp129_cmovznz_u32(&x150, x134, x127, x117);
  fiat_fp129_cmovznz_u32(&x151, x134, x129, x119);
  fiat_fp129_cmovznz_u32(&x152, x134, x131, x121);
  *out1 = x135;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out2[4] = x11;
  out2[5] = x12;
  out3[0] = x137;
  out3[1] = x138;
  out3[2] = x139;
  out3[3] = x140;
  out3[4] = x141;
  out3[5] = x142;
  out4[0] = x143;
  out4[1] = x144;
  out4[2] = x145;
  out4[3] = x146;
  out4[4] = x147;
  out5[0] = x148;
  out5[1] = x149;
  out5[2] = x150;
  out5[3] = x151;
  out5[4] = x152;
}
