/* Autogenerated: word_by_word_montgomery fp118 32 0x27939f3c5bd1c182ffffffffffffff */
/* curve description: fp118 */
/* machine_wordsize = 32 (from "32") */
/* requested operations: (all) */
/* m = 0x27939f3c5bd1c182ffffffffffffff (from "0x27939f3c5bd1c182ffffffffffffff") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) in */
/*                            if x1 & (2^128-1) < 2^127 then x1 & (2^128-1) else (x1 & (2^128-1)) - 2^128 */

#include <stdint.h>
typedef unsigned char fiat_fp118_uint1;
typedef signed char fiat_fp118_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_FP118_FIAT_INLINE __inline__
#else
#  define FIAT_FP118_FIAT_INLINE
#endif

/* The type fiat_fp118_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp118_montgomery_domain_field_element[4];

/* The type fiat_fp118_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp118_non_montgomery_domain_field_element[4];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_fp118_addcarryx_u32 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^32
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp118_addcarryx_u32(uint32_t* out1, fiat_fp118_uint1* out2, fiat_fp118_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  uint64_t x1;
  uint32_t x2;
  fiat_fp118_uint1 x3;
  x1 = ((arg1 + (uint64_t)arg2) + arg3);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (fiat_fp118_uint1)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp118_subborrowx_u32 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^32
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp118_subborrowx_u32(uint32_t* out1, fiat_fp118_uint1* out2, fiat_fp118_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  int64_t x1;
  fiat_fp118_int1 x2;
  uint32_t x3;
  x1 = ((arg2 - (int64_t)arg1) - arg3);
  x2 = (fiat_fp118_int1)(x1 >> 32);
  x3 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  *out1 = x3;
  *out2 = (fiat_fp118_uint1)(0x0 - x2);
}

/*
 * The function fiat_fp118_mulx_u32 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^32
 *   out2 = ⌊arg1 * arg2 / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0xffffffff]
 */
void fiat_fp118_mulx_u32(uint32_t* out1, uint32_t* out2, uint32_t arg1, uint32_t arg2) {
  uint64_t x1;
  uint32_t x2;
  uint32_t x3;
  x1 = ((uint64_t)arg1 * arg2);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (uint32_t)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp118_cmovznz_u32 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp118_cmovznz_u32(uint32_t* out1, fiat_fp118_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  fiat_fp118_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_fp118_int1)(0x0 - x1) & UINT32_C(0xffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_fp118_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_mul(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1, const fiat_fp118_montgomery_domain_field_element arg2) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  fiat_fp118_uint1 x14;
  uint32_t x15;
  fiat_fp118_uint1 x16;
  uint32_t x17;
  fiat_fp118_uint1 x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  fiat_fp118_uint1 x29;
  uint32_t x30;
  fiat_fp118_uint1 x31;
  uint32_t x32;
  fiat_fp118_uint1 x33;
  uint32_t x34;
  uint32_t x35;
  fiat_fp118_uint1 x36;
  uint32_t x37;
  fiat_fp118_uint1 x38;
  uint32_t x39;
  fiat_fp118_uint1 x40;
  uint32_t x41;
  fiat_fp118_uint1 x42;
  uint32_t x43;
  fiat_fp118_uint1 x44;
  uint32_t x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  uint32_t x53;
  fiat_fp118_uint1 x54;
  uint32_t x55;
  fiat_fp118_uint1 x56;
  uint32_t x57;
  fiat_fp118_uint1 x58;
  uint32_t x59;
  uint32_t x60;
  fiat_fp118_uint1 x61;
  uint32_t x62;
  fiat_fp118_uint1 x63;
  uint32_t x64;
  fiat_fp118_uint1 x65;
  uint32_t x66;
  fiat_fp118_uint1 x67;
  uint32_t x68;
  fiat_fp118_uint1 x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  fiat_fp118_uint1 x79;
  uint32_t x80;
  fiat_fp118_uint1 x81;
  uint32_t x82;
  fiat_fp118_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  fiat_fp118_uint1 x86;
  uint32_t x87;
  fiat_fp118_uint1 x88;
  uint32_t x89;
  fiat_fp118_uint1 x90;
  uint32_t x91;
  fiat_fp118_uint1 x92;
  uint32_t x93;
  fiat_fp118_uint1 x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  uint32_t x99;
  uint32_t x100;
  uint32_t x101;
  uint32_t x102;
  uint32_t x103;
  uint32_t x104;
  fiat_fp118_uint1 x105;
  uint32_t x106;
  fiat_fp118_uint1 x107;
  uint32_t x108;
  fiat_fp118_uint1 x109;
  uint32_t x110;
  uint32_t x111;
  fiat_fp118_uint1 x112;
  uint32_t x113;
  fiat_fp118_uint1 x114;
  uint32_t x115;
  fiat_fp118_uint1 x116;
  uint32_t x117;
  fiat_fp118_uint1 x118;
  uint32_t x119;
  fiat_fp118_uint1 x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  uint32_t x127;
  uint32_t x128;
  uint32_t x129;
  fiat_fp118_uint1 x130;
  uint32_t x131;
  fiat_fp118_uint1 x132;
  uint32_t x133;
  fiat_fp118_uint1 x134;
  uint32_t x135;
  uint32_t x136;
  fiat_fp118_uint1 x137;
  uint32_t x138;
  fiat_fp118_uint1 x139;
  uint32_t x140;
  fiat_fp118_uint1 x141;
  uint32_t x142;
  fiat_fp118_uint1 x143;
  uint32_t x144;
  fiat_fp118_uint1 x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  fiat_fp118_uint1 x156;
  uint32_t x157;
  fiat_fp118_uint1 x158;
  uint32_t x159;
  fiat_fp118_uint1 x160;
  uint32_t x161;
  uint32_t x162;
  fiat_fp118_uint1 x163;
  uint32_t x164;
  fiat_fp118_uint1 x165;
  uint32_t x166;
  fiat_fp118_uint1 x167;
  uint32_t x168;
  fiat_fp118_uint1 x169;
  uint32_t x170;
  fiat_fp118_uint1 x171;
  uint32_t x172;
  uint32_t x173;
  uint32_t x174;
  uint32_t x175;
  uint32_t x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  fiat_fp118_uint1 x181;
  uint32_t x182;
  fiat_fp118_uint1 x183;
  uint32_t x184;
  fiat_fp118_uint1 x185;
  uint32_t x186;
  uint32_t x187;
  fiat_fp118_uint1 x188;
  uint32_t x189;
  fiat_fp118_uint1 x190;
  uint32_t x191;
  fiat_fp118_uint1 x192;
  uint32_t x193;
  fiat_fp118_uint1 x194;
  uint32_t x195;
  fiat_fp118_uint1 x196;
  uint32_t x197;
  uint32_t x198;
  fiat_fp118_uint1 x199;
  uint32_t x200;
  fiat_fp118_uint1 x201;
  uint32_t x202;
  fiat_fp118_uint1 x203;
  uint32_t x204;
  fiat_fp118_uint1 x205;
  uint32_t x206;
  fiat_fp118_uint1 x207;
  uint32_t x208;
  uint32_t x209;
  uint32_t x210;
  uint32_t x211;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[0]);
  fiat_fp118_mulx_u32(&x5, &x6, x4, (arg2[3]));
  fiat_fp118_mulx_u32(&x7, &x8, x4, (arg2[2]));
  fiat_fp118_mulx_u32(&x9, &x10, x4, (arg2[1]));
  fiat_fp118_mulx_u32(&x11, &x12, x4, (arg2[0]));
  fiat_fp118_addcarryx_u32(&x13, &x14, 0x0, x12, x9);
  fiat_fp118_addcarryx_u32(&x15, &x16, x14, x10, x7);
  fiat_fp118_addcarryx_u32(&x17, &x18, x16, x8, x5);
  x19 = (x18 + x6);
  fiat_fp118_mulx_u32(&x20, &x21, x11, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x22, &x23, x11, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x24, &x25, x11, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x26, &x27, x11, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x28, &x29, 0x0, x27, x24);
  fiat_fp118_addcarryx_u32(&x30, &x31, x29, x25, x22);
  fiat_fp118_addcarryx_u32(&x32, &x33, x31, x23, x20);
  x34 = (x33 + x21);
  fiat_fp118_addcarryx_u32(&x35, &x36, 0x0, x11, x26);
  fiat_fp118_addcarryx_u32(&x37, &x38, x36, x13, x28);
  fiat_fp118_addcarryx_u32(&x39, &x40, x38, x15, x30);
  fiat_fp118_addcarryx_u32(&x41, &x42, x40, x17, x32);
  fiat_fp118_addcarryx_u32(&x43, &x44, x42, x19, x34);
  fiat_fp118_mulx_u32(&x45, &x46, x1, (arg2[3]));
  fiat_fp118_mulx_u32(&x47, &x48, x1, (arg2[2]));
  fiat_fp118_mulx_u32(&x49, &x50, x1, (arg2[1]));
  fiat_fp118_mulx_u32(&x51, &x52, x1, (arg2[0]));
  fiat_fp118_addcarryx_u32(&x53, &x54, 0x0, x52, x49);
  fiat_fp118_addcarryx_u32(&x55, &x56, x54, x50, x47);
  fiat_fp118_addcarryx_u32(&x57, &x58, x56, x48, x45);
  x59 = (x58 + x46);
  fiat_fp118_addcarryx_u32(&x60, &x61, 0x0, x37, x51);
  fiat_fp118_addcarryx_u32(&x62, &x63, x61, x39, x53);
  fiat_fp118_addcarryx_u32(&x64, &x65, x63, x41, x55);
  fiat_fp118_addcarryx_u32(&x66, &x67, x65, x43, x57);
  fiat_fp118_addcarryx_u32(&x68, &x69, x67, x44, x59);
  fiat_fp118_mulx_u32(&x70, &x71, x60, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x72, &x73, x60, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x74, &x75, x60, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x76, &x77, x60, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x78, &x79, 0x0, x77, x74);
  fiat_fp118_addcarryx_u32(&x80, &x81, x79, x75, x72);
  fiat_fp118_addcarryx_u32(&x82, &x83, x81, x73, x70);
  x84 = (x83 + x71);
  fiat_fp118_addcarryx_u32(&x85, &x86, 0x0, x60, x76);
  fiat_fp118_addcarryx_u32(&x87, &x88, x86, x62, x78);
  fiat_fp118_addcarryx_u32(&x89, &x90, x88, x64, x80);
  fiat_fp118_addcarryx_u32(&x91, &x92, x90, x66, x82);
  fiat_fp118_addcarryx_u32(&x93, &x94, x92, x68, x84);
  x95 = ((uint32_t)x94 + x69);
  fiat_fp118_mulx_u32(&x96, &x97, x2, (arg2[3]));
  fiat_fp118_mulx_u32(&x98, &x99, x2, (arg2[2]));
  fiat_fp118_mulx_u32(&x100, &x101, x2, (arg2[1]));
  fiat_fp118_mulx_u32(&x102, &x103, x2, (arg2[0]));
  fiat_fp118_addcarryx_u32(&x104, &x105, 0x0, x103, x100);
  fiat_fp118_addcarryx_u32(&x106, &x107, x105, x101, x98);
  fiat_fp118_addcarryx_u32(&x108, &x109, x107, x99, x96);
  x110 = (x109 + x97);
  fiat_fp118_addcarryx_u32(&x111, &x112, 0x0, x87, x102);
  fiat_fp118_addcarryx_u32(&x113, &x114, x112, x89, x104);
  fiat_fp118_addcarryx_u32(&x115, &x116, x114, x91, x106);
  fiat_fp118_addcarryx_u32(&x117, &x118, x116, x93, x108);
  fiat_fp118_addcarryx_u32(&x119, &x120, x118, x95, x110);
  fiat_fp118_mulx_u32(&x121, &x122, x111, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x123, &x124, x111, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x125, &x126, x111, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x127, &x128, x111, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x129, &x130, 0x0, x128, x125);
  fiat_fp118_addcarryx_u32(&x131, &x132, x130, x126, x123);
  fiat_fp118_addcarryx_u32(&x133, &x134, x132, x124, x121);
  x135 = (x134 + x122);
  fiat_fp118_addcarryx_u32(&x136, &x137, 0x0, x111, x127);
  fiat_fp118_addcarryx_u32(&x138, &x139, x137, x113, x129);
  fiat_fp118_addcarryx_u32(&x140, &x141, x139, x115, x131);
  fiat_fp118_addcarryx_u32(&x142, &x143, x141, x117, x133);
  fiat_fp118_addcarryx_u32(&x144, &x145, x143, x119, x135);
  x146 = ((uint32_t)x145 + x120);
  fiat_fp118_mulx_u32(&x147, &x148, x3, (arg2[3]));
  fiat_fp118_mulx_u32(&x149, &x150, x3, (arg2[2]));
  fiat_fp118_mulx_u32(&x151, &x152, x3, (arg2[1]));
  fiat_fp118_mulx_u32(&x153, &x154, x3, (arg2[0]));
  fiat_fp118_addcarryx_u32(&x155, &x156, 0x0, x154, x151);
  fiat_fp118_addcarryx_u32(&x157, &x158, x156, x152, x149);
  fiat_fp118_addcarryx_u32(&x159, &x160, x158, x150, x147);
  x161 = (x160 + x148);
  fiat_fp118_addcarryx_u32(&x162, &x163, 0x0, x138, x153);
  fiat_fp118_addcarryx_u32(&x164, &x165, x163, x140, x155);
  fiat_fp118_addcarryx_u32(&x166, &x167, x165, x142, x157);
  fiat_fp118_addcarryx_u32(&x168, &x169, x167, x144, x159);
  fiat_fp118_addcarryx_u32(&x170, &x171, x169, x146, x161);
  fiat_fp118_mulx_u32(&x172, &x173, x162, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x174, &x175, x162, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x176, &x177, x162, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x178, &x179, x162, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x180, &x181, 0x0, x179, x176);
  fiat_fp118_addcarryx_u32(&x182, &x183, x181, x177, x174);
  fiat_fp118_addcarryx_u32(&x184, &x185, x183, x175, x172);
  x186 = (x185 + x173);
  fiat_fp118_addcarryx_u32(&x187, &x188, 0x0, x162, x178);
  fiat_fp118_addcarryx_u32(&x189, &x190, x188, x164, x180);
  fiat_fp118_addcarryx_u32(&x191, &x192, x190, x166, x182);
  fiat_fp118_addcarryx_u32(&x193, &x194, x192, x168, x184);
  fiat_fp118_addcarryx_u32(&x195, &x196, x194, x170, x186);
  x197 = ((uint32_t)x196 + x171);
  fiat_fp118_subborrowx_u32(&x198, &x199, 0x0, x189, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x200, &x201, x199, x191, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x202, &x203, x201, x193, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x204, &x205, x203, x195, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x206, &x207, x205, x197, 0x0);
  fiat_fp118_cmovznz_u32(&x208, x207, x198, x189);
  fiat_fp118_cmovznz_u32(&x209, x207, x200, x191);
  fiat_fp118_cmovznz_u32(&x210, x207, x202, x193);
  fiat_fp118_cmovznz_u32(&x211, x207, x204, x195);
  out1[0] = x208;
  out1[1] = x209;
  out1[2] = x210;
  out1[3] = x211;
}

/*
 * The function fiat_fp118_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_square(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  fiat_fp118_uint1 x14;
  uint32_t x15;
  fiat_fp118_uint1 x16;
  uint32_t x17;
  fiat_fp118_uint1 x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  fiat_fp118_uint1 x29;
  uint32_t x30;
  fiat_fp118_uint1 x31;
  uint32_t x32;
  fiat_fp118_uint1 x33;
  uint32_t x34;
  uint32_t x35;
  fiat_fp118_uint1 x36;
  uint32_t x37;
  fiat_fp118_uint1 x38;
  uint32_t x39;
  fiat_fp118_uint1 x40;
  uint32_t x41;
  fiat_fp118_uint1 x42;
  uint32_t x43;
  fiat_fp118_uint1 x44;
  uint32_t x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  uint32_t x53;
  fiat_fp118_uint1 x54;
  uint32_t x55;
  fiat_fp118_uint1 x56;
  uint32_t x57;
  fiat_fp118_uint1 x58;
  uint32_t x59;
  uint32_t x60;
  fiat_fp118_uint1 x61;
  uint32_t x62;
  fiat_fp118_uint1 x63;
  uint32_t x64;
  fiat_fp118_uint1 x65;
  uint32_t x66;
  fiat_fp118_uint1 x67;
  uint32_t x68;
  fiat_fp118_uint1 x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  fiat_fp118_uint1 x79;
  uint32_t x80;
  fiat_fp118_uint1 x81;
  uint32_t x82;
  fiat_fp118_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  fiat_fp118_uint1 x86;
  uint32_t x87;
  fiat_fp118_uint1 x88;
  uint32_t x89;
  fiat_fp118_uint1 x90;
  uint32_t x91;
  fiat_fp118_uint1 x92;
  uint32_t x93;
  fiat_fp118_uint1 x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  uint32_t x99;
  uint32_t x100;
  uint32_t x101;
  uint32_t x102;
  uint32_t x103;
  uint32_t x104;
  fiat_fp118_uint1 x105;
  uint32_t x106;
  fiat_fp118_uint1 x107;
  uint32_t x108;
  fiat_fp118_uint1 x109;
  uint32_t x110;
  uint32_t x111;
  fiat_fp118_uint1 x112;
  uint32_t x113;
  fiat_fp118_uint1 x114;
  uint32_t x115;
  fiat_fp118_uint1 x116;
  uint32_t x117;
  fiat_fp118_uint1 x118;
  uint32_t x119;
  fiat_fp118_uint1 x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  uint32_t x127;
  uint32_t x128;
  uint32_t x129;
  fiat_fp118_uint1 x130;
  uint32_t x131;
  fiat_fp118_uint1 x132;
  uint32_t x133;
  fiat_fp118_uint1 x134;
  uint32_t x135;
  uint32_t x136;
  fiat_fp118_uint1 x137;
  uint32_t x138;
  fiat_fp118_uint1 x139;
  uint32_t x140;
  fiat_fp118_uint1 x141;
  uint32_t x142;
  fiat_fp118_uint1 x143;
  uint32_t x144;
  fiat_fp118_uint1 x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  fiat_fp118_uint1 x156;
  uint32_t x157;
  fiat_fp118_uint1 x158;
  uint32_t x159;
  fiat_fp118_uint1 x160;
  uint32_t x161;
  uint32_t x162;
  fiat_fp118_uint1 x163;
  uint32_t x164;
  fiat_fp118_uint1 x165;
  uint32_t x166;
  fiat_fp118_uint1 x167;
  uint32_t x168;
  fiat_fp118_uint1 x169;
  uint32_t x170;
  fiat_fp118_uint1 x171;
  uint32_t x172;
  uint32_t x173;
  uint32_t x174;
  uint32_t x175;
  uint32_t x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  fiat_fp118_uint1 x181;
  uint32_t x182;
  fiat_fp118_uint1 x183;
  uint32_t x184;
  fiat_fp118_uint1 x185;
  uint32_t x186;
  uint32_t x187;
  fiat_fp118_uint1 x188;
  uint32_t x189;
  fiat_fp118_uint1 x190;
  uint32_t x191;
  fiat_fp118_uint1 x192;
  uint32_t x193;
  fiat_fp118_uint1 x194;
  uint32_t x195;
  fiat_fp118_uint1 x196;
  uint32_t x197;
  uint32_t x198;
  fiat_fp118_uint1 x199;
  uint32_t x200;
  fiat_fp118_uint1 x201;
  uint32_t x202;
  fiat_fp118_uint1 x203;
  uint32_t x204;
  fiat_fp118_uint1 x205;
  uint32_t x206;
  fiat_fp118_uint1 x207;
  uint32_t x208;
  uint32_t x209;
  uint32_t x210;
  uint32_t x211;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[0]);
  fiat_fp118_mulx_u32(&x5, &x6, x4, (arg1[3]));
  fiat_fp118_mulx_u32(&x7, &x8, x4, (arg1[2]));
  fiat_fp118_mulx_u32(&x9, &x10, x4, (arg1[1]));
  fiat_fp118_mulx_u32(&x11, &x12, x4, (arg1[0]));
  fiat_fp118_addcarryx_u32(&x13, &x14, 0x0, x12, x9);
  fiat_fp118_addcarryx_u32(&x15, &x16, x14, x10, x7);
  fiat_fp118_addcarryx_u32(&x17, &x18, x16, x8, x5);
  x19 = (x18 + x6);
  fiat_fp118_mulx_u32(&x20, &x21, x11, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x22, &x23, x11, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x24, &x25, x11, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x26, &x27, x11, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x28, &x29, 0x0, x27, x24);
  fiat_fp118_addcarryx_u32(&x30, &x31, x29, x25, x22);
  fiat_fp118_addcarryx_u32(&x32, &x33, x31, x23, x20);
  x34 = (x33 + x21);
  fiat_fp118_addcarryx_u32(&x35, &x36, 0x0, x11, x26);
  fiat_fp118_addcarryx_u32(&x37, &x38, x36, x13, x28);
  fiat_fp118_addcarryx_u32(&x39, &x40, x38, x15, x30);
  fiat_fp118_addcarryx_u32(&x41, &x42, x40, x17, x32);
  fiat_fp118_addcarryx_u32(&x43, &x44, x42, x19, x34);
  fiat_fp118_mulx_u32(&x45, &x46, x1, (arg1[3]));
  fiat_fp118_mulx_u32(&x47, &x48, x1, (arg1[2]));
  fiat_fp118_mulx_u32(&x49, &x50, x1, (arg1[1]));
  fiat_fp118_mulx_u32(&x51, &x52, x1, (arg1[0]));
  fiat_fp118_addcarryx_u32(&x53, &x54, 0x0, x52, x49);
  fiat_fp118_addcarryx_u32(&x55, &x56, x54, x50, x47);
  fiat_fp118_addcarryx_u32(&x57, &x58, x56, x48, x45);
  x59 = (x58 + x46);
  fiat_fp118_addcarryx_u32(&x60, &x61, 0x0, x37, x51);
  fiat_fp118_addcarryx_u32(&x62, &x63, x61, x39, x53);
  fiat_fp118_addcarryx_u32(&x64, &x65, x63, x41, x55);
  fiat_fp118_addcarryx_u32(&x66, &x67, x65, x43, x57);
  fiat_fp118_addcarryx_u32(&x68, &x69, x67, x44, x59);
  fiat_fp118_mulx_u32(&x70, &x71, x60, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x72, &x73, x60, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x74, &x75, x60, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x76, &x77, x60, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x78, &x79, 0x0, x77, x74);
  fiat_fp118_addcarryx_u32(&x80, &x81, x79, x75, x72);
  fiat_fp118_addcarryx_u32(&x82, &x83, x81, x73, x70);
  x84 = (x83 + x71);
  fiat_fp118_addcarryx_u32(&x85, &x86, 0x0, x60, x76);
  fiat_fp118_addcarryx_u32(&x87, &x88, x86, x62, x78);
  fiat_fp118_addcarryx_u32(&x89, &x90, x88, x64, x80);
  fiat_fp118_addcarryx_u32(&x91, &x92, x90, x66, x82);
  fiat_fp118_addcarryx_u32(&x93, &x94, x92, x68, x84);
  x95 = ((uint32_t)x94 + x69);
  fiat_fp118_mulx_u32(&x96, &x97, x2, (arg1[3]));
  fiat_fp118_mulx_u32(&x98, &x99, x2, (arg1[2]));
  fiat_fp118_mulx_u32(&x100, &x101, x2, (arg1[1]));
  fiat_fp118_mulx_u32(&x102, &x103, x2, (arg1[0]));
  fiat_fp118_addcarryx_u32(&x104, &x105, 0x0, x103, x100);
  fiat_fp118_addcarryx_u32(&x106, &x107, x105, x101, x98);
  fiat_fp118_addcarryx_u32(&x108, &x109, x107, x99, x96);
  x110 = (x109 + x97);
  fiat_fp118_addcarryx_u32(&x111, &x112, 0x0, x87, x102);
  fiat_fp118_addcarryx_u32(&x113, &x114, x112, x89, x104);
  fiat_fp118_addcarryx_u32(&x115, &x116, x114, x91, x106);
  fiat_fp118_addcarryx_u32(&x117, &x118, x116, x93, x108);
  fiat_fp118_addcarryx_u32(&x119, &x120, x118, x95, x110);
  fiat_fp118_mulx_u32(&x121, &x122, x111, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x123, &x124, x111, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x125, &x126, x111, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x127, &x128, x111, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x129, &x130, 0x0, x128, x125);
  fiat_fp118_addcarryx_u32(&x131, &x132, x130, x126, x123);
  fiat_fp118_addcarryx_u32(&x133, &x134, x132, x124, x121);
  x135 = (x134 + x122);
  fiat_fp118_addcarryx_u32(&x136, &x137, 0x0, x111, x127);
  fiat_fp118_addcarryx_u32(&x138, &x139, x137, x113, x129);
  fiat_fp118_addcarryx_u32(&x140, &x141, x139, x115, x131);
  fiat_fp118_addcarryx_u32(&x142, &x143, x141, x117, x133);
  fiat_fp118_addcarryx_u32(&x144, &x145, x143, x119, x135);
  x146 = ((uint32_t)x145 + x120);
  fiat_fp118_mulx_u32(&x147, &x148, x3, (arg1[3]));
  fiat_fp118_mulx_u32(&x149, &x150, x3, (arg1[2]));
  fiat_fp118_mulx_u32(&x151, &x152, x3, (arg1[1]));
  fiat_fp118_mulx_u32(&x153, &x154, x3, (arg1[0]));
  fiat_fp118_addcarryx_u32(&x155, &x156, 0x0, x154, x151);
  fiat_fp118_addcarryx_u32(&x157, &x158, x156, x152, x149);
  fiat_fp118_addcarryx_u32(&x159, &x160, x158, x150, x147);
  x161 = (x160 + x148);
  fiat_fp118_addcarryx_u32(&x162, &x163, 0x0, x138, x153);
  fiat_fp118_addcarryx_u32(&x164, &x165, x163, x140, x155);
  fiat_fp118_addcarryx_u32(&x166, &x167, x165, x142, x157);
  fiat_fp118_addcarryx_u32(&x168, &x169, x167, x144, x159);
  fiat_fp118_addcarryx_u32(&x170, &x171, x169, x146, x161);
  fiat_fp118_mulx_u32(&x172, &x173, x162, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x174, &x175, x162, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x176, &x177, x162, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x178, &x179, x162, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x180, &x181, 0x0, x179, x176);
  fiat_fp118_addcarryx_u32(&x182, &x183, x181, x177, x174);
  fiat_fp118_addcarryx_u32(&x184, &x185, x183, x175, x172);
  x186 = (x185 + x173);
  fiat_fp118_addcarryx_u32(&x187, &x188, 0x0, x162, x178);
  fiat_fp118_addcarryx_u32(&x189, &x190, x188, x164, x180);
  fiat_fp118_addcarryx_u32(&x191, &x192, x190, x166, x182);
  fiat_fp118_addcarryx_u32(&x193, &x194, x192, x168, x184);
  fiat_fp118_addcarryx_u32(&x195, &x196, x194, x170, x186);
  x197 = ((uint32_t)x196 + x171);
  fiat_fp118_subborrowx_u32(&x198, &x199, 0x0, x189, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x200, &x201, x199, x191, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x202, &x203, x201, x193, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x204, &x205, x203, x195, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x206, &x207, x205, x197, 0x0);
  fiat_fp118_cmovznz_u32(&x208, x207, x198, x189);
  fiat_fp118_cmovznz_u32(&x209, x207, x200, x191);
  fiat_fp118_cmovznz_u32(&x210, x207, x202, x193);
  fiat_fp118_cmovznz_u32(&x211, x207, x204, x195);
  out1[0] = x208;
  out1[1] = x209;
  out1[2] = x210;
  out1[3] = x211;
}

/*
 * The function fiat_fp118_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_add(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1, const fiat_fp118_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp118_uint1 x2;
  uint32_t x3;
  fiat_fp118_uint1 x4;
  uint32_t x5;
  fiat_fp118_uint1 x6;
  uint32_t x7;
  fiat_fp118_uint1 x8;
  uint32_t x9;
  fiat_fp118_uint1 x10;
  uint32_t x11;
  fiat_fp118_uint1 x12;
  uint32_t x13;
  fiat_fp118_uint1 x14;
  uint32_t x15;
  fiat_fp118_uint1 x16;
  uint32_t x17;
  fiat_fp118_uint1 x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  fiat_fp118_addcarryx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp118_addcarryx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp118_addcarryx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp118_addcarryx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp118_subborrowx_u32(&x9, &x10, 0x0, x1, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x11, &x12, x10, x3, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x13, &x14, x12, x5, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x15, &x16, x14, x7, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x17, &x18, x16, x8, 0x0);
  fiat_fp118_cmovznz_u32(&x19, x18, x9, x1);
  fiat_fp118_cmovznz_u32(&x20, x18, x11, x3);
  fiat_fp118_cmovznz_u32(&x21, x18, x13, x5);
  fiat_fp118_cmovznz_u32(&x22, x18, x15, x7);
  out1[0] = x19;
  out1[1] = x20;
  out1[2] = x21;
  out1[3] = x22;
}

/*
 * The function fiat_fp118_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_sub(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1, const fiat_fp118_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp118_uint1 x2;
  uint32_t x3;
  fiat_fp118_uint1 x4;
  uint32_t x5;
  fiat_fp118_uint1 x6;
  uint32_t x7;
  fiat_fp118_uint1 x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp118_uint1 x11;
  uint32_t x12;
  fiat_fp118_uint1 x13;
  uint32_t x14;
  fiat_fp118_uint1 x15;
  uint32_t x16;
  fiat_fp118_uint1 x17;
  fiat_fp118_subborrowx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp118_subborrowx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp118_subborrowx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp118_subborrowx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp118_cmovznz_u32(&x9, x8, 0x0, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x10, &x11, 0x0, x1, x9);
  fiat_fp118_addcarryx_u32(&x12, &x13, x11, x3, (x9 & UINT32_C(0x82ffffff)));
  fiat_fp118_addcarryx_u32(&x14, &x15, x13, x5, (x9 & UINT32_C(0x3c5bd1c1)));
  fiat_fp118_addcarryx_u32(&x16, &x17, x15, x7, (x9 & UINT32_C(0x27939f)));
  out1[0] = x10;
  out1[1] = x12;
  out1[2] = x14;
  out1[3] = x16;
}

/*
 * The function fiat_fp118_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_opp(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1) {
  uint32_t x1;
  fiat_fp118_uint1 x2;
  uint32_t x3;
  fiat_fp118_uint1 x4;
  uint32_t x5;
  fiat_fp118_uint1 x6;
  uint32_t x7;
  fiat_fp118_uint1 x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp118_uint1 x11;
  uint32_t x12;
  fiat_fp118_uint1 x13;
  uint32_t x14;
  fiat_fp118_uint1 x15;
  uint32_t x16;
  fiat_fp118_uint1 x17;
  fiat_fp118_subborrowx_u32(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_fp118_subborrowx_u32(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_fp118_subborrowx_u32(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_fp118_subborrowx_u32(&x7, &x8, x6, 0x0, (arg1[3]));
  fiat_fp118_cmovznz_u32(&x9, x8, 0x0, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x10, &x11, 0x0, x1, x9);
  fiat_fp118_addcarryx_u32(&x12, &x13, x11, x3, (x9 & UINT32_C(0x82ffffff)));
  fiat_fp118_addcarryx_u32(&x14, &x15, x13, x5, (x9 & UINT32_C(0x3c5bd1c1)));
  fiat_fp118_addcarryx_u32(&x16, &x17, x15, x7, (x9 & UINT32_C(0x27939f)));
  out1[0] = x10;
  out1[1] = x12;
  out1[2] = x14;
  out1[3] = x16;
}

/*
 * The function fiat_fp118_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^32)⁻¹ mod m)^4) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_from_montgomery(fiat_fp118_non_montgomery_domain_field_element out1, const fiat_fp118_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp118_uint1 x11;
  uint32_t x12;
  fiat_fp118_uint1 x13;
  uint32_t x14;
  fiat_fp118_uint1 x15;
  uint32_t x16;
  fiat_fp118_uint1 x17;
  uint32_t x18;
  fiat_fp118_uint1 x19;
  uint32_t x20;
  fiat_fp118_uint1 x21;
  uint32_t x22;
  fiat_fp118_uint1 x23;
  uint32_t x24;
  fiat_fp118_uint1 x25;
  uint32_t x26;
  fiat_fp118_uint1 x27;
  uint32_t x28;
  fiat_fp118_uint1 x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  uint32_t x37;
  uint32_t x38;
  fiat_fp118_uint1 x39;
  uint32_t x40;
  fiat_fp118_uint1 x41;
  uint32_t x42;
  fiat_fp118_uint1 x43;
  uint32_t x44;
  fiat_fp118_uint1 x45;
  uint32_t x46;
  fiat_fp118_uint1 x47;
  uint32_t x48;
  fiat_fp118_uint1 x49;
  uint32_t x50;
  fiat_fp118_uint1 x51;
  uint32_t x52;
  fiat_fp118_uint1 x53;
  uint32_t x54;
  fiat_fp118_uint1 x55;
  uint32_t x56;
  fiat_fp118_uint1 x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  uint32_t x64;
  uint32_t x65;
  uint32_t x66;
  fiat_fp118_uint1 x67;
  uint32_t x68;
  fiat_fp118_uint1 x69;
  uint32_t x70;
  fiat_fp118_uint1 x71;
  uint32_t x72;
  fiat_fp118_uint1 x73;
  uint32_t x74;
  fiat_fp118_uint1 x75;
  uint32_t x76;
  fiat_fp118_uint1 x77;
  uint32_t x78;
  fiat_fp118_uint1 x79;
  uint32_t x80;
  fiat_fp118_uint1 x81;
  uint32_t x82;
  fiat_fp118_uint1 x83;
  uint32_t x84;
  fiat_fp118_uint1 x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  fiat_fp118_uint1 x95;
  uint32_t x96;
  fiat_fp118_uint1 x97;
  uint32_t x98;
  fiat_fp118_uint1 x99;
  uint32_t x100;
  fiat_fp118_uint1 x101;
  uint32_t x102;
  fiat_fp118_uint1 x103;
  uint32_t x104;
  fiat_fp118_uint1 x105;
  uint32_t x106;
  fiat_fp118_uint1 x107;
  uint32_t x108;
  uint32_t x109;
  fiat_fp118_uint1 x110;
  uint32_t x111;
  fiat_fp118_uint1 x112;
  uint32_t x113;
  fiat_fp118_uint1 x114;
  uint32_t x115;
  fiat_fp118_uint1 x116;
  uint32_t x117;
  fiat_fp118_uint1 x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  x1 = (arg1[0]);
  fiat_fp118_mulx_u32(&x2, &x3, x1, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x4, &x5, x1, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x6, &x7, x1, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x8, &x9, x1, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x10, &x11, 0x0, x9, x6);
  fiat_fp118_addcarryx_u32(&x12, &x13, x11, x7, x4);
  fiat_fp118_addcarryx_u32(&x14, &x15, x13, x5, x2);
  fiat_fp118_addcarryx_u32(&x16, &x17, 0x0, x1, x8);
  fiat_fp118_addcarryx_u32(&x18, &x19, x17, 0x0, x10);
  fiat_fp118_addcarryx_u32(&x20, &x21, x19, 0x0, x12);
  fiat_fp118_addcarryx_u32(&x22, &x23, x21, 0x0, x14);
  fiat_fp118_addcarryx_u32(&x24, &x25, 0x0, x18, (arg1[1]));
  fiat_fp118_addcarryx_u32(&x26, &x27, x25, x20, 0x0);
  fiat_fp118_addcarryx_u32(&x28, &x29, x27, x22, 0x0);
  fiat_fp118_mulx_u32(&x30, &x31, x24, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x32, &x33, x24, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x34, &x35, x24, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x36, &x37, x24, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x38, &x39, 0x0, x37, x34);
  fiat_fp118_addcarryx_u32(&x40, &x41, x39, x35, x32);
  fiat_fp118_addcarryx_u32(&x42, &x43, x41, x33, x30);
  fiat_fp118_addcarryx_u32(&x44, &x45, 0x0, x24, x36);
  fiat_fp118_addcarryx_u32(&x46, &x47, x45, x26, x38);
  fiat_fp118_addcarryx_u32(&x48, &x49, x47, x28, x40);
  fiat_fp118_addcarryx_u32(&x50, &x51, x49, (x29 + (x23 + (x15 + x3))), x42);
  fiat_fp118_addcarryx_u32(&x52, &x53, 0x0, x46, (arg1[2]));
  fiat_fp118_addcarryx_u32(&x54, &x55, x53, x48, 0x0);
  fiat_fp118_addcarryx_u32(&x56, &x57, x55, x50, 0x0);
  fiat_fp118_mulx_u32(&x58, &x59, x52, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x60, &x61, x52, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x62, &x63, x52, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x64, &x65, x52, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x66, &x67, 0x0, x65, x62);
  fiat_fp118_addcarryx_u32(&x68, &x69, x67, x63, x60);
  fiat_fp118_addcarryx_u32(&x70, &x71, x69, x61, x58);
  fiat_fp118_addcarryx_u32(&x72, &x73, 0x0, x52, x64);
  fiat_fp118_addcarryx_u32(&x74, &x75, x73, x54, x66);
  fiat_fp118_addcarryx_u32(&x76, &x77, x75, x56, x68);
  fiat_fp118_addcarryx_u32(&x78, &x79, x77, (x57 + (x51 + (x43 + x31))), x70);
  fiat_fp118_addcarryx_u32(&x80, &x81, 0x0, x74, (arg1[3]));
  fiat_fp118_addcarryx_u32(&x82, &x83, x81, x76, 0x0);
  fiat_fp118_addcarryx_u32(&x84, &x85, x83, x78, 0x0);
  fiat_fp118_mulx_u32(&x86, &x87, x80, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x88, &x89, x80, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x90, &x91, x80, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x92, &x93, x80, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x94, &x95, 0x0, x93, x90);
  fiat_fp118_addcarryx_u32(&x96, &x97, x95, x91, x88);
  fiat_fp118_addcarryx_u32(&x98, &x99, x97, x89, x86);
  fiat_fp118_addcarryx_u32(&x100, &x101, 0x0, x80, x92);
  fiat_fp118_addcarryx_u32(&x102, &x103, x101, x82, x94);
  fiat_fp118_addcarryx_u32(&x104, &x105, x103, x84, x96);
  fiat_fp118_addcarryx_u32(&x106, &x107, x105, (x85 + (x79 + (x71 + x59))), x98);
  x108 = (x107 + (x99 + x87));
  fiat_fp118_subborrowx_u32(&x109, &x110, 0x0, x102, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x111, &x112, x110, x104, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x113, &x114, x112, x106, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x115, &x116, x114, x108, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x117, &x118, x116, 0x0, 0x0);
  fiat_fp118_cmovznz_u32(&x119, x118, x109, x102);
  fiat_fp118_cmovznz_u32(&x120, x118, x111, x104);
  fiat_fp118_cmovznz_u32(&x121, x118, x113, x106);
  fiat_fp118_cmovznz_u32(&x122, x118, x115, x108);
  out1[0] = x119;
  out1[1] = x120;
  out1[2] = x121;
  out1[3] = x122;
}

/*
 * The function fiat_fp118_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_to_montgomery(fiat_fp118_montgomery_domain_field_element out1, const fiat_fp118_non_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  fiat_fp118_uint1 x14;
  uint32_t x15;
  fiat_fp118_uint1 x16;
  uint32_t x17;
  fiat_fp118_uint1 x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  fiat_fp118_uint1 x28;
  uint32_t x29;
  fiat_fp118_uint1 x30;
  uint32_t x31;
  fiat_fp118_uint1 x32;
  uint32_t x33;
  fiat_fp118_uint1 x34;
  uint32_t x35;
  fiat_fp118_uint1 x36;
  uint32_t x37;
  fiat_fp118_uint1 x38;
  uint32_t x39;
  fiat_fp118_uint1 x40;
  uint32_t x41;
  uint32_t x42;
  uint32_t x43;
  uint32_t x44;
  uint32_t x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  uint32_t x49;
  fiat_fp118_uint1 x50;
  uint32_t x51;
  fiat_fp118_uint1 x52;
  uint32_t x53;
  fiat_fp118_uint1 x54;
  uint32_t x55;
  fiat_fp118_uint1 x56;
  uint32_t x57;
  fiat_fp118_uint1 x58;
  uint32_t x59;
  fiat_fp118_uint1 x60;
  uint32_t x61;
  fiat_fp118_uint1 x62;
  uint32_t x63;
  uint32_t x64;
  uint32_t x65;
  uint32_t x66;
  uint32_t x67;
  uint32_t x68;
  uint32_t x69;
  uint32_t x70;
  uint32_t x71;
  fiat_fp118_uint1 x72;
  uint32_t x73;
  fiat_fp118_uint1 x74;
  uint32_t x75;
  fiat_fp118_uint1 x76;
  uint32_t x77;
  fiat_fp118_uint1 x78;
  uint32_t x79;
  fiat_fp118_uint1 x80;
  uint32_t x81;
  fiat_fp118_uint1 x82;
  uint32_t x83;
  fiat_fp118_uint1 x84;
  uint32_t x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  fiat_fp118_uint1 x94;
  uint32_t x95;
  fiat_fp118_uint1 x96;
  uint32_t x97;
  fiat_fp118_uint1 x98;
  uint32_t x99;
  fiat_fp118_uint1 x100;
  uint32_t x101;
  fiat_fp118_uint1 x102;
  uint32_t x103;
  fiat_fp118_uint1 x104;
  uint32_t x105;
  fiat_fp118_uint1 x106;
  uint32_t x107;
  uint32_t x108;
  uint32_t x109;
  uint32_t x110;
  uint32_t x111;
  uint32_t x112;
  uint32_t x113;
  uint32_t x114;
  uint32_t x115;
  fiat_fp118_uint1 x116;
  uint32_t x117;
  fiat_fp118_uint1 x118;
  uint32_t x119;
  fiat_fp118_uint1 x120;
  uint32_t x121;
  fiat_fp118_uint1 x122;
  uint32_t x123;
  fiat_fp118_uint1 x124;
  uint32_t x125;
  fiat_fp118_uint1 x126;
  uint32_t x127;
  fiat_fp118_uint1 x128;
  uint32_t x129;
  uint32_t x130;
  uint32_t x131;
  uint32_t x132;
  uint32_t x133;
  uint32_t x134;
  uint32_t x135;
  uint32_t x136;
  uint32_t x137;
  fiat_fp118_uint1 x138;
  uint32_t x139;
  fiat_fp118_uint1 x140;
  uint32_t x141;
  fiat_fp118_uint1 x142;
  uint32_t x143;
  fiat_fp118_uint1 x144;
  uint32_t x145;
  fiat_fp118_uint1 x146;
  uint32_t x147;
  fiat_fp118_uint1 x148;
  uint32_t x149;
  fiat_fp118_uint1 x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  uint32_t x156;
  uint32_t x157;
  uint32_t x158;
  uint32_t x159;
  fiat_fp118_uint1 x160;
  uint32_t x161;
  fiat_fp118_uint1 x162;
  uint32_t x163;
  fiat_fp118_uint1 x164;
  uint32_t x165;
  fiat_fp118_uint1 x166;
  uint32_t x167;
  fiat_fp118_uint1 x168;
  uint32_t x169;
  fiat_fp118_uint1 x170;
  uint32_t x171;
  fiat_fp118_uint1 x172;
  uint32_t x173;
  uint32_t x174;
  fiat_fp118_uint1 x175;
  uint32_t x176;
  fiat_fp118_uint1 x177;
  uint32_t x178;
  fiat_fp118_uint1 x179;
  uint32_t x180;
  fiat_fp118_uint1 x181;
  uint32_t x182;
  fiat_fp118_uint1 x183;
  uint32_t x184;
  uint32_t x185;
  uint32_t x186;
  uint32_t x187;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[0]);
  fiat_fp118_mulx_u32(&x5, &x6, x4, UINT32_C(0x22f40e));
  fiat_fp118_mulx_u32(&x7, &x8, x4, UINT32_C(0xb68ba748));
  fiat_fp118_mulx_u32(&x9, &x10, x4, UINT32_C(0xe8ad679a));
  fiat_fp118_mulx_u32(&x11, &x12, x4, UINT32_C(0xf3b8e9a7));
  fiat_fp118_addcarryx_u32(&x13, &x14, 0x0, x12, x9);
  fiat_fp118_addcarryx_u32(&x15, &x16, x14, x10, x7);
  fiat_fp118_addcarryx_u32(&x17, &x18, x16, x8, x5);
  fiat_fp118_mulx_u32(&x19, &x20, x11, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x21, &x22, x11, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x23, &x24, x11, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x25, &x26, x11, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x27, &x28, 0x0, x26, x23);
  fiat_fp118_addcarryx_u32(&x29, &x30, x28, x24, x21);
  fiat_fp118_addcarryx_u32(&x31, &x32, x30, x22, x19);
  fiat_fp118_addcarryx_u32(&x33, &x34, 0x0, x11, x25);
  fiat_fp118_addcarryx_u32(&x35, &x36, x34, x13, x27);
  fiat_fp118_addcarryx_u32(&x37, &x38, x36, x15, x29);
  fiat_fp118_addcarryx_u32(&x39, &x40, x38, x17, x31);
  fiat_fp118_mulx_u32(&x41, &x42, x1, UINT32_C(0x22f40e));
  fiat_fp118_mulx_u32(&x43, &x44, x1, UINT32_C(0xb68ba748));
  fiat_fp118_mulx_u32(&x45, &x46, x1, UINT32_C(0xe8ad679a));
  fiat_fp118_mulx_u32(&x47, &x48, x1, UINT32_C(0xf3b8e9a7));
  fiat_fp118_addcarryx_u32(&x49, &x50, 0x0, x48, x45);
  fiat_fp118_addcarryx_u32(&x51, &x52, x50, x46, x43);
  fiat_fp118_addcarryx_u32(&x53, &x54, x52, x44, x41);
  fiat_fp118_addcarryx_u32(&x55, &x56, 0x0, x35, x47);
  fiat_fp118_addcarryx_u32(&x57, &x58, x56, x37, x49);
  fiat_fp118_addcarryx_u32(&x59, &x60, x58, x39, x51);
  fiat_fp118_addcarryx_u32(&x61, &x62, x60, ((x40 + (x18 + x6)) + (x32 + x20)), x53);
  fiat_fp118_mulx_u32(&x63, &x64, x55, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x65, &x66, x55, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x67, &x68, x55, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x69, &x70, x55, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x71, &x72, 0x0, x70, x67);
  fiat_fp118_addcarryx_u32(&x73, &x74, x72, x68, x65);
  fiat_fp118_addcarryx_u32(&x75, &x76, x74, x66, x63);
  fiat_fp118_addcarryx_u32(&x77, &x78, 0x0, x55, x69);
  fiat_fp118_addcarryx_u32(&x79, &x80, x78, x57, x71);
  fiat_fp118_addcarryx_u32(&x81, &x82, x80, x59, x73);
  fiat_fp118_addcarryx_u32(&x83, &x84, x82, x61, x75);
  fiat_fp118_mulx_u32(&x85, &x86, x2, UINT32_C(0x22f40e));
  fiat_fp118_mulx_u32(&x87, &x88, x2, UINT32_C(0xb68ba748));
  fiat_fp118_mulx_u32(&x89, &x90, x2, UINT32_C(0xe8ad679a));
  fiat_fp118_mulx_u32(&x91, &x92, x2, UINT32_C(0xf3b8e9a7));
  fiat_fp118_addcarryx_u32(&x93, &x94, 0x0, x92, x89);
  fiat_fp118_addcarryx_u32(&x95, &x96, x94, x90, x87);
  fiat_fp118_addcarryx_u32(&x97, &x98, x96, x88, x85);
  fiat_fp118_addcarryx_u32(&x99, &x100, 0x0, x79, x91);
  fiat_fp118_addcarryx_u32(&x101, &x102, x100, x81, x93);
  fiat_fp118_addcarryx_u32(&x103, &x104, x102, x83, x95);
  fiat_fp118_addcarryx_u32(&x105, &x106, x104, ((x84 + (x62 + (x54 + x42))) + (x76 + x64)), x97);
  fiat_fp118_mulx_u32(&x107, &x108, x99, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x109, &x110, x99, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x111, &x112, x99, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x113, &x114, x99, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x115, &x116, 0x0, x114, x111);
  fiat_fp118_addcarryx_u32(&x117, &x118, x116, x112, x109);
  fiat_fp118_addcarryx_u32(&x119, &x120, x118, x110, x107);
  fiat_fp118_addcarryx_u32(&x121, &x122, 0x0, x99, x113);
  fiat_fp118_addcarryx_u32(&x123, &x124, x122, x101, x115);
  fiat_fp118_addcarryx_u32(&x125, &x126, x124, x103, x117);
  fiat_fp118_addcarryx_u32(&x127, &x128, x126, x105, x119);
  fiat_fp118_mulx_u32(&x129, &x130, x3, UINT32_C(0x22f40e));
  fiat_fp118_mulx_u32(&x131, &x132, x3, UINT32_C(0xb68ba748));
  fiat_fp118_mulx_u32(&x133, &x134, x3, UINT32_C(0xe8ad679a));
  fiat_fp118_mulx_u32(&x135, &x136, x3, UINT32_C(0xf3b8e9a7));
  fiat_fp118_addcarryx_u32(&x137, &x138, 0x0, x136, x133);
  fiat_fp118_addcarryx_u32(&x139, &x140, x138, x134, x131);
  fiat_fp118_addcarryx_u32(&x141, &x142, x140, x132, x129);
  fiat_fp118_addcarryx_u32(&x143, &x144, 0x0, x123, x135);
  fiat_fp118_addcarryx_u32(&x145, &x146, x144, x125, x137);
  fiat_fp118_addcarryx_u32(&x147, &x148, x146, x127, x139);
  fiat_fp118_addcarryx_u32(&x149, &x150, x148, ((x128 + (x106 + (x98 + x86))) + (x120 + x108)), x141);
  fiat_fp118_mulx_u32(&x151, &x152, x143, UINT32_C(0x27939f));
  fiat_fp118_mulx_u32(&x153, &x154, x143, UINT32_C(0x3c5bd1c1));
  fiat_fp118_mulx_u32(&x155, &x156, x143, UINT32_C(0x82ffffff));
  fiat_fp118_mulx_u32(&x157, &x158, x143, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x159, &x160, 0x0, x158, x155);
  fiat_fp118_addcarryx_u32(&x161, &x162, x160, x156, x153);
  fiat_fp118_addcarryx_u32(&x163, &x164, x162, x154, x151);
  fiat_fp118_addcarryx_u32(&x165, &x166, 0x0, x143, x157);
  fiat_fp118_addcarryx_u32(&x167, &x168, x166, x145, x159);
  fiat_fp118_addcarryx_u32(&x169, &x170, x168, x147, x161);
  fiat_fp118_addcarryx_u32(&x171, &x172, x170, x149, x163);
  x173 = ((x172 + (x150 + (x142 + x130))) + (x164 + x152));
  fiat_fp118_subborrowx_u32(&x174, &x175, 0x0, x167, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x176, &x177, x175, x169, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x178, &x179, x177, x171, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x180, &x181, x179, x173, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x182, &x183, x181, 0x0, 0x0);
  fiat_fp118_cmovznz_u32(&x184, x183, x174, x167);
  fiat_fp118_cmovznz_u32(&x185, x183, x176, x169);
  fiat_fp118_cmovznz_u32(&x186, x183, x178, x171);
  fiat_fp118_cmovznz_u32(&x187, x183, x180, x173);
  out1[0] = x184;
  out1[1] = x185;
  out1[2] = x186;
  out1[3] = x187;
}

/*
 * The function fiat_fp118_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp118_nonzero(uint32_t* out1, const uint32_t arg1[4]) {
  uint32_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | ((arg1[2]) | (arg1[3]))));
  *out1 = x1;
}

/*
 * The function fiat_fp118_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp118_selectznz(uint32_t out1[4], fiat_fp118_uint1 arg1, const uint32_t arg2[4], const uint32_t arg3[4]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  fiat_fp118_cmovznz_u32(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_fp118_cmovznz_u32(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_fp118_cmovznz_u32(&x3, arg1, (arg2[2]), (arg3[2]));
  fiat_fp118_cmovznz_u32(&x4, arg1, (arg2[3]), (arg3[3]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
}

/*
 * The function fiat_fp118_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..14]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x3fffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x3f]]
 */
void fiat_fp118_to_bytes(uint8_t out1[15], const uint32_t arg1[4]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint8_t x5;
  uint32_t x6;
  uint8_t x7;
  uint32_t x8;
  uint8_t x9;
  uint8_t x10;
  uint8_t x11;
  uint32_t x12;
  uint8_t x13;
  uint32_t x14;
  uint8_t x15;
  uint8_t x16;
  uint8_t x17;
  uint32_t x18;
  uint8_t x19;
  uint32_t x20;
  uint8_t x21;
  uint8_t x22;
  uint8_t x23;
  uint32_t x24;
  uint8_t x25;
  uint8_t x26;
  x1 = (arg1[3]);
  x2 = (arg1[2]);
  x3 = (arg1[1]);
  x4 = (arg1[0]);
  x5 = (uint8_t)(x4 & UINT8_C(0xff));
  x6 = (x4 >> 8);
  x7 = (uint8_t)(x6 & UINT8_C(0xff));
  x8 = (x6 >> 8);
  x9 = (uint8_t)(x8 & UINT8_C(0xff));
  x10 = (uint8_t)(x8 >> 8);
  x11 = (uint8_t)(x3 & UINT8_C(0xff));
  x12 = (x3 >> 8);
  x13 = (uint8_t)(x12 & UINT8_C(0xff));
  x14 = (x12 >> 8);
  x15 = (uint8_t)(x14 & UINT8_C(0xff));
  x16 = (uint8_t)(x14 >> 8);
  x17 = (uint8_t)(x2 & UINT8_C(0xff));
  x18 = (x2 >> 8);
  x19 = (uint8_t)(x18 & UINT8_C(0xff));
  x20 = (x18 >> 8);
  x21 = (uint8_t)(x20 & UINT8_C(0xff));
  x22 = (uint8_t)(x20 >> 8);
  x23 = (uint8_t)(x1 & UINT8_C(0xff));
  x24 = (x1 >> 8);
  x25 = (uint8_t)(x24 & UINT8_C(0xff));
  x26 = (uint8_t)(x24 >> 8);
  out1[0] = x5;
  out1[1] = x7;
  out1[2] = x9;
  out1[3] = x10;
  out1[4] = x11;
  out1[5] = x13;
  out1[6] = x15;
  out1[7] = x16;
  out1[8] = x17;
  out1[9] = x19;
  out1[10] = x21;
  out1[11] = x22;
  out1[12] = x23;
  out1[13] = x25;
  out1[14] = x26;
}

/*
 * The function fiat_fp118_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x3f]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x3fffff]]
 */
void fiat_fp118_from_bytes(uint32_t out1[4], const uint8_t arg1[15]) {
  uint32_t x1;
  uint32_t x2;
  uint8_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint8_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint8_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint8_t x15;
  uint32_t x16;
  uint32_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  x1 = ((uint32_t)(arg1[14]) << 16);
  x2 = ((uint32_t)(arg1[13]) << 8);
  x3 = (arg1[12]);
  x4 = ((uint32_t)(arg1[11]) << 24);
  x5 = ((uint32_t)(arg1[10]) << 16);
  x6 = ((uint32_t)(arg1[9]) << 8);
  x7 = (arg1[8]);
  x8 = ((uint32_t)(arg1[7]) << 24);
  x9 = ((uint32_t)(arg1[6]) << 16);
  x10 = ((uint32_t)(arg1[5]) << 8);
  x11 = (arg1[4]);
  x12 = ((uint32_t)(arg1[3]) << 24);
  x13 = ((uint32_t)(arg1[2]) << 16);
  x14 = ((uint32_t)(arg1[1]) << 8);
  x15 = (arg1[0]);
  x16 = (x14 + (uint32_t)x15);
  x17 = (x13 + x16);
  x18 = (x12 + x17);
  x19 = (x10 + (uint32_t)x11);
  x20 = (x9 + x19);
  x21 = (x8 + x20);
  x22 = (x6 + (uint32_t)x7);
  x23 = (x5 + x22);
  x24 = (x4 + x23);
  x25 = (x2 + (uint32_t)x3);
  x26 = (x1 + x25);
  out1[0] = x18;
  out1[1] = x21;
  out1[2] = x24;
  out1[3] = x26;
}

/*
 * The function fiat_fp118_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp118_set_one(fiat_fp118_montgomery_domain_field_element out1) {
  out1[0] = UINT16_C(0x677);
  out1[1] = UINT32_C(0x1b000000);
  out1[2] = UINT32_C(0xca66f5fa);
  out1[3] = UINT32_C(0x24a590);
}

/*
 * The function fiat_fp118_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp118_msat(uint32_t out1[5]) {
  out1[0] = UINT32_C(0xffffffff);
  out1[1] = UINT32_C(0x82ffffff);
  out1[2] = UINT32_C(0x3c5bd1c1);
  out1[3] = UINT32_C(0x27939f);
  out1[4] = 0x0;
}

/*
 * The function fiat_fp118_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp118_divstep_precomp(uint32_t out1[4]) {
  out1[0] = UINT32_C(0xe1e4c94c);
  out1[1] = UINT32_C(0x5e9b1dd2);
  out1[2] = UINT32_C(0xfe33f8a);
  out1[3] = UINT32_C(0x17a44d);
}

/*
 * The function fiat_fp118_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp118_divstep(uint32_t* out1, uint32_t out2[5], uint32_t out3[5], uint32_t out4[4], uint32_t out5[4], uint32_t arg1, const uint32_t arg2[5], const uint32_t arg3[5], const uint32_t arg4[4], const uint32_t arg5[4]) {
  uint32_t x1;
  fiat_fp118_uint1 x2;
  fiat_fp118_uint1 x3;
  uint32_t x4;
  fiat_fp118_uint1 x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp118_uint1 x13;
  uint32_t x14;
  fiat_fp118_uint1 x15;
  uint32_t x16;
  fiat_fp118_uint1 x17;
  uint32_t x18;
  fiat_fp118_uint1 x19;
  uint32_t x20;
  fiat_fp118_uint1 x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  fiat_fp118_uint1 x32;
  uint32_t x33;
  fiat_fp118_uint1 x34;
  uint32_t x35;
  fiat_fp118_uint1 x36;
  uint32_t x37;
  fiat_fp118_uint1 x38;
  uint32_t x39;
  fiat_fp118_uint1 x40;
  uint32_t x41;
  fiat_fp118_uint1 x42;
  uint32_t x43;
  fiat_fp118_uint1 x44;
  uint32_t x45;
  fiat_fp118_uint1 x46;
  uint32_t x47;
  fiat_fp118_uint1 x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  uint32_t x53;
  fiat_fp118_uint1 x54;
  uint32_t x55;
  fiat_fp118_uint1 x56;
  uint32_t x57;
  fiat_fp118_uint1 x58;
  uint32_t x59;
  fiat_fp118_uint1 x60;
  uint32_t x61;
  uint32_t x62;
  fiat_fp118_uint1 x63;
  uint32_t x64;
  fiat_fp118_uint1 x65;
  uint32_t x66;
  fiat_fp118_uint1 x67;
  uint32_t x68;
  fiat_fp118_uint1 x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  fiat_fp118_uint1 x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  uint32_t x79;
  uint32_t x80;
  fiat_fp118_uint1 x81;
  uint32_t x82;
  fiat_fp118_uint1 x83;
  uint32_t x84;
  fiat_fp118_uint1 x85;
  uint32_t x86;
  fiat_fp118_uint1 x87;
  uint32_t x88;
  fiat_fp118_uint1 x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  fiat_fp118_uint1 x95;
  uint32_t x96;
  fiat_fp118_uint1 x97;
  uint32_t x98;
  fiat_fp118_uint1 x99;
  uint32_t x100;
  fiat_fp118_uint1 x101;
  uint32_t x102;
  fiat_fp118_uint1 x103;
  uint32_t x104;
  fiat_fp118_uint1 x105;
  uint32_t x106;
  fiat_fp118_uint1 x107;
  uint32_t x108;
  fiat_fp118_uint1 x109;
  uint32_t x110;
  fiat_fp118_uint1 x111;
  uint32_t x112;
  fiat_fp118_uint1 x113;
  uint32_t x114;
  uint32_t x115;
  uint32_t x116;
  uint32_t x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  fiat_fp118_addcarryx_u32(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_fp118_uint1)((fiat_fp118_uint1)(x1 >> 31) & (fiat_fp118_uint1)((arg3[0]) & 0x1));
  fiat_fp118_addcarryx_u32(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_fp118_cmovznz_u32(&x6, x3, arg1, x4);
  fiat_fp118_cmovznz_u32(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_fp118_cmovznz_u32(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_fp118_cmovznz_u32(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_fp118_cmovznz_u32(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_fp118_cmovznz_u32(&x11, x3, (arg2[4]), (arg3[4]));
  fiat_fp118_addcarryx_u32(&x12, &x13, 0x0, 0x1, (~(arg2[0])));
  fiat_fp118_addcarryx_u32(&x14, &x15, x13, 0x0, (~(arg2[1])));
  fiat_fp118_addcarryx_u32(&x16, &x17, x15, 0x0, (~(arg2[2])));
  fiat_fp118_addcarryx_u32(&x18, &x19, x17, 0x0, (~(arg2[3])));
  fiat_fp118_addcarryx_u32(&x20, &x21, x19, 0x0, (~(arg2[4])));
  fiat_fp118_cmovznz_u32(&x22, x3, (arg3[0]), x12);
  fiat_fp118_cmovznz_u32(&x23, x3, (arg3[1]), x14);
  fiat_fp118_cmovznz_u32(&x24, x3, (arg3[2]), x16);
  fiat_fp118_cmovznz_u32(&x25, x3, (arg3[3]), x18);
  fiat_fp118_cmovznz_u32(&x26, x3, (arg3[4]), x20);
  fiat_fp118_cmovznz_u32(&x27, x3, (arg4[0]), (arg5[0]));
  fiat_fp118_cmovznz_u32(&x28, x3, (arg4[1]), (arg5[1]));
  fiat_fp118_cmovznz_u32(&x29, x3, (arg4[2]), (arg5[2]));
  fiat_fp118_cmovznz_u32(&x30, x3, (arg4[3]), (arg5[3]));
  fiat_fp118_addcarryx_u32(&x31, &x32, 0x0, x27, x27);
  fiat_fp118_addcarryx_u32(&x33, &x34, x32, x28, x28);
  fiat_fp118_addcarryx_u32(&x35, &x36, x34, x29, x29);
  fiat_fp118_addcarryx_u32(&x37, &x38, x36, x30, x30);
  fiat_fp118_subborrowx_u32(&x39, &x40, 0x0, x31, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x41, &x42, x40, x33, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x43, &x44, x42, x35, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x45, &x46, x44, x37, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x47, &x48, x46, x38, 0x0);
  x49 = (arg4[3]);
  x50 = (arg4[2]);
  x51 = (arg4[1]);
  x52 = (arg4[0]);
  fiat_fp118_subborrowx_u32(&x53, &x54, 0x0, 0x0, x52);
  fiat_fp118_subborrowx_u32(&x55, &x56, x54, 0x0, x51);
  fiat_fp118_subborrowx_u32(&x57, &x58, x56, 0x0, x50);
  fiat_fp118_subborrowx_u32(&x59, &x60, x58, 0x0, x49);
  fiat_fp118_cmovznz_u32(&x61, x60, 0x0, UINT32_C(0xffffffff));
  fiat_fp118_addcarryx_u32(&x62, &x63, 0x0, x53, x61);
  fiat_fp118_addcarryx_u32(&x64, &x65, x63, x55, (x61 & UINT32_C(0x82ffffff)));
  fiat_fp118_addcarryx_u32(&x66, &x67, x65, x57, (x61 & UINT32_C(0x3c5bd1c1)));
  fiat_fp118_addcarryx_u32(&x68, &x69, x67, x59, (x61 & UINT32_C(0x27939f)));
  fiat_fp118_cmovznz_u32(&x70, x3, (arg5[0]), x62);
  fiat_fp118_cmovznz_u32(&x71, x3, (arg5[1]), x64);
  fiat_fp118_cmovznz_u32(&x72, x3, (arg5[2]), x66);
  fiat_fp118_cmovznz_u32(&x73, x3, (arg5[3]), x68);
  x74 = (fiat_fp118_uint1)(x22 & 0x1);
  fiat_fp118_cmovznz_u32(&x75, x74, 0x0, x7);
  fiat_fp118_cmovznz_u32(&x76, x74, 0x0, x8);
  fiat_fp118_cmovznz_u32(&x77, x74, 0x0, x9);
  fiat_fp118_cmovznz_u32(&x78, x74, 0x0, x10);
  fiat_fp118_cmovznz_u32(&x79, x74, 0x0, x11);
  fiat_fp118_addcarryx_u32(&x80, &x81, 0x0, x22, x75);
  fiat_fp118_addcarryx_u32(&x82, &x83, x81, x23, x76);
  fiat_fp118_addcarryx_u32(&x84, &x85, x83, x24, x77);
  fiat_fp118_addcarryx_u32(&x86, &x87, x85, x25, x78);
  fiat_fp118_addcarryx_u32(&x88, &x89, x87, x26, x79);
  fiat_fp118_cmovznz_u32(&x90, x74, 0x0, x27);
  fiat_fp118_cmovznz_u32(&x91, x74, 0x0, x28);
  fiat_fp118_cmovznz_u32(&x92, x74, 0x0, x29);
  fiat_fp118_cmovznz_u32(&x93, x74, 0x0, x30);
  fiat_fp118_addcarryx_u32(&x94, &x95, 0x0, x70, x90);
  fiat_fp118_addcarryx_u32(&x96, &x97, x95, x71, x91);
  fiat_fp118_addcarryx_u32(&x98, &x99, x97, x72, x92);
  fiat_fp118_addcarryx_u32(&x100, &x101, x99, x73, x93);
  fiat_fp118_subborrowx_u32(&x102, &x103, 0x0, x94, UINT32_C(0xffffffff));
  fiat_fp118_subborrowx_u32(&x104, &x105, x103, x96, UINT32_C(0x82ffffff));
  fiat_fp118_subborrowx_u32(&x106, &x107, x105, x98, UINT32_C(0x3c5bd1c1));
  fiat_fp118_subborrowx_u32(&x108, &x109, x107, x100, UINT32_C(0x27939f));
  fiat_fp118_subborrowx_u32(&x110, &x111, x109, x101, 0x0);
  fiat_fp118_addcarryx_u32(&x112, &x113, 0x0, x6, 0x1);
  x114 = ((x80 >> 1) | ((x82 << 31) & UINT32_C(0xffffffff)));
  x115 = ((x82 >> 1) | ((x84 << 31) & UINT32_C(0xffffffff)));
  x116 = ((x84 >> 1) | ((x86 << 31) & UINT32_C(0xffffffff)));
  x117 = ((x86 >> 1) | ((x88 << 31) & UINT32_C(0xffffffff)));
  x118 = ((x88 & UINT32_C(0x80000000)) | (x88 >> 1));
  fiat_fp118_cmovznz_u32(&x119, x48, x39, x31);
  fiat_fp118_cmovznz_u32(&x120, x48, x41, x33);
  fiat_fp118_cmovznz_u32(&x121, x48, x43, x35);
  fiat_fp118_cmovznz_u32(&x122, x48, x45, x37);
  fiat_fp118_cmovznz_u32(&x123, x111, x102, x94);
  fiat_fp118_cmovznz_u32(&x124, x111, x104, x96);
  fiat_fp118_cmovznz_u32(&x125, x111, x106, x98);
  fiat_fp118_cmovznz_u32(&x126, x111, x108, x100);
  *out1 = x112;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out2[4] = x11;
  out3[0] = x114;
  out3[1] = x115;
  out3[2] = x116;
  out3[3] = x117;
  out3[4] = x118;
  out4[0] = x119;
  out4[1] = x120;
  out4[2] = x121;
  out4[3] = x122;
  out5[0] = x123;
  out5[1] = x124;
  out5[2] = x125;
  out5[3] = x126;
}
