/* Autogenerated: word_by_word_montgomery fp131 64 0x6397b18cf129f1e8cffffffffffffffff */
/* curve description: fp131 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: (all) */
/* m = 0x6397b18cf129f1e8cffffffffffffffff (from "0x6397b18cf129f1e8cffffffffffffffff") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 64) + (z[2] << 128) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 64) + (z[2] << 128) in */
/*                            if x1 & (2^192-1) < 2^191 then x1 & (2^192-1) else (x1 & (2^192-1)) - 2^192 */

#include <stdint.h>
typedef unsigned char fiat_fp131_uint1;
typedef signed char fiat_fp131_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_FP131_FIAT_EXTENSION __extension__
#  define FIAT_FP131_FIAT_INLINE __inline__
#else
#  define FIAT_FP131_FIAT_EXTENSION
#  define FIAT_FP131_FIAT_INLINE
#endif

FIAT_FP131_FIAT_EXTENSION typedef signed __int128 fiat_fp131_int128;
FIAT_FP131_FIAT_EXTENSION typedef unsigned __int128 fiat_fp131_uint128;

/* The type fiat_fp131_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_fp131_montgomery_domain_field_element[3];

/* The type fiat_fp131_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_fp131_non_montgomery_domain_field_element[3];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_fp131_addcarryx_u64 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^64
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp131_addcarryx_u64(uint64_t* out1, fiat_fp131_uint1* out2, fiat_fp131_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_fp131_uint128 x1;
  uint64_t x2;
  fiat_fp131_uint1 x3;
  x1 = ((arg1 + (fiat_fp131_uint128)arg2) + arg3);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (fiat_fp131_uint1)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp131_subborrowx_u64 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^64
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp131_subborrowx_u64(uint64_t* out1, fiat_fp131_uint1* out2, fiat_fp131_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_fp131_int128 x1;
  fiat_fp131_int1 x2;
  uint64_t x3;
  x1 = ((arg2 - (fiat_fp131_int128)arg1) - arg3);
  x2 = (fiat_fp131_int1)(x1 >> 64);
  x3 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  *out1 = x3;
  *out2 = (fiat_fp131_uint1)(0x0 - x2);
}

/*
 * The function fiat_fp131_mulx_u64 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^64
 *   out2 = ⌊arg1 * arg2 / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_fp131_mulx_u64(uint64_t* out1, uint64_t* out2, uint64_t arg1, uint64_t arg2) {
  fiat_fp131_uint128 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = ((fiat_fp131_uint128)arg1 * arg2);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (uint64_t)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp131_cmovznz_u64 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_fp131_cmovznz_u64(uint64_t* out1, fiat_fp131_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_fp131_uint1 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_fp131_int1)(0x0 - x1) & UINT64_C(0xffffffffffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_fp131_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_mul(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  fiat_fp131_uint1 x11;
  uint64_t x12;
  fiat_fp131_uint1 x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  fiat_fp131_uint1 x22;
  uint64_t x23;
  fiat_fp131_uint1 x24;
  uint64_t x25;
  uint64_t x26;
  fiat_fp131_uint1 x27;
  uint64_t x28;
  fiat_fp131_uint1 x29;
  uint64_t x30;
  fiat_fp131_uint1 x31;
  uint64_t x32;
  fiat_fp131_uint1 x33;
  uint64_t x34;
  uint64_t x35;
  uint64_t x36;
  uint64_t x37;
  uint64_t x38;
  uint64_t x39;
  uint64_t x40;
  fiat_fp131_uint1 x41;
  uint64_t x42;
  fiat_fp131_uint1 x43;
  uint64_t x44;
  uint64_t x45;
  fiat_fp131_uint1 x46;
  uint64_t x47;
  fiat_fp131_uint1 x48;
  uint64_t x49;
  fiat_fp131_uint1 x50;
  uint64_t x51;
  fiat_fp131_uint1 x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  fiat_fp131_uint1 x60;
  uint64_t x61;
  fiat_fp131_uint1 x62;
  uint64_t x63;
  uint64_t x64;
  fiat_fp131_uint1 x65;
  uint64_t x66;
  fiat_fp131_uint1 x67;
  uint64_t x68;
  fiat_fp131_uint1 x69;
  uint64_t x70;
  fiat_fp131_uint1 x71;
  uint64_t x72;
  uint64_t x73;
  uint64_t x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  fiat_fp131_uint1 x80;
  uint64_t x81;
  fiat_fp131_uint1 x82;
  uint64_t x83;
  uint64_t x84;
  fiat_fp131_uint1 x85;
  uint64_t x86;
  fiat_fp131_uint1 x87;
  uint64_t x88;
  fiat_fp131_uint1 x89;
  uint64_t x90;
  fiat_fp131_uint1 x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  uint64_t x97;
  uint64_t x98;
  fiat_fp131_uint1 x99;
  uint64_t x100;
  fiat_fp131_uint1 x101;
  uint64_t x102;
  uint64_t x103;
  fiat_fp131_uint1 x104;
  uint64_t x105;
  fiat_fp131_uint1 x106;
  uint64_t x107;
  fiat_fp131_uint1 x108;
  uint64_t x109;
  fiat_fp131_uint1 x110;
  uint64_t x111;
  uint64_t x112;
  fiat_fp131_uint1 x113;
  uint64_t x114;
  fiat_fp131_uint1 x115;
  uint64_t x116;
  fiat_fp131_uint1 x117;
  uint64_t x118;
  fiat_fp131_uint1 x119;
  uint64_t x120;
  uint64_t x121;
  uint64_t x122;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp131_mulx_u64(&x4, &x5, x3, (arg2[2]));
  fiat_fp131_mulx_u64(&x6, &x7, x3, (arg2[1]));
  fiat_fp131_mulx_u64(&x8, &x9, x3, (arg2[0]));
  fiat_fp131_addcarryx_u64(&x10, &x11, 0x0, x9, x6);
  fiat_fp131_addcarryx_u64(&x12, &x13, x11, x7, x4);
  x14 = (x13 + x5);
  fiat_fp131_mulx_u64(&x15, &x16, x8, 0x6);
  fiat_fp131_mulx_u64(&x17, &x18, x8, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x19, &x20, x8, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x21, &x22, 0x0, x20, x17);
  fiat_fp131_addcarryx_u64(&x23, &x24, x22, x18, x15);
  x25 = (x24 + x16);
  fiat_fp131_addcarryx_u64(&x26, &x27, 0x0, x8, x19);
  fiat_fp131_addcarryx_u64(&x28, &x29, x27, x10, x21);
  fiat_fp131_addcarryx_u64(&x30, &x31, x29, x12, x23);
  fiat_fp131_addcarryx_u64(&x32, &x33, x31, x14, x25);
  fiat_fp131_mulx_u64(&x34, &x35, x1, (arg2[2]));
  fiat_fp131_mulx_u64(&x36, &x37, x1, (arg2[1]));
  fiat_fp131_mulx_u64(&x38, &x39, x1, (arg2[0]));
  fiat_fp131_addcarryx_u64(&x40, &x41, 0x0, x39, x36);
  fiat_fp131_addcarryx_u64(&x42, &x43, x41, x37, x34);
  x44 = (x43 + x35);
  fiat_fp131_addcarryx_u64(&x45, &x46, 0x0, x28, x38);
  fiat_fp131_addcarryx_u64(&x47, &x48, x46, x30, x40);
  fiat_fp131_addcarryx_u64(&x49, &x50, x48, x32, x42);
  fiat_fp131_addcarryx_u64(&x51, &x52, x50, x33, x44);
  fiat_fp131_mulx_u64(&x53, &x54, x45, 0x6);
  fiat_fp131_mulx_u64(&x55, &x56, x45, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x57, &x58, x45, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x59, &x60, 0x0, x58, x55);
  fiat_fp131_addcarryx_u64(&x61, &x62, x60, x56, x53);
  x63 = (x62 + x54);
  fiat_fp131_addcarryx_u64(&x64, &x65, 0x0, x45, x57);
  fiat_fp131_addcarryx_u64(&x66, &x67, x65, x47, x59);
  fiat_fp131_addcarryx_u64(&x68, &x69, x67, x49, x61);
  fiat_fp131_addcarryx_u64(&x70, &x71, x69, x51, x63);
  x72 = ((uint64_t)x71 + x52);
  fiat_fp131_mulx_u64(&x73, &x74, x2, (arg2[2]));
  fiat_fp131_mulx_u64(&x75, &x76, x2, (arg2[1]));
  fiat_fp131_mulx_u64(&x77, &x78, x2, (arg2[0]));
  fiat_fp131_addcarryx_u64(&x79, &x80, 0x0, x78, x75);
  fiat_fp131_addcarryx_u64(&x81, &x82, x80, x76, x73);
  x83 = (x82 + x74);
  fiat_fp131_addcarryx_u64(&x84, &x85, 0x0, x66, x77);
  fiat_fp131_addcarryx_u64(&x86, &x87, x85, x68, x79);
  fiat_fp131_addcarryx_u64(&x88, &x89, x87, x70, x81);
  fiat_fp131_addcarryx_u64(&x90, &x91, x89, x72, x83);
  fiat_fp131_mulx_u64(&x92, &x93, x84, 0x6);
  fiat_fp131_mulx_u64(&x94, &x95, x84, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x96, &x97, x84, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x98, &x99, 0x0, x97, x94);
  fiat_fp131_addcarryx_u64(&x100, &x101, x99, x95, x92);
  x102 = (x101 + x93);
  fiat_fp131_addcarryx_u64(&x103, &x104, 0x0, x84, x96);
  fiat_fp131_addcarryx_u64(&x105, &x106, x104, x86, x98);
  fiat_fp131_addcarryx_u64(&x107, &x108, x106, x88, x100);
  fiat_fp131_addcarryx_u64(&x109, &x110, x108, x90, x102);
  x111 = ((uint64_t)x110 + x91);
  fiat_fp131_subborrowx_u64(&x112, &x113, 0x0, x105, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x114, &x115, x113, x107, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x116, &x117, x115, x109, 0x6);
  fiat_fp131_subborrowx_u64(&x118, &x119, x117, x111, 0x0);
  fiat_fp131_cmovznz_u64(&x120, x119, x112, x105);
  fiat_fp131_cmovznz_u64(&x121, x119, x114, x107);
  fiat_fp131_cmovznz_u64(&x122, x119, x116, x109);
  out1[0] = x120;
  out1[1] = x121;
  out1[2] = x122;
}

/*
 * The function fiat_fp131_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_square(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  fiat_fp131_uint1 x11;
  uint64_t x12;
  fiat_fp131_uint1 x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  fiat_fp131_uint1 x22;
  uint64_t x23;
  fiat_fp131_uint1 x24;
  uint64_t x25;
  uint64_t x26;
  fiat_fp131_uint1 x27;
  uint64_t x28;
  fiat_fp131_uint1 x29;
  uint64_t x30;
  fiat_fp131_uint1 x31;
  uint64_t x32;
  fiat_fp131_uint1 x33;
  uint64_t x34;
  uint64_t x35;
  uint64_t x36;
  uint64_t x37;
  uint64_t x38;
  uint64_t x39;
  uint64_t x40;
  fiat_fp131_uint1 x41;
  uint64_t x42;
  fiat_fp131_uint1 x43;
  uint64_t x44;
  uint64_t x45;
  fiat_fp131_uint1 x46;
  uint64_t x47;
  fiat_fp131_uint1 x48;
  uint64_t x49;
  fiat_fp131_uint1 x50;
  uint64_t x51;
  fiat_fp131_uint1 x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  fiat_fp131_uint1 x60;
  uint64_t x61;
  fiat_fp131_uint1 x62;
  uint64_t x63;
  uint64_t x64;
  fiat_fp131_uint1 x65;
  uint64_t x66;
  fiat_fp131_uint1 x67;
  uint64_t x68;
  fiat_fp131_uint1 x69;
  uint64_t x70;
  fiat_fp131_uint1 x71;
  uint64_t x72;
  uint64_t x73;
  uint64_t x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  fiat_fp131_uint1 x80;
  uint64_t x81;
  fiat_fp131_uint1 x82;
  uint64_t x83;
  uint64_t x84;
  fiat_fp131_uint1 x85;
  uint64_t x86;
  fiat_fp131_uint1 x87;
  uint64_t x88;
  fiat_fp131_uint1 x89;
  uint64_t x90;
  fiat_fp131_uint1 x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  uint64_t x97;
  uint64_t x98;
  fiat_fp131_uint1 x99;
  uint64_t x100;
  fiat_fp131_uint1 x101;
  uint64_t x102;
  uint64_t x103;
  fiat_fp131_uint1 x104;
  uint64_t x105;
  fiat_fp131_uint1 x106;
  uint64_t x107;
  fiat_fp131_uint1 x108;
  uint64_t x109;
  fiat_fp131_uint1 x110;
  uint64_t x111;
  uint64_t x112;
  fiat_fp131_uint1 x113;
  uint64_t x114;
  fiat_fp131_uint1 x115;
  uint64_t x116;
  fiat_fp131_uint1 x117;
  uint64_t x118;
  fiat_fp131_uint1 x119;
  uint64_t x120;
  uint64_t x121;
  uint64_t x122;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp131_mulx_u64(&x4, &x5, x3, (arg1[2]));
  fiat_fp131_mulx_u64(&x6, &x7, x3, (arg1[1]));
  fiat_fp131_mulx_u64(&x8, &x9, x3, (arg1[0]));
  fiat_fp131_addcarryx_u64(&x10, &x11, 0x0, x9, x6);
  fiat_fp131_addcarryx_u64(&x12, &x13, x11, x7, x4);
  x14 = (x13 + x5);
  fiat_fp131_mulx_u64(&x15, &x16, x8, 0x6);
  fiat_fp131_mulx_u64(&x17, &x18, x8, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x19, &x20, x8, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x21, &x22, 0x0, x20, x17);
  fiat_fp131_addcarryx_u64(&x23, &x24, x22, x18, x15);
  x25 = (x24 + x16);
  fiat_fp131_addcarryx_u64(&x26, &x27, 0x0, x8, x19);
  fiat_fp131_addcarryx_u64(&x28, &x29, x27, x10, x21);
  fiat_fp131_addcarryx_u64(&x30, &x31, x29, x12, x23);
  fiat_fp131_addcarryx_u64(&x32, &x33, x31, x14, x25);
  fiat_fp131_mulx_u64(&x34, &x35, x1, (arg1[2]));
  fiat_fp131_mulx_u64(&x36, &x37, x1, (arg1[1]));
  fiat_fp131_mulx_u64(&x38, &x39, x1, (arg1[0]));
  fiat_fp131_addcarryx_u64(&x40, &x41, 0x0, x39, x36);
  fiat_fp131_addcarryx_u64(&x42, &x43, x41, x37, x34);
  x44 = (x43 + x35);
  fiat_fp131_addcarryx_u64(&x45, &x46, 0x0, x28, x38);
  fiat_fp131_addcarryx_u64(&x47, &x48, x46, x30, x40);
  fiat_fp131_addcarryx_u64(&x49, &x50, x48, x32, x42);
  fiat_fp131_addcarryx_u64(&x51, &x52, x50, x33, x44);
  fiat_fp131_mulx_u64(&x53, &x54, x45, 0x6);
  fiat_fp131_mulx_u64(&x55, &x56, x45, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x57, &x58, x45, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x59, &x60, 0x0, x58, x55);
  fiat_fp131_addcarryx_u64(&x61, &x62, x60, x56, x53);
  x63 = (x62 + x54);
  fiat_fp131_addcarryx_u64(&x64, &x65, 0x0, x45, x57);
  fiat_fp131_addcarryx_u64(&x66, &x67, x65, x47, x59);
  fiat_fp131_addcarryx_u64(&x68, &x69, x67, x49, x61);
  fiat_fp131_addcarryx_u64(&x70, &x71, x69, x51, x63);
  x72 = ((uint64_t)x71 + x52);
  fiat_fp131_mulx_u64(&x73, &x74, x2, (arg1[2]));
  fiat_fp131_mulx_u64(&x75, &x76, x2, (arg1[1]));
  fiat_fp131_mulx_u64(&x77, &x78, x2, (arg1[0]));
  fiat_fp131_addcarryx_u64(&x79, &x80, 0x0, x78, x75);
  fiat_fp131_addcarryx_u64(&x81, &x82, x80, x76, x73);
  x83 = (x82 + x74);
  fiat_fp131_addcarryx_u64(&x84, &x85, 0x0, x66, x77);
  fiat_fp131_addcarryx_u64(&x86, &x87, x85, x68, x79);
  fiat_fp131_addcarryx_u64(&x88, &x89, x87, x70, x81);
  fiat_fp131_addcarryx_u64(&x90, &x91, x89, x72, x83);
  fiat_fp131_mulx_u64(&x92, &x93, x84, 0x6);
  fiat_fp131_mulx_u64(&x94, &x95, x84, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x96, &x97, x84, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x98, &x99, 0x0, x97, x94);
  fiat_fp131_addcarryx_u64(&x100, &x101, x99, x95, x92);
  x102 = (x101 + x93);
  fiat_fp131_addcarryx_u64(&x103, &x104, 0x0, x84, x96);
  fiat_fp131_addcarryx_u64(&x105, &x106, x104, x86, x98);
  fiat_fp131_addcarryx_u64(&x107, &x108, x106, x88, x100);
  fiat_fp131_addcarryx_u64(&x109, &x110, x108, x90, x102);
  x111 = ((uint64_t)x110 + x91);
  fiat_fp131_subborrowx_u64(&x112, &x113, 0x0, x105, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x114, &x115, x113, x107, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x116, &x117, x115, x109, 0x6);
  fiat_fp131_subborrowx_u64(&x118, &x119, x117, x111, 0x0);
  fiat_fp131_cmovznz_u64(&x120, x119, x112, x105);
  fiat_fp131_cmovznz_u64(&x121, x119, x114, x107);
  fiat_fp131_cmovznz_u64(&x122, x119, x116, x109);
  out1[0] = x120;
  out1[1] = x121;
  out1[2] = x122;
}

/*
 * The function fiat_fp131_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_add(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint64_t x1;
  fiat_fp131_uint1 x2;
  uint64_t x3;
  fiat_fp131_uint1 x4;
  uint64_t x5;
  fiat_fp131_uint1 x6;
  uint64_t x7;
  fiat_fp131_uint1 x8;
  uint64_t x9;
  fiat_fp131_uint1 x10;
  uint64_t x11;
  fiat_fp131_uint1 x12;
  uint64_t x13;
  fiat_fp131_uint1 x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  fiat_fp131_addcarryx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp131_addcarryx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp131_addcarryx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp131_subborrowx_u64(&x7, &x8, 0x0, x1, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x9, &x10, x8, x3, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x11, &x12, x10, x5, 0x6);
  fiat_fp131_subborrowx_u64(&x13, &x14, x12, x6, 0x0);
  fiat_fp131_cmovznz_u64(&x15, x14, x7, x1);
  fiat_fp131_cmovznz_u64(&x16, x14, x9, x3);
  fiat_fp131_cmovznz_u64(&x17, x14, x11, x5);
  out1[0] = x15;
  out1[1] = x16;
  out1[2] = x17;
}

/*
 * The function fiat_fp131_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_sub(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint64_t x1;
  fiat_fp131_uint1 x2;
  uint64_t x3;
  fiat_fp131_uint1 x4;
  uint64_t x5;
  fiat_fp131_uint1 x6;
  uint64_t x7;
  uint64_t x8;
  fiat_fp131_uint1 x9;
  uint64_t x10;
  fiat_fp131_uint1 x11;
  uint64_t x12;
  fiat_fp131_uint1 x13;
  fiat_fp131_subborrowx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp131_subborrowx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp131_subborrowx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp131_cmovznz_u64(&x7, x6, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x8, &x9, 0x0, x1, x7);
  fiat_fp131_addcarryx_u64(&x10, &x11, x9, x3, (x7 & UINT64_C(0x397b18cf129f1e8c)));
  fiat_fp131_addcarryx_u64(&x12, &x13, x11, x5, (x7 & 0x6));
  out1[0] = x8;
  out1[1] = x10;
  out1[2] = x12;
}

/*
 * The function fiat_fp131_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_opp(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint64_t x1;
  fiat_fp131_uint1 x2;
  uint64_t x3;
  fiat_fp131_uint1 x4;
  uint64_t x5;
  fiat_fp131_uint1 x6;
  uint64_t x7;
  uint64_t x8;
  fiat_fp131_uint1 x9;
  uint64_t x10;
  fiat_fp131_uint1 x11;
  uint64_t x12;
  fiat_fp131_uint1 x13;
  fiat_fp131_subborrowx_u64(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_fp131_subborrowx_u64(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_fp131_subborrowx_u64(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_fp131_cmovznz_u64(&x7, x6, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x8, &x9, 0x0, x1, x7);
  fiat_fp131_addcarryx_u64(&x10, &x11, x9, x3, (x7 & UINT64_C(0x397b18cf129f1e8c)));
  fiat_fp131_addcarryx_u64(&x12, &x13, x11, x5, (x7 & 0x6));
  out1[0] = x8;
  out1[1] = x10;
  out1[2] = x12;
}

/*
 * The function fiat_fp131_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^64)⁻¹ mod m)^3) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_from_montgomery(fiat_fp131_non_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  fiat_fp131_uint1 x9;
  uint64_t x10;
  fiat_fp131_uint1 x11;
  uint64_t x12;
  fiat_fp131_uint1 x13;
  uint64_t x14;
  fiat_fp131_uint1 x15;
  uint64_t x16;
  fiat_fp131_uint1 x17;
  uint64_t x18;
  fiat_fp131_uint1 x19;
  uint64_t x20;
  fiat_fp131_uint1 x21;
  uint64_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  fiat_fp131_uint1 x29;
  uint64_t x30;
  fiat_fp131_uint1 x31;
  uint64_t x32;
  fiat_fp131_uint1 x33;
  uint64_t x34;
  fiat_fp131_uint1 x35;
  uint64_t x36;
  fiat_fp131_uint1 x37;
  uint64_t x38;
  fiat_fp131_uint1 x39;
  uint64_t x40;
  fiat_fp131_uint1 x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  uint64_t x48;
  fiat_fp131_uint1 x49;
  uint64_t x50;
  fiat_fp131_uint1 x51;
  uint64_t x52;
  fiat_fp131_uint1 x53;
  uint64_t x54;
  fiat_fp131_uint1 x55;
  uint64_t x56;
  fiat_fp131_uint1 x57;
  uint64_t x58;
  uint64_t x59;
  fiat_fp131_uint1 x60;
  uint64_t x61;
  fiat_fp131_uint1 x62;
  uint64_t x63;
  fiat_fp131_uint1 x64;
  uint64_t x65;
  fiat_fp131_uint1 x66;
  uint64_t x67;
  uint64_t x68;
  uint64_t x69;
  x1 = (arg1[0]);
  fiat_fp131_mulx_u64(&x2, &x3, x1, 0x6);
  fiat_fp131_mulx_u64(&x4, &x5, x1, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x6, &x7, x1, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x8, &x9, 0x0, x7, x4);
  fiat_fp131_addcarryx_u64(&x10, &x11, x9, x5, x2);
  fiat_fp131_addcarryx_u64(&x12, &x13, 0x0, x1, x6);
  fiat_fp131_addcarryx_u64(&x14, &x15, x13, 0x0, x8);
  fiat_fp131_addcarryx_u64(&x16, &x17, x15, 0x0, x10);
  fiat_fp131_addcarryx_u64(&x18, &x19, 0x0, x14, (arg1[1]));
  fiat_fp131_addcarryx_u64(&x20, &x21, x19, x16, 0x0);
  fiat_fp131_mulx_u64(&x22, &x23, x18, 0x6);
  fiat_fp131_mulx_u64(&x24, &x25, x18, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x26, &x27, x18, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x28, &x29, 0x0, x27, x24);
  fiat_fp131_addcarryx_u64(&x30, &x31, x29, x25, x22);
  fiat_fp131_addcarryx_u64(&x32, &x33, 0x0, x18, x26);
  fiat_fp131_addcarryx_u64(&x34, &x35, x33, x20, x28);
  fiat_fp131_addcarryx_u64(&x36, &x37, x35, (x21 + (x17 + (x11 + x3))), x30);
  fiat_fp131_addcarryx_u64(&x38, &x39, 0x0, x34, (arg1[2]));
  fiat_fp131_addcarryx_u64(&x40, &x41, x39, x36, 0x0);
  fiat_fp131_mulx_u64(&x42, &x43, x38, 0x6);
  fiat_fp131_mulx_u64(&x44, &x45, x38, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x46, &x47, x38, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x48, &x49, 0x0, x47, x44);
  fiat_fp131_addcarryx_u64(&x50, &x51, x49, x45, x42);
  fiat_fp131_addcarryx_u64(&x52, &x53, 0x0, x38, x46);
  fiat_fp131_addcarryx_u64(&x54, &x55, x53, x40, x48);
  fiat_fp131_addcarryx_u64(&x56, &x57, x55, (x41 + (x37 + (x31 + x23))), x50);
  x58 = (x57 + (x51 + x43));
  fiat_fp131_subborrowx_u64(&x59, &x60, 0x0, x54, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x61, &x62, x60, x56, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x63, &x64, x62, x58, 0x6);
  fiat_fp131_subborrowx_u64(&x65, &x66, x64, 0x0, 0x0);
  fiat_fp131_cmovznz_u64(&x67, x66, x59, x54);
  fiat_fp131_cmovznz_u64(&x68, x66, x61, x56);
  fiat_fp131_cmovznz_u64(&x69, x66, x63, x58);
  out1[0] = x67;
  out1[1] = x68;
  out1[2] = x69;
}

/*
 * The function fiat_fp131_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_to_montgomery(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_non_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  fiat_fp131_uint1 x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_fp131_uint1 x17;
  uint64_t x18;
  fiat_fp131_uint1 x19;
  uint64_t x20;
  fiat_fp131_uint1 x21;
  uint64_t x22;
  fiat_fp131_uint1 x23;
  uint64_t x24;
  fiat_fp131_uint1 x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  fiat_fp131_uint1 x31;
  uint64_t x32;
  fiat_fp131_uint1 x33;
  uint64_t x34;
  fiat_fp131_uint1 x35;
  uint64_t x36;
  uint64_t x37;
  uint64_t x38;
  uint64_t x39;
  uint64_t x40;
  uint64_t x41;
  uint64_t x42;
  fiat_fp131_uint1 x43;
  uint64_t x44;
  fiat_fp131_uint1 x45;
  uint64_t x46;
  fiat_fp131_uint1 x47;
  uint64_t x48;
  fiat_fp131_uint1 x49;
  uint64_t x50;
  fiat_fp131_uint1 x51;
  uint64_t x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  fiat_fp131_uint1 x57;
  uint64_t x58;
  fiat_fp131_uint1 x59;
  uint64_t x60;
  fiat_fp131_uint1 x61;
  uint64_t x62;
  uint64_t x63;
  uint64_t x64;
  uint64_t x65;
  uint64_t x66;
  uint64_t x67;
  uint64_t x68;
  fiat_fp131_uint1 x69;
  uint64_t x70;
  fiat_fp131_uint1 x71;
  uint64_t x72;
  fiat_fp131_uint1 x73;
  uint64_t x74;
  fiat_fp131_uint1 x75;
  uint64_t x76;
  fiat_fp131_uint1 x77;
  uint64_t x78;
  uint64_t x79;
  fiat_fp131_uint1 x80;
  uint64_t x81;
  fiat_fp131_uint1 x82;
  uint64_t x83;
  fiat_fp131_uint1 x84;
  uint64_t x85;
  fiat_fp131_uint1 x86;
  uint64_t x87;
  uint64_t x88;
  uint64_t x89;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp131_mulx_u64(&x4, &x5, x3, UINT64_C(0x2bdbc90ab20fc329));
  fiat_fp131_mulx_u64(&x6, &x7, x3, UINT64_C(0x120ad6c5bfa60904));
  fiat_fp131_addcarryx_u64(&x8, &x9, 0x0, x7, x4);
  fiat_fp131_mulx_u64(&x10, &x11, x6, 0x6);
  fiat_fp131_mulx_u64(&x12, &x13, x6, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x14, &x15, x6, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x16, &x17, 0x0, x15, x12);
  fiat_fp131_addcarryx_u64(&x18, &x19, x17, x13, x10);
  fiat_fp131_addcarryx_u64(&x20, &x21, 0x0, x6, x14);
  fiat_fp131_addcarryx_u64(&x22, &x23, x21, x8, x16);
  fiat_fp131_addcarryx_u64(&x24, &x25, x23, (x9 + x5), x18);
  fiat_fp131_mulx_u64(&x26, &x27, x1, UINT64_C(0x2bdbc90ab20fc329));
  fiat_fp131_mulx_u64(&x28, &x29, x1, UINT64_C(0x120ad6c5bfa60904));
  fiat_fp131_addcarryx_u64(&x30, &x31, 0x0, x29, x26);
  fiat_fp131_addcarryx_u64(&x32, &x33, 0x0, x22, x28);
  fiat_fp131_addcarryx_u64(&x34, &x35, x33, x24, x30);
  fiat_fp131_mulx_u64(&x36, &x37, x32, 0x6);
  fiat_fp131_mulx_u64(&x38, &x39, x32, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x40, &x41, x32, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x42, &x43, 0x0, x41, x38);
  fiat_fp131_addcarryx_u64(&x44, &x45, x43, x39, x36);
  fiat_fp131_addcarryx_u64(&x46, &x47, 0x0, x32, x40);
  fiat_fp131_addcarryx_u64(&x48, &x49, x47, x34, x42);
  fiat_fp131_addcarryx_u64(&x50, &x51, x49, ((x35 + (x25 + (x19 + x11))) + (x31 + x27)), x44);
  fiat_fp131_mulx_u64(&x52, &x53, x2, UINT64_C(0x2bdbc90ab20fc329));
  fiat_fp131_mulx_u64(&x54, &x55, x2, UINT64_C(0x120ad6c5bfa60904));
  fiat_fp131_addcarryx_u64(&x56, &x57, 0x0, x55, x52);
  fiat_fp131_addcarryx_u64(&x58, &x59, 0x0, x48, x54);
  fiat_fp131_addcarryx_u64(&x60, &x61, x59, x50, x56);
  fiat_fp131_mulx_u64(&x62, &x63, x58, 0x6);
  fiat_fp131_mulx_u64(&x64, &x65, x58, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_mulx_u64(&x66, &x67, x58, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x68, &x69, 0x0, x67, x64);
  fiat_fp131_addcarryx_u64(&x70, &x71, x69, x65, x62);
  fiat_fp131_addcarryx_u64(&x72, &x73, 0x0, x58, x66);
  fiat_fp131_addcarryx_u64(&x74, &x75, x73, x60, x68);
  fiat_fp131_addcarryx_u64(&x76, &x77, x75, ((x61 + (x51 + (x45 + x37))) + (x57 + x53)), x70);
  x78 = (x77 + (x71 + x63));
  fiat_fp131_subborrowx_u64(&x79, &x80, 0x0, x74, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x81, &x82, x80, x76, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x83, &x84, x82, x78, 0x6);
  fiat_fp131_subborrowx_u64(&x85, &x86, x84, 0x0, 0x0);
  fiat_fp131_cmovznz_u64(&x87, x86, x79, x74);
  fiat_fp131_cmovznz_u64(&x88, x86, x81, x76);
  fiat_fp131_cmovznz_u64(&x89, x86, x83, x78);
  out1[0] = x87;
  out1[1] = x88;
  out1[2] = x89;
}

/*
 * The function fiat_fp131_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_fp131_nonzero(uint64_t* out1, const uint64_t arg1[3]) {
  uint64_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | (arg1[2])));
  *out1 = x1;
}

/*
 * The function fiat_fp131_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_fp131_selectznz(uint64_t out1[3], fiat_fp131_uint1 arg1, const uint64_t arg2[3], const uint64_t arg3[3]) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  fiat_fp131_cmovznz_u64(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_fp131_cmovznz_u64(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_fp131_cmovznz_u64(&x3, arg1, (arg2[2]), (arg3[2]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
}

/*
 * The function fiat_fp131_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..16]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0x7]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7]]
 */
void fiat_fp131_to_bytes(uint8_t out1[17], const uint64_t arg1[3]) {
  uint8_t x1;
  uint64_t x2;
  uint64_t x3;
  uint8_t x4;
  uint64_t x5;
  uint8_t x6;
  uint64_t x7;
  uint8_t x8;
  uint64_t x9;
  uint8_t x10;
  uint64_t x11;
  uint8_t x12;
  uint64_t x13;
  uint8_t x14;
  uint64_t x15;
  uint8_t x16;
  uint8_t x17;
  uint8_t x18;
  uint64_t x19;
  uint8_t x20;
  uint64_t x21;
  uint8_t x22;
  uint64_t x23;
  uint8_t x24;
  uint64_t x25;
  uint8_t x26;
  uint64_t x27;
  uint8_t x28;
  uint64_t x29;
  uint8_t x30;
  uint8_t x31;
  x1 = (uint8_t)(arg1[2]);
  x2 = (arg1[1]);
  x3 = (arg1[0]);
  x4 = (uint8_t)(x3 & UINT8_C(0xff));
  x5 = (x3 >> 8);
  x6 = (uint8_t)(x5 & UINT8_C(0xff));
  x7 = (x5 >> 8);
  x8 = (uint8_t)(x7 & UINT8_C(0xff));
  x9 = (x7 >> 8);
  x10 = (uint8_t)(x9 & UINT8_C(0xff));
  x11 = (x9 >> 8);
  x12 = (uint8_t)(x11 & UINT8_C(0xff));
  x13 = (x11 >> 8);
  x14 = (uint8_t)(x13 & UINT8_C(0xff));
  x15 = (x13 >> 8);
  x16 = (uint8_t)(x15 & UINT8_C(0xff));
  x17 = (uint8_t)(x15 >> 8);
  x18 = (uint8_t)(x2 & UINT8_C(0xff));
  x19 = (x2 >> 8);
  x20 = (uint8_t)(x19 & UINT8_C(0xff));
  x21 = (x19 >> 8);
  x22 = (uint8_t)(x21 & UINT8_C(0xff));
  x23 = (x21 >> 8);
  x24 = (uint8_t)(x23 & UINT8_C(0xff));
  x25 = (x23 >> 8);
  x26 = (uint8_t)(x25 & UINT8_C(0xff));
  x27 = (x25 >> 8);
  x28 = (uint8_t)(x27 & UINT8_C(0xff));
  x29 = (x27 >> 8);
  x30 = (uint8_t)(x29 & UINT8_C(0xff));
  x31 = (uint8_t)(x29 >> 8);
  out1[0] = x4;
  out1[1] = x6;
  out1[2] = x8;
  out1[3] = x10;
  out1[4] = x12;
  out1[5] = x14;
  out1[6] = x16;
  out1[7] = x17;
  out1[8] = x18;
  out1[9] = x20;
  out1[10] = x22;
  out1[11] = x24;
  out1[12] = x26;
  out1[13] = x28;
  out1[14] = x30;
  out1[15] = x31;
  out1[16] = x1;
}

/*
 * The function fiat_fp131_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0x7]]
 */
void fiat_fp131_from_bytes(uint64_t out1[3], const uint8_t arg1[17]) {
  uint8_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint8_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint8_t x17;
  uint64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint64_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  x1 = (arg1[16]);
  x2 = ((uint64_t)(arg1[15]) << 56);
  x3 = ((uint64_t)(arg1[14]) << 48);
  x4 = ((uint64_t)(arg1[13]) << 40);
  x5 = ((uint64_t)(arg1[12]) << 32);
  x6 = ((uint64_t)(arg1[11]) << 24);
  x7 = ((uint64_t)(arg1[10]) << 16);
  x8 = ((uint64_t)(arg1[9]) << 8);
  x9 = (arg1[8]);
  x10 = ((uint64_t)(arg1[7]) << 56);
  x11 = ((uint64_t)(arg1[6]) << 48);
  x12 = ((uint64_t)(arg1[5]) << 40);
  x13 = ((uint64_t)(arg1[4]) << 32);
  x14 = ((uint64_t)(arg1[3]) << 24);
  x15 = ((uint64_t)(arg1[2]) << 16);
  x16 = ((uint64_t)(arg1[1]) << 8);
  x17 = (arg1[0]);
  x18 = (x16 + (uint64_t)x17);
  x19 = (x15 + x18);
  x20 = (x14 + x19);
  x21 = (x13 + x20);
  x22 = (x12 + x21);
  x23 = (x11 + x22);
  x24 = (x10 + x23);
  x25 = (x8 + (uint64_t)x9);
  x26 = (x7 + x25);
  x27 = (x6 + x26);
  x28 = (x5 + x27);
  x29 = (x4 + x28);
  x30 = (x3 + x29);
  x31 = (x2 + x30);
  out1[0] = x24;
  out1[1] = x31;
  out1[2] = x1;
}

/*
 * The function fiat_fp131_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_set_one(fiat_fp131_montgomery_domain_field_element out1) {
  out1[0] = UINT64_C(0x2920a8a1210118c1);
  out1[1] = UINT64_C(0xccea8de7bf9fbfb3);
  out1[2] = 0x1;
}

/*
 * The function fiat_fp131_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_fp131_msat(uint64_t out1[4]) {
  out1[0] = UINT64_C(0xffffffffffffffff);
  out1[1] = UINT64_C(0x397b18cf129f1e8c);
  out1[2] = 0x6;
  out1[3] = 0x0;
}

/*
 * The function fiat_fp131_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_fp131_divstep_precomp(uint64_t out1[3]) {
  out1[0] = UINT64_C(0xf71f43f079cda301);
  out1[1] = UINT64_C(0xda0bea69af205095);
  out1[2] = 0x3;
}

/*
 * The function fiat_fp131_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_fp131_divstep(uint64_t* out1, uint64_t out2[4], uint64_t out3[4], uint64_t out4[3], uint64_t out5[3], uint64_t arg1, const uint64_t arg2[4], const uint64_t arg3[4], const uint64_t arg4[3], const uint64_t arg5[3]) {
  uint64_t x1;
  fiat_fp131_uint1 x2;
  fiat_fp131_uint1 x3;
  uint64_t x4;
  fiat_fp131_uint1 x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  fiat_fp131_uint1 x12;
  uint64_t x13;
  fiat_fp131_uint1 x14;
  uint64_t x15;
  fiat_fp131_uint1 x16;
  uint64_t x17;
  fiat_fp131_uint1 x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint64_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  fiat_fp131_uint1 x27;
  uint64_t x28;
  fiat_fp131_uint1 x29;
  uint64_t x30;
  fiat_fp131_uint1 x31;
  uint64_t x32;
  fiat_fp131_uint1 x33;
  uint64_t x34;
  fiat_fp131_uint1 x35;
  uint64_t x36;
  fiat_fp131_uint1 x37;
  uint64_t x38;
  fiat_fp131_uint1 x39;
  uint64_t x40;
  uint64_t x41;
  uint64_t x42;
  uint64_t x43;
  fiat_fp131_uint1 x44;
  uint64_t x45;
  fiat_fp131_uint1 x46;
  uint64_t x47;
  fiat_fp131_uint1 x48;
  uint64_t x49;
  uint64_t x50;
  fiat_fp131_uint1 x51;
  uint64_t x52;
  fiat_fp131_uint1 x53;
  uint64_t x54;
  fiat_fp131_uint1 x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  fiat_fp131_uint1 x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  uint64_t x63;
  uint64_t x64;
  fiat_fp131_uint1 x65;
  uint64_t x66;
  fiat_fp131_uint1 x67;
  uint64_t x68;
  fiat_fp131_uint1 x69;
  uint64_t x70;
  fiat_fp131_uint1 x71;
  uint64_t x72;
  uint64_t x73;
  uint64_t x74;
  uint64_t x75;
  fiat_fp131_uint1 x76;
  uint64_t x77;
  fiat_fp131_uint1 x78;
  uint64_t x79;
  fiat_fp131_uint1 x80;
  uint64_t x81;
  fiat_fp131_uint1 x82;
  uint64_t x83;
  fiat_fp131_uint1 x84;
  uint64_t x85;
  fiat_fp131_uint1 x86;
  uint64_t x87;
  fiat_fp131_uint1 x88;
  uint64_t x89;
  fiat_fp131_uint1 x90;
  uint64_t x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  uint64_t x97;
  uint64_t x98;
  uint64_t x99;
  uint64_t x100;
  fiat_fp131_addcarryx_u64(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_fp131_uint1)((fiat_fp131_uint1)(x1 >> 63) & (fiat_fp131_uint1)((arg3[0]) & 0x1));
  fiat_fp131_addcarryx_u64(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_fp131_cmovznz_u64(&x6, x3, arg1, x4);
  fiat_fp131_cmovznz_u64(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_fp131_cmovznz_u64(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_fp131_cmovznz_u64(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_fp131_cmovznz_u64(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_fp131_addcarryx_u64(&x11, &x12, 0x0, 0x1, (~(arg2[0])));
  fiat_fp131_addcarryx_u64(&x13, &x14, x12, 0x0, (~(arg2[1])));
  fiat_fp131_addcarryx_u64(&x15, &x16, x14, 0x0, (~(arg2[2])));
  fiat_fp131_addcarryx_u64(&x17, &x18, x16, 0x0, (~(arg2[3])));
  fiat_fp131_cmovznz_u64(&x19, x3, (arg3[0]), x11);
  fiat_fp131_cmovznz_u64(&x20, x3, (arg3[1]), x13);
  fiat_fp131_cmovznz_u64(&x21, x3, (arg3[2]), x15);
  fiat_fp131_cmovznz_u64(&x22, x3, (arg3[3]), x17);
  fiat_fp131_cmovznz_u64(&x23, x3, (arg4[0]), (arg5[0]));
  fiat_fp131_cmovznz_u64(&x24, x3, (arg4[1]), (arg5[1]));
  fiat_fp131_cmovznz_u64(&x25, x3, (arg4[2]), (arg5[2]));
  fiat_fp131_addcarryx_u64(&x26, &x27, 0x0, x23, x23);
  fiat_fp131_addcarryx_u64(&x28, &x29, x27, x24, x24);
  fiat_fp131_addcarryx_u64(&x30, &x31, x29, x25, x25);
  fiat_fp131_subborrowx_u64(&x32, &x33, 0x0, x26, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x34, &x35, x33, x28, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x36, &x37, x35, x30, 0x6);
  fiat_fp131_subborrowx_u64(&x38, &x39, x37, x31, 0x0);
  x40 = (arg4[2]);
  x41 = (arg4[1]);
  x42 = (arg4[0]);
  fiat_fp131_subborrowx_u64(&x43, &x44, 0x0, 0x0, x42);
  fiat_fp131_subborrowx_u64(&x45, &x46, x44, 0x0, x41);
  fiat_fp131_subborrowx_u64(&x47, &x48, x46, 0x0, x40);
  fiat_fp131_cmovznz_u64(&x49, x48, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_fp131_addcarryx_u64(&x50, &x51, 0x0, x43, x49);
  fiat_fp131_addcarryx_u64(&x52, &x53, x51, x45, (x49 & UINT64_C(0x397b18cf129f1e8c)));
  fiat_fp131_addcarryx_u64(&x54, &x55, x53, x47, (x49 & 0x6));
  fiat_fp131_cmovznz_u64(&x56, x3, (arg5[0]), x50);
  fiat_fp131_cmovznz_u64(&x57, x3, (arg5[1]), x52);
  fiat_fp131_cmovznz_u64(&x58, x3, (arg5[2]), x54);
  x59 = (fiat_fp131_uint1)(x19 & 0x1);
  fiat_fp131_cmovznz_u64(&x60, x59, 0x0, x7);
  fiat_fp131_cmovznz_u64(&x61, x59, 0x0, x8);
  fiat_fp131_cmovznz_u64(&x62, x59, 0x0, x9);
  fiat_fp131_cmovznz_u64(&x63, x59, 0x0, x10);
  fiat_fp131_addcarryx_u64(&x64, &x65, 0x0, x19, x60);
  fiat_fp131_addcarryx_u64(&x66, &x67, x65, x20, x61);
  fiat_fp131_addcarryx_u64(&x68, &x69, x67, x21, x62);
  fiat_fp131_addcarryx_u64(&x70, &x71, x69, x22, x63);
  fiat_fp131_cmovznz_u64(&x72, x59, 0x0, x23);
  fiat_fp131_cmovznz_u64(&x73, x59, 0x0, x24);
  fiat_fp131_cmovznz_u64(&x74, x59, 0x0, x25);
  fiat_fp131_addcarryx_u64(&x75, &x76, 0x0, x56, x72);
  fiat_fp131_addcarryx_u64(&x77, &x78, x76, x57, x73);
  fiat_fp131_addcarryx_u64(&x79, &x80, x78, x58, x74);
  fiat_fp131_subborrowx_u64(&x81, &x82, 0x0, x75, UINT64_C(0xffffffffffffffff));
  fiat_fp131_subborrowx_u64(&x83, &x84, x82, x77, UINT64_C(0x397b18cf129f1e8c));
  fiat_fp131_subborrowx_u64(&x85, &x86, x84, x79, 0x6);
  fiat_fp131_subborrowx_u64(&x87, &x88, x86, x80, 0x0);
  fiat_fp131_addcarryx_u64(&x89, &x90, 0x0, x6, 0x1);
  x91 = ((x64 >> 1) | ((x66 << 63) & UINT64_C(0xffffffffffffffff)));
  x92 = ((x66 >> 1) | ((x68 << 63) & UINT64_C(0xffffffffffffffff)));
  x93 = ((x68 >> 1) | ((x70 << 63) & UINT64_C(0xffffffffffffffff)));
  x94 = ((x70 & UINT64_C(0x8000000000000000)) | (x70 >> 1));
  fiat_fp131_cmovznz_u64(&x95, x39, x32, x26);
  fiat_fp131_cmovznz_u64(&x96, x39, x34, x28);
  fiat_fp131_cmovznz_u64(&x97, x39, x36, x30);
  fiat_fp131_cmovznz_u64(&x98, x88, x81, x75);
  fiat_fp131_cmovznz_u64(&x99, x88, x83, x77);
  fiat_fp131_cmovznz_u64(&x100, x88, x85, x79);
  *out1 = x89;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out3[0] = x91;
  out3[1] = x92;
  out3[2] = x93;
  out3[3] = x94;
  out4[0] = x95;
  out4[1] = x96;
  out4[2] = x97;
  out5[0] = x98;
  out5[1] = x99;
  out5[2] = x100;
}
