/* Autogenerated: word_by_word_montgomery fp131 32 0x6397b18cf129f1e8cffffffffffffffff */
/* curve description: fp131 */
/* machine_wordsize = 32 (from "32") */
/* requested operations: (all) */
/* m = 0x6397b18cf129f1e8cffffffffffffffff (from "0x6397b18cf129f1e8cffffffffffffffff") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) + (z[4] << 128) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 32) + (z[2] << 64) + (z[3] << 96) + (z[4] << 128) in */
/*                            if x1 & (2^160-1) < 2^159 then x1 & (2^160-1) else (x1 & (2^160-1)) - 2^160 */

#include <stdint.h>
typedef unsigned char fiat_fp131_uint1;
typedef signed char fiat_fp131_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_FP131_FIAT_INLINE __inline__
#else
#  define FIAT_FP131_FIAT_INLINE
#endif

/* The type fiat_fp131_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp131_montgomery_domain_field_element[5];

/* The type fiat_fp131_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp131_non_montgomery_domain_field_element[5];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_fp131_addcarryx_u32 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^32
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp131_addcarryx_u32(uint32_t* out1, fiat_fp131_uint1* out2, fiat_fp131_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  uint64_t x1;
  uint32_t x2;
  fiat_fp131_uint1 x3;
  x1 = ((arg1 + (uint64_t)arg2) + arg3);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (fiat_fp131_uint1)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp131_subborrowx_u32 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^32
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp131_subborrowx_u32(uint32_t* out1, fiat_fp131_uint1* out2, fiat_fp131_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  int64_t x1;
  fiat_fp131_int1 x2;
  uint32_t x3;
  x1 = ((arg2 - (int64_t)arg1) - arg3);
  x2 = (fiat_fp131_int1)(x1 >> 32);
  x3 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  *out1 = x3;
  *out2 = (fiat_fp131_uint1)(0x0 - x2);
}

/*
 * The function fiat_fp131_mulx_u32 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^32
 *   out2 = ⌊arg1 * arg2 / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0xffffffff]
 */
void fiat_fp131_mulx_u32(uint32_t* out1, uint32_t* out2, uint32_t arg1, uint32_t arg2) {
  uint64_t x1;
  uint32_t x2;
  uint32_t x3;
  x1 = ((uint64_t)arg1 * arg2);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (uint32_t)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp131_cmovznz_u32 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp131_cmovznz_u32(uint32_t* out1, fiat_fp131_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  fiat_fp131_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_fp131_int1)(0x0 - x1) & UINT32_C(0xffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_fp131_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_mul(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  fiat_fp131_uint1 x21;
  uint32_t x22;
  fiat_fp131_uint1 x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  fiat_fp131_uint1 x36;
  uint32_t x37;
  fiat_fp131_uint1 x38;
  uint32_t x39;
  fiat_fp131_uint1 x40;
  uint32_t x41;
  fiat_fp131_uint1 x42;
  uint32_t x43;
  uint32_t x44;
  fiat_fp131_uint1 x45;
  uint32_t x46;
  fiat_fp131_uint1 x47;
  uint32_t x48;
  fiat_fp131_uint1 x49;
  uint32_t x50;
  fiat_fp131_uint1 x51;
  uint32_t x52;
  fiat_fp131_uint1 x53;
  uint32_t x54;
  fiat_fp131_uint1 x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  uint32_t x64;
  uint32_t x65;
  uint32_t x66;
  fiat_fp131_uint1 x67;
  uint32_t x68;
  fiat_fp131_uint1 x69;
  uint32_t x70;
  fiat_fp131_uint1 x71;
  uint32_t x72;
  fiat_fp131_uint1 x73;
  uint32_t x74;
  uint32_t x75;
  fiat_fp131_uint1 x76;
  uint32_t x77;
  fiat_fp131_uint1 x78;
  uint32_t x79;
  fiat_fp131_uint1 x80;
  uint32_t x81;
  fiat_fp131_uint1 x82;
  uint32_t x83;
  fiat_fp131_uint1 x84;
  uint32_t x85;
  fiat_fp131_uint1 x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  fiat_fp131_uint1 x98;
  uint32_t x99;
  fiat_fp131_uint1 x100;
  uint32_t x101;
  fiat_fp131_uint1 x102;
  uint32_t x103;
  fiat_fp131_uint1 x104;
  uint32_t x105;
  uint32_t x106;
  fiat_fp131_uint1 x107;
  uint32_t x108;
  fiat_fp131_uint1 x109;
  uint32_t x110;
  fiat_fp131_uint1 x111;
  uint32_t x112;
  fiat_fp131_uint1 x113;
  uint32_t x114;
  fiat_fp131_uint1 x115;
  uint32_t x116;
  fiat_fp131_uint1 x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  uint32_t x127;
  uint32_t x128;
  uint32_t x129;
  fiat_fp131_uint1 x130;
  uint32_t x131;
  fiat_fp131_uint1 x132;
  uint32_t x133;
  fiat_fp131_uint1 x134;
  uint32_t x135;
  fiat_fp131_uint1 x136;
  uint32_t x137;
  uint32_t x138;
  fiat_fp131_uint1 x139;
  uint32_t x140;
  fiat_fp131_uint1 x141;
  uint32_t x142;
  fiat_fp131_uint1 x143;
  uint32_t x144;
  fiat_fp131_uint1 x145;
  uint32_t x146;
  fiat_fp131_uint1 x147;
  uint32_t x148;
  fiat_fp131_uint1 x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  uint32_t x156;
  uint32_t x157;
  uint32_t x158;
  uint32_t x159;
  uint32_t x160;
  fiat_fp131_uint1 x161;
  uint32_t x162;
  fiat_fp131_uint1 x163;
  uint32_t x164;
  fiat_fp131_uint1 x165;
  uint32_t x166;
  fiat_fp131_uint1 x167;
  uint32_t x168;
  uint32_t x169;
  fiat_fp131_uint1 x170;
  uint32_t x171;
  fiat_fp131_uint1 x172;
  uint32_t x173;
  fiat_fp131_uint1 x174;
  uint32_t x175;
  fiat_fp131_uint1 x176;
  uint32_t x177;
  fiat_fp131_uint1 x178;
  uint32_t x179;
  fiat_fp131_uint1 x180;
  uint32_t x181;
  uint32_t x182;
  uint32_t x183;
  uint32_t x184;
  uint32_t x185;
  uint32_t x186;
  uint32_t x187;
  uint32_t x188;
  uint32_t x189;
  uint32_t x190;
  uint32_t x191;
  uint32_t x192;
  fiat_fp131_uint1 x193;
  uint32_t x194;
  fiat_fp131_uint1 x195;
  uint32_t x196;
  fiat_fp131_uint1 x197;
  uint32_t x198;
  fiat_fp131_uint1 x199;
  uint32_t x200;
  uint32_t x201;
  fiat_fp131_uint1 x202;
  uint32_t x203;
  fiat_fp131_uint1 x204;
  uint32_t x205;
  fiat_fp131_uint1 x206;
  uint32_t x207;
  fiat_fp131_uint1 x208;
  uint32_t x209;
  fiat_fp131_uint1 x210;
  uint32_t x211;
  fiat_fp131_uint1 x212;
  uint32_t x213;
  uint32_t x214;
  uint32_t x215;
  uint32_t x216;
  uint32_t x217;
  uint32_t x218;
  uint32_t x219;
  uint32_t x220;
  uint32_t x221;
  uint32_t x222;
  uint32_t x223;
  fiat_fp131_uint1 x224;
  uint32_t x225;
  fiat_fp131_uint1 x226;
  uint32_t x227;
  fiat_fp131_uint1 x228;
  uint32_t x229;
  fiat_fp131_uint1 x230;
  uint32_t x231;
  uint32_t x232;
  fiat_fp131_uint1 x233;
  uint32_t x234;
  fiat_fp131_uint1 x235;
  uint32_t x236;
  fiat_fp131_uint1 x237;
  uint32_t x238;
  fiat_fp131_uint1 x239;
  uint32_t x240;
  fiat_fp131_uint1 x241;
  uint32_t x242;
  fiat_fp131_uint1 x243;
  uint32_t x244;
  uint32_t x245;
  uint32_t x246;
  uint32_t x247;
  uint32_t x248;
  uint32_t x249;
  uint32_t x250;
  uint32_t x251;
  uint32_t x252;
  uint32_t x253;
  uint32_t x254;
  uint32_t x255;
  fiat_fp131_uint1 x256;
  uint32_t x257;
  fiat_fp131_uint1 x258;
  uint32_t x259;
  fiat_fp131_uint1 x260;
  uint32_t x261;
  fiat_fp131_uint1 x262;
  uint32_t x263;
  uint32_t x264;
  fiat_fp131_uint1 x265;
  uint32_t x266;
  fiat_fp131_uint1 x267;
  uint32_t x268;
  fiat_fp131_uint1 x269;
  uint32_t x270;
  fiat_fp131_uint1 x271;
  uint32_t x272;
  fiat_fp131_uint1 x273;
  uint32_t x274;
  fiat_fp131_uint1 x275;
  uint32_t x276;
  uint32_t x277;
  uint32_t x278;
  uint32_t x279;
  uint32_t x280;
  uint32_t x281;
  uint32_t x282;
  uint32_t x283;
  uint32_t x284;
  uint32_t x285;
  uint32_t x286;
  fiat_fp131_uint1 x287;
  uint32_t x288;
  fiat_fp131_uint1 x289;
  uint32_t x290;
  fiat_fp131_uint1 x291;
  uint32_t x292;
  fiat_fp131_uint1 x293;
  uint32_t x294;
  uint32_t x295;
  fiat_fp131_uint1 x296;
  uint32_t x297;
  fiat_fp131_uint1 x298;
  uint32_t x299;
  fiat_fp131_uint1 x300;
  uint32_t x301;
  fiat_fp131_uint1 x302;
  uint32_t x303;
  fiat_fp131_uint1 x304;
  uint32_t x305;
  fiat_fp131_uint1 x306;
  uint32_t x307;
  uint32_t x308;
  fiat_fp131_uint1 x309;
  uint32_t x310;
  fiat_fp131_uint1 x311;
  uint32_t x312;
  fiat_fp131_uint1 x313;
  uint32_t x314;
  fiat_fp131_uint1 x315;
  uint32_t x316;
  fiat_fp131_uint1 x317;
  uint32_t x318;
  fiat_fp131_uint1 x319;
  uint32_t x320;
  uint32_t x321;
  uint32_t x322;
  uint32_t x323;
  uint32_t x324;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp131_mulx_u32(&x6, &x7, x5, (arg2[4]));
  fiat_fp131_mulx_u32(&x8, &x9, x5, (arg2[3]));
  fiat_fp131_mulx_u32(&x10, &x11, x5, (arg2[2]));
  fiat_fp131_mulx_u32(&x12, &x13, x5, (arg2[1]));
  fiat_fp131_mulx_u32(&x14, &x15, x5, (arg2[0]));
  fiat_fp131_addcarryx_u32(&x16, &x17, 0x0, x15, x12);
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x13, x10);
  fiat_fp131_addcarryx_u32(&x20, &x21, x19, x11, x8);
  fiat_fp131_addcarryx_u32(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_fp131_mulx_u32(&x25, &x26, x14, 0x6);
  fiat_fp131_mulx_u32(&x27, &x28, x14, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x29, &x30, x14, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x31, &x32, x14, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x33, &x34, x14, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x35, &x36, 0x0, x34, x31);
  fiat_fp131_addcarryx_u32(&x37, &x38, x36, x32, x29);
  fiat_fp131_addcarryx_u32(&x39, &x40, x38, x30, x27);
  fiat_fp131_addcarryx_u32(&x41, &x42, x40, x28, x25);
  x43 = (x42 + x26);
  fiat_fp131_addcarryx_u32(&x44, &x45, 0x0, x14, x33);
  fiat_fp131_addcarryx_u32(&x46, &x47, x45, x16, x35);
  fiat_fp131_addcarryx_u32(&x48, &x49, x47, x18, x37);
  fiat_fp131_addcarryx_u32(&x50, &x51, x49, x20, x39);
  fiat_fp131_addcarryx_u32(&x52, &x53, x51, x22, x41);
  fiat_fp131_addcarryx_u32(&x54, &x55, x53, x24, x43);
  fiat_fp131_mulx_u32(&x56, &x57, x1, (arg2[4]));
  fiat_fp131_mulx_u32(&x58, &x59, x1, (arg2[3]));
  fiat_fp131_mulx_u32(&x60, &x61, x1, (arg2[2]));
  fiat_fp131_mulx_u32(&x62, &x63, x1, (arg2[1]));
  fiat_fp131_mulx_u32(&x64, &x65, x1, (arg2[0]));
  fiat_fp131_addcarryx_u32(&x66, &x67, 0x0, x65, x62);
  fiat_fp131_addcarryx_u32(&x68, &x69, x67, x63, x60);
  fiat_fp131_addcarryx_u32(&x70, &x71, x69, x61, x58);
  fiat_fp131_addcarryx_u32(&x72, &x73, x71, x59, x56);
  x74 = (x73 + x57);
  fiat_fp131_addcarryx_u32(&x75, &x76, 0x0, x46, x64);
  fiat_fp131_addcarryx_u32(&x77, &x78, x76, x48, x66);
  fiat_fp131_addcarryx_u32(&x79, &x80, x78, x50, x68);
  fiat_fp131_addcarryx_u32(&x81, &x82, x80, x52, x70);
  fiat_fp131_addcarryx_u32(&x83, &x84, x82, x54, x72);
  fiat_fp131_addcarryx_u32(&x85, &x86, x84, x55, x74);
  fiat_fp131_mulx_u32(&x87, &x88, x75, 0x6);
  fiat_fp131_mulx_u32(&x89, &x90, x75, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x91, &x92, x75, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x93, &x94, x75, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x95, &x96, x75, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x97, &x98, 0x0, x96, x93);
  fiat_fp131_addcarryx_u32(&x99, &x100, x98, x94, x91);
  fiat_fp131_addcarryx_u32(&x101, &x102, x100, x92, x89);
  fiat_fp131_addcarryx_u32(&x103, &x104, x102, x90, x87);
  x105 = (x104 + x88);
  fiat_fp131_addcarryx_u32(&x106, &x107, 0x0, x75, x95);
  fiat_fp131_addcarryx_u32(&x108, &x109, x107, x77, x97);
  fiat_fp131_addcarryx_u32(&x110, &x111, x109, x79, x99);
  fiat_fp131_addcarryx_u32(&x112, &x113, x111, x81, x101);
  fiat_fp131_addcarryx_u32(&x114, &x115, x113, x83, x103);
  fiat_fp131_addcarryx_u32(&x116, &x117, x115, x85, x105);
  x118 = ((uint32_t)x117 + x86);
  fiat_fp131_mulx_u32(&x119, &x120, x2, (arg2[4]));
  fiat_fp131_mulx_u32(&x121, &x122, x2, (arg2[3]));
  fiat_fp131_mulx_u32(&x123, &x124, x2, (arg2[2]));
  fiat_fp131_mulx_u32(&x125, &x126, x2, (arg2[1]));
  fiat_fp131_mulx_u32(&x127, &x128, x2, (arg2[0]));
  fiat_fp131_addcarryx_u32(&x129, &x130, 0x0, x128, x125);
  fiat_fp131_addcarryx_u32(&x131, &x132, x130, x126, x123);
  fiat_fp131_addcarryx_u32(&x133, &x134, x132, x124, x121);
  fiat_fp131_addcarryx_u32(&x135, &x136, x134, x122, x119);
  x137 = (x136 + x120);
  fiat_fp131_addcarryx_u32(&x138, &x139, 0x0, x108, x127);
  fiat_fp131_addcarryx_u32(&x140, &x141, x139, x110, x129);
  fiat_fp131_addcarryx_u32(&x142, &x143, x141, x112, x131);
  fiat_fp131_addcarryx_u32(&x144, &x145, x143, x114, x133);
  fiat_fp131_addcarryx_u32(&x146, &x147, x145, x116, x135);
  fiat_fp131_addcarryx_u32(&x148, &x149, x147, x118, x137);
  fiat_fp131_mulx_u32(&x150, &x151, x138, 0x6);
  fiat_fp131_mulx_u32(&x152, &x153, x138, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x154, &x155, x138, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x156, &x157, x138, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x158, &x159, x138, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x160, &x161, 0x0, x159, x156);
  fiat_fp131_addcarryx_u32(&x162, &x163, x161, x157, x154);
  fiat_fp131_addcarryx_u32(&x164, &x165, x163, x155, x152);
  fiat_fp131_addcarryx_u32(&x166, &x167, x165, x153, x150);
  x168 = (x167 + x151);
  fiat_fp131_addcarryx_u32(&x169, &x170, 0x0, x138, x158);
  fiat_fp131_addcarryx_u32(&x171, &x172, x170, x140, x160);
  fiat_fp131_addcarryx_u32(&x173, &x174, x172, x142, x162);
  fiat_fp131_addcarryx_u32(&x175, &x176, x174, x144, x164);
  fiat_fp131_addcarryx_u32(&x177, &x178, x176, x146, x166);
  fiat_fp131_addcarryx_u32(&x179, &x180, x178, x148, x168);
  x181 = ((uint32_t)x180 + x149);
  fiat_fp131_mulx_u32(&x182, &x183, x3, (arg2[4]));
  fiat_fp131_mulx_u32(&x184, &x185, x3, (arg2[3]));
  fiat_fp131_mulx_u32(&x186, &x187, x3, (arg2[2]));
  fiat_fp131_mulx_u32(&x188, &x189, x3, (arg2[1]));
  fiat_fp131_mulx_u32(&x190, &x191, x3, (arg2[0]));
  fiat_fp131_addcarryx_u32(&x192, &x193, 0x0, x191, x188);
  fiat_fp131_addcarryx_u32(&x194, &x195, x193, x189, x186);
  fiat_fp131_addcarryx_u32(&x196, &x197, x195, x187, x184);
  fiat_fp131_addcarryx_u32(&x198, &x199, x197, x185, x182);
  x200 = (x199 + x183);
  fiat_fp131_addcarryx_u32(&x201, &x202, 0x0, x171, x190);
  fiat_fp131_addcarryx_u32(&x203, &x204, x202, x173, x192);
  fiat_fp131_addcarryx_u32(&x205, &x206, x204, x175, x194);
  fiat_fp131_addcarryx_u32(&x207, &x208, x206, x177, x196);
  fiat_fp131_addcarryx_u32(&x209, &x210, x208, x179, x198);
  fiat_fp131_addcarryx_u32(&x211, &x212, x210, x181, x200);
  fiat_fp131_mulx_u32(&x213, &x214, x201, 0x6);
  fiat_fp131_mulx_u32(&x215, &x216, x201, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x217, &x218, x201, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x219, &x220, x201, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x221, &x222, x201, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x223, &x224, 0x0, x222, x219);
  fiat_fp131_addcarryx_u32(&x225, &x226, x224, x220, x217);
  fiat_fp131_addcarryx_u32(&x227, &x228, x226, x218, x215);
  fiat_fp131_addcarryx_u32(&x229, &x230, x228, x216, x213);
  x231 = (x230 + x214);
  fiat_fp131_addcarryx_u32(&x232, &x233, 0x0, x201, x221);
  fiat_fp131_addcarryx_u32(&x234, &x235, x233, x203, x223);
  fiat_fp131_addcarryx_u32(&x236, &x237, x235, x205, x225);
  fiat_fp131_addcarryx_u32(&x238, &x239, x237, x207, x227);
  fiat_fp131_addcarryx_u32(&x240, &x241, x239, x209, x229);
  fiat_fp131_addcarryx_u32(&x242, &x243, x241, x211, x231);
  x244 = ((uint32_t)x243 + x212);
  fiat_fp131_mulx_u32(&x245, &x246, x4, (arg2[4]));
  fiat_fp131_mulx_u32(&x247, &x248, x4, (arg2[3]));
  fiat_fp131_mulx_u32(&x249, &x250, x4, (arg2[2]));
  fiat_fp131_mulx_u32(&x251, &x252, x4, (arg2[1]));
  fiat_fp131_mulx_u32(&x253, &x254, x4, (arg2[0]));
  fiat_fp131_addcarryx_u32(&x255, &x256, 0x0, x254, x251);
  fiat_fp131_addcarryx_u32(&x257, &x258, x256, x252, x249);
  fiat_fp131_addcarryx_u32(&x259, &x260, x258, x250, x247);
  fiat_fp131_addcarryx_u32(&x261, &x262, x260, x248, x245);
  x263 = (x262 + x246);
  fiat_fp131_addcarryx_u32(&x264, &x265, 0x0, x234, x253);
  fiat_fp131_addcarryx_u32(&x266, &x267, x265, x236, x255);
  fiat_fp131_addcarryx_u32(&x268, &x269, x267, x238, x257);
  fiat_fp131_addcarryx_u32(&x270, &x271, x269, x240, x259);
  fiat_fp131_addcarryx_u32(&x272, &x273, x271, x242, x261);
  fiat_fp131_addcarryx_u32(&x274, &x275, x273, x244, x263);
  fiat_fp131_mulx_u32(&x276, &x277, x264, 0x6);
  fiat_fp131_mulx_u32(&x278, &x279, x264, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x280, &x281, x264, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x282, &x283, x264, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x284, &x285, x264, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x286, &x287, 0x0, x285, x282);
  fiat_fp131_addcarryx_u32(&x288, &x289, x287, x283, x280);
  fiat_fp131_addcarryx_u32(&x290, &x291, x289, x281, x278);
  fiat_fp131_addcarryx_u32(&x292, &x293, x291, x279, x276);
  x294 = (x293 + x277);
  fiat_fp131_addcarryx_u32(&x295, &x296, 0x0, x264, x284);
  fiat_fp131_addcarryx_u32(&x297, &x298, x296, x266, x286);
  fiat_fp131_addcarryx_u32(&x299, &x300, x298, x268, x288);
  fiat_fp131_addcarryx_u32(&x301, &x302, x300, x270, x290);
  fiat_fp131_addcarryx_u32(&x303, &x304, x302, x272, x292);
  fiat_fp131_addcarryx_u32(&x305, &x306, x304, x274, x294);
  x307 = ((uint32_t)x306 + x275);
  fiat_fp131_subborrowx_u32(&x308, &x309, 0x0, x297, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x310, &x311, x309, x299, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x312, &x313, x311, x301, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x314, &x315, x313, x303, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x316, &x317, x315, x305, 0x6);
  fiat_fp131_subborrowx_u32(&x318, &x319, x317, x307, 0x0);
  fiat_fp131_cmovznz_u32(&x320, x319, x308, x297);
  fiat_fp131_cmovznz_u32(&x321, x319, x310, x299);
  fiat_fp131_cmovznz_u32(&x322, x319, x312, x301);
  fiat_fp131_cmovznz_u32(&x323, x319, x314, x303);
  fiat_fp131_cmovznz_u32(&x324, x319, x316, x305);
  out1[0] = x320;
  out1[1] = x321;
  out1[2] = x322;
  out1[3] = x323;
  out1[4] = x324;
}

/*
 * The function fiat_fp131_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_square(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  fiat_fp131_uint1 x21;
  uint32_t x22;
  fiat_fp131_uint1 x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  fiat_fp131_uint1 x36;
  uint32_t x37;
  fiat_fp131_uint1 x38;
  uint32_t x39;
  fiat_fp131_uint1 x40;
  uint32_t x41;
  fiat_fp131_uint1 x42;
  uint32_t x43;
  uint32_t x44;
  fiat_fp131_uint1 x45;
  uint32_t x46;
  fiat_fp131_uint1 x47;
  uint32_t x48;
  fiat_fp131_uint1 x49;
  uint32_t x50;
  fiat_fp131_uint1 x51;
  uint32_t x52;
  fiat_fp131_uint1 x53;
  uint32_t x54;
  fiat_fp131_uint1 x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  uint32_t x64;
  uint32_t x65;
  uint32_t x66;
  fiat_fp131_uint1 x67;
  uint32_t x68;
  fiat_fp131_uint1 x69;
  uint32_t x70;
  fiat_fp131_uint1 x71;
  uint32_t x72;
  fiat_fp131_uint1 x73;
  uint32_t x74;
  uint32_t x75;
  fiat_fp131_uint1 x76;
  uint32_t x77;
  fiat_fp131_uint1 x78;
  uint32_t x79;
  fiat_fp131_uint1 x80;
  uint32_t x81;
  fiat_fp131_uint1 x82;
  uint32_t x83;
  fiat_fp131_uint1 x84;
  uint32_t x85;
  fiat_fp131_uint1 x86;
  uint32_t x87;
  uint32_t x88;
  uint32_t x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  fiat_fp131_uint1 x98;
  uint32_t x99;
  fiat_fp131_uint1 x100;
  uint32_t x101;
  fiat_fp131_uint1 x102;
  uint32_t x103;
  fiat_fp131_uint1 x104;
  uint32_t x105;
  uint32_t x106;
  fiat_fp131_uint1 x107;
  uint32_t x108;
  fiat_fp131_uint1 x109;
  uint32_t x110;
  fiat_fp131_uint1 x111;
  uint32_t x112;
  fiat_fp131_uint1 x113;
  uint32_t x114;
  fiat_fp131_uint1 x115;
  uint32_t x116;
  fiat_fp131_uint1 x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  uint32_t x127;
  uint32_t x128;
  uint32_t x129;
  fiat_fp131_uint1 x130;
  uint32_t x131;
  fiat_fp131_uint1 x132;
  uint32_t x133;
  fiat_fp131_uint1 x134;
  uint32_t x135;
  fiat_fp131_uint1 x136;
  uint32_t x137;
  uint32_t x138;
  fiat_fp131_uint1 x139;
  uint32_t x140;
  fiat_fp131_uint1 x141;
  uint32_t x142;
  fiat_fp131_uint1 x143;
  uint32_t x144;
  fiat_fp131_uint1 x145;
  uint32_t x146;
  fiat_fp131_uint1 x147;
  uint32_t x148;
  fiat_fp131_uint1 x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  uint32_t x156;
  uint32_t x157;
  uint32_t x158;
  uint32_t x159;
  uint32_t x160;
  fiat_fp131_uint1 x161;
  uint32_t x162;
  fiat_fp131_uint1 x163;
  uint32_t x164;
  fiat_fp131_uint1 x165;
  uint32_t x166;
  fiat_fp131_uint1 x167;
  uint32_t x168;
  uint32_t x169;
  fiat_fp131_uint1 x170;
  uint32_t x171;
  fiat_fp131_uint1 x172;
  uint32_t x173;
  fiat_fp131_uint1 x174;
  uint32_t x175;
  fiat_fp131_uint1 x176;
  uint32_t x177;
  fiat_fp131_uint1 x178;
  uint32_t x179;
  fiat_fp131_uint1 x180;
  uint32_t x181;
  uint32_t x182;
  uint32_t x183;
  uint32_t x184;
  uint32_t x185;
  uint32_t x186;
  uint32_t x187;
  uint32_t x188;
  uint32_t x189;
  uint32_t x190;
  uint32_t x191;
  uint32_t x192;
  fiat_fp131_uint1 x193;
  uint32_t x194;
  fiat_fp131_uint1 x195;
  uint32_t x196;
  fiat_fp131_uint1 x197;
  uint32_t x198;
  fiat_fp131_uint1 x199;
  uint32_t x200;
  uint32_t x201;
  fiat_fp131_uint1 x202;
  uint32_t x203;
  fiat_fp131_uint1 x204;
  uint32_t x205;
  fiat_fp131_uint1 x206;
  uint32_t x207;
  fiat_fp131_uint1 x208;
  uint32_t x209;
  fiat_fp131_uint1 x210;
  uint32_t x211;
  fiat_fp131_uint1 x212;
  uint32_t x213;
  uint32_t x214;
  uint32_t x215;
  uint32_t x216;
  uint32_t x217;
  uint32_t x218;
  uint32_t x219;
  uint32_t x220;
  uint32_t x221;
  uint32_t x222;
  uint32_t x223;
  fiat_fp131_uint1 x224;
  uint32_t x225;
  fiat_fp131_uint1 x226;
  uint32_t x227;
  fiat_fp131_uint1 x228;
  uint32_t x229;
  fiat_fp131_uint1 x230;
  uint32_t x231;
  uint32_t x232;
  fiat_fp131_uint1 x233;
  uint32_t x234;
  fiat_fp131_uint1 x235;
  uint32_t x236;
  fiat_fp131_uint1 x237;
  uint32_t x238;
  fiat_fp131_uint1 x239;
  uint32_t x240;
  fiat_fp131_uint1 x241;
  uint32_t x242;
  fiat_fp131_uint1 x243;
  uint32_t x244;
  uint32_t x245;
  uint32_t x246;
  uint32_t x247;
  uint32_t x248;
  uint32_t x249;
  uint32_t x250;
  uint32_t x251;
  uint32_t x252;
  uint32_t x253;
  uint32_t x254;
  uint32_t x255;
  fiat_fp131_uint1 x256;
  uint32_t x257;
  fiat_fp131_uint1 x258;
  uint32_t x259;
  fiat_fp131_uint1 x260;
  uint32_t x261;
  fiat_fp131_uint1 x262;
  uint32_t x263;
  uint32_t x264;
  fiat_fp131_uint1 x265;
  uint32_t x266;
  fiat_fp131_uint1 x267;
  uint32_t x268;
  fiat_fp131_uint1 x269;
  uint32_t x270;
  fiat_fp131_uint1 x271;
  uint32_t x272;
  fiat_fp131_uint1 x273;
  uint32_t x274;
  fiat_fp131_uint1 x275;
  uint32_t x276;
  uint32_t x277;
  uint32_t x278;
  uint32_t x279;
  uint32_t x280;
  uint32_t x281;
  uint32_t x282;
  uint32_t x283;
  uint32_t x284;
  uint32_t x285;
  uint32_t x286;
  fiat_fp131_uint1 x287;
  uint32_t x288;
  fiat_fp131_uint1 x289;
  uint32_t x290;
  fiat_fp131_uint1 x291;
  uint32_t x292;
  fiat_fp131_uint1 x293;
  uint32_t x294;
  uint32_t x295;
  fiat_fp131_uint1 x296;
  uint32_t x297;
  fiat_fp131_uint1 x298;
  uint32_t x299;
  fiat_fp131_uint1 x300;
  uint32_t x301;
  fiat_fp131_uint1 x302;
  uint32_t x303;
  fiat_fp131_uint1 x304;
  uint32_t x305;
  fiat_fp131_uint1 x306;
  uint32_t x307;
  uint32_t x308;
  fiat_fp131_uint1 x309;
  uint32_t x310;
  fiat_fp131_uint1 x311;
  uint32_t x312;
  fiat_fp131_uint1 x313;
  uint32_t x314;
  fiat_fp131_uint1 x315;
  uint32_t x316;
  fiat_fp131_uint1 x317;
  uint32_t x318;
  fiat_fp131_uint1 x319;
  uint32_t x320;
  uint32_t x321;
  uint32_t x322;
  uint32_t x323;
  uint32_t x324;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp131_mulx_u32(&x6, &x7, x5, (arg1[4]));
  fiat_fp131_mulx_u32(&x8, &x9, x5, (arg1[3]));
  fiat_fp131_mulx_u32(&x10, &x11, x5, (arg1[2]));
  fiat_fp131_mulx_u32(&x12, &x13, x5, (arg1[1]));
  fiat_fp131_mulx_u32(&x14, &x15, x5, (arg1[0]));
  fiat_fp131_addcarryx_u32(&x16, &x17, 0x0, x15, x12);
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x13, x10);
  fiat_fp131_addcarryx_u32(&x20, &x21, x19, x11, x8);
  fiat_fp131_addcarryx_u32(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_fp131_mulx_u32(&x25, &x26, x14, 0x6);
  fiat_fp131_mulx_u32(&x27, &x28, x14, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x29, &x30, x14, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x31, &x32, x14, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x33, &x34, x14, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x35, &x36, 0x0, x34, x31);
  fiat_fp131_addcarryx_u32(&x37, &x38, x36, x32, x29);
  fiat_fp131_addcarryx_u32(&x39, &x40, x38, x30, x27);
  fiat_fp131_addcarryx_u32(&x41, &x42, x40, x28, x25);
  x43 = (x42 + x26);
  fiat_fp131_addcarryx_u32(&x44, &x45, 0x0, x14, x33);
  fiat_fp131_addcarryx_u32(&x46, &x47, x45, x16, x35);
  fiat_fp131_addcarryx_u32(&x48, &x49, x47, x18, x37);
  fiat_fp131_addcarryx_u32(&x50, &x51, x49, x20, x39);
  fiat_fp131_addcarryx_u32(&x52, &x53, x51, x22, x41);
  fiat_fp131_addcarryx_u32(&x54, &x55, x53, x24, x43);
  fiat_fp131_mulx_u32(&x56, &x57, x1, (arg1[4]));
  fiat_fp131_mulx_u32(&x58, &x59, x1, (arg1[3]));
  fiat_fp131_mulx_u32(&x60, &x61, x1, (arg1[2]));
  fiat_fp131_mulx_u32(&x62, &x63, x1, (arg1[1]));
  fiat_fp131_mulx_u32(&x64, &x65, x1, (arg1[0]));
  fiat_fp131_addcarryx_u32(&x66, &x67, 0x0, x65, x62);
  fiat_fp131_addcarryx_u32(&x68, &x69, x67, x63, x60);
  fiat_fp131_addcarryx_u32(&x70, &x71, x69, x61, x58);
  fiat_fp131_addcarryx_u32(&x72, &x73, x71, x59, x56);
  x74 = (x73 + x57);
  fiat_fp131_addcarryx_u32(&x75, &x76, 0x0, x46, x64);
  fiat_fp131_addcarryx_u32(&x77, &x78, x76, x48, x66);
  fiat_fp131_addcarryx_u32(&x79, &x80, x78, x50, x68);
  fiat_fp131_addcarryx_u32(&x81, &x82, x80, x52, x70);
  fiat_fp131_addcarryx_u32(&x83, &x84, x82, x54, x72);
  fiat_fp131_addcarryx_u32(&x85, &x86, x84, x55, x74);
  fiat_fp131_mulx_u32(&x87, &x88, x75, 0x6);
  fiat_fp131_mulx_u32(&x89, &x90, x75, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x91, &x92, x75, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x93, &x94, x75, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x95, &x96, x75, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x97, &x98, 0x0, x96, x93);
  fiat_fp131_addcarryx_u32(&x99, &x100, x98, x94, x91);
  fiat_fp131_addcarryx_u32(&x101, &x102, x100, x92, x89);
  fiat_fp131_addcarryx_u32(&x103, &x104, x102, x90, x87);
  x105 = (x104 + x88);
  fiat_fp131_addcarryx_u32(&x106, &x107, 0x0, x75, x95);
  fiat_fp131_addcarryx_u32(&x108, &x109, x107, x77, x97);
  fiat_fp131_addcarryx_u32(&x110, &x111, x109, x79, x99);
  fiat_fp131_addcarryx_u32(&x112, &x113, x111, x81, x101);
  fiat_fp131_addcarryx_u32(&x114, &x115, x113, x83, x103);
  fiat_fp131_addcarryx_u32(&x116, &x117, x115, x85, x105);
  x118 = ((uint32_t)x117 + x86);
  fiat_fp131_mulx_u32(&x119, &x120, x2, (arg1[4]));
  fiat_fp131_mulx_u32(&x121, &x122, x2, (arg1[3]));
  fiat_fp131_mulx_u32(&x123, &x124, x2, (arg1[2]));
  fiat_fp131_mulx_u32(&x125, &x126, x2, (arg1[1]));
  fiat_fp131_mulx_u32(&x127, &x128, x2, (arg1[0]));
  fiat_fp131_addcarryx_u32(&x129, &x130, 0x0, x128, x125);
  fiat_fp131_addcarryx_u32(&x131, &x132, x130, x126, x123);
  fiat_fp131_addcarryx_u32(&x133, &x134, x132, x124, x121);
  fiat_fp131_addcarryx_u32(&x135, &x136, x134, x122, x119);
  x137 = (x136 + x120);
  fiat_fp131_addcarryx_u32(&x138, &x139, 0x0, x108, x127);
  fiat_fp131_addcarryx_u32(&x140, &x141, x139, x110, x129);
  fiat_fp131_addcarryx_u32(&x142, &x143, x141, x112, x131);
  fiat_fp131_addcarryx_u32(&x144, &x145, x143, x114, x133);
  fiat_fp131_addcarryx_u32(&x146, &x147, x145, x116, x135);
  fiat_fp131_addcarryx_u32(&x148, &x149, x147, x118, x137);
  fiat_fp131_mulx_u32(&x150, &x151, x138, 0x6);
  fiat_fp131_mulx_u32(&x152, &x153, x138, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x154, &x155, x138, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x156, &x157, x138, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x158, &x159, x138, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x160, &x161, 0x0, x159, x156);
  fiat_fp131_addcarryx_u32(&x162, &x163, x161, x157, x154);
  fiat_fp131_addcarryx_u32(&x164, &x165, x163, x155, x152);
  fiat_fp131_addcarryx_u32(&x166, &x167, x165, x153, x150);
  x168 = (x167 + x151);
  fiat_fp131_addcarryx_u32(&x169, &x170, 0x0, x138, x158);
  fiat_fp131_addcarryx_u32(&x171, &x172, x170, x140, x160);
  fiat_fp131_addcarryx_u32(&x173, &x174, x172, x142, x162);
  fiat_fp131_addcarryx_u32(&x175, &x176, x174, x144, x164);
  fiat_fp131_addcarryx_u32(&x177, &x178, x176, x146, x166);
  fiat_fp131_addcarryx_u32(&x179, &x180, x178, x148, x168);
  x181 = ((uint32_t)x180 + x149);
  fiat_fp131_mulx_u32(&x182, &x183, x3, (arg1[4]));
  fiat_fp131_mulx_u32(&x184, &x185, x3, (arg1[3]));
  fiat_fp131_mulx_u32(&x186, &x187, x3, (arg1[2]));
  fiat_fp131_mulx_u32(&x188, &x189, x3, (arg1[1]));
  fiat_fp131_mulx_u32(&x190, &x191, x3, (arg1[0]));
  fiat_fp131_addcarryx_u32(&x192, &x193, 0x0, x191, x188);
  fiat_fp131_addcarryx_u32(&x194, &x195, x193, x189, x186);
  fiat_fp131_addcarryx_u32(&x196, &x197, x195, x187, x184);
  fiat_fp131_addcarryx_u32(&x198, &x199, x197, x185, x182);
  x200 = (x199 + x183);
  fiat_fp131_addcarryx_u32(&x201, &x202, 0x0, x171, x190);
  fiat_fp131_addcarryx_u32(&x203, &x204, x202, x173, x192);
  fiat_fp131_addcarryx_u32(&x205, &x206, x204, x175, x194);
  fiat_fp131_addcarryx_u32(&x207, &x208, x206, x177, x196);
  fiat_fp131_addcarryx_u32(&x209, &x210, x208, x179, x198);
  fiat_fp131_addcarryx_u32(&x211, &x212, x210, x181, x200);
  fiat_fp131_mulx_u32(&x213, &x214, x201, 0x6);
  fiat_fp131_mulx_u32(&x215, &x216, x201, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x217, &x218, x201, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x219, &x220, x201, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x221, &x222, x201, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x223, &x224, 0x0, x222, x219);
  fiat_fp131_addcarryx_u32(&x225, &x226, x224, x220, x217);
  fiat_fp131_addcarryx_u32(&x227, &x228, x226, x218, x215);
  fiat_fp131_addcarryx_u32(&x229, &x230, x228, x216, x213);
  x231 = (x230 + x214);
  fiat_fp131_addcarryx_u32(&x232, &x233, 0x0, x201, x221);
  fiat_fp131_addcarryx_u32(&x234, &x235, x233, x203, x223);
  fiat_fp131_addcarryx_u32(&x236, &x237, x235, x205, x225);
  fiat_fp131_addcarryx_u32(&x238, &x239, x237, x207, x227);
  fiat_fp131_addcarryx_u32(&x240, &x241, x239, x209, x229);
  fiat_fp131_addcarryx_u32(&x242, &x243, x241, x211, x231);
  x244 = ((uint32_t)x243 + x212);
  fiat_fp131_mulx_u32(&x245, &x246, x4, (arg1[4]));
  fiat_fp131_mulx_u32(&x247, &x248, x4, (arg1[3]));
  fiat_fp131_mulx_u32(&x249, &x250, x4, (arg1[2]));
  fiat_fp131_mulx_u32(&x251, &x252, x4, (arg1[1]));
  fiat_fp131_mulx_u32(&x253, &x254, x4, (arg1[0]));
  fiat_fp131_addcarryx_u32(&x255, &x256, 0x0, x254, x251);
  fiat_fp131_addcarryx_u32(&x257, &x258, x256, x252, x249);
  fiat_fp131_addcarryx_u32(&x259, &x260, x258, x250, x247);
  fiat_fp131_addcarryx_u32(&x261, &x262, x260, x248, x245);
  x263 = (x262 + x246);
  fiat_fp131_addcarryx_u32(&x264, &x265, 0x0, x234, x253);
  fiat_fp131_addcarryx_u32(&x266, &x267, x265, x236, x255);
  fiat_fp131_addcarryx_u32(&x268, &x269, x267, x238, x257);
  fiat_fp131_addcarryx_u32(&x270, &x271, x269, x240, x259);
  fiat_fp131_addcarryx_u32(&x272, &x273, x271, x242, x261);
  fiat_fp131_addcarryx_u32(&x274, &x275, x273, x244, x263);
  fiat_fp131_mulx_u32(&x276, &x277, x264, 0x6);
  fiat_fp131_mulx_u32(&x278, &x279, x264, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x280, &x281, x264, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x282, &x283, x264, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x284, &x285, x264, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x286, &x287, 0x0, x285, x282);
  fiat_fp131_addcarryx_u32(&x288, &x289, x287, x283, x280);
  fiat_fp131_addcarryx_u32(&x290, &x291, x289, x281, x278);
  fiat_fp131_addcarryx_u32(&x292, &x293, x291, x279, x276);
  x294 = (x293 + x277);
  fiat_fp131_addcarryx_u32(&x295, &x296, 0x0, x264, x284);
  fiat_fp131_addcarryx_u32(&x297, &x298, x296, x266, x286);
  fiat_fp131_addcarryx_u32(&x299, &x300, x298, x268, x288);
  fiat_fp131_addcarryx_u32(&x301, &x302, x300, x270, x290);
  fiat_fp131_addcarryx_u32(&x303, &x304, x302, x272, x292);
  fiat_fp131_addcarryx_u32(&x305, &x306, x304, x274, x294);
  x307 = ((uint32_t)x306 + x275);
  fiat_fp131_subborrowx_u32(&x308, &x309, 0x0, x297, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x310, &x311, x309, x299, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x312, &x313, x311, x301, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x314, &x315, x313, x303, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x316, &x317, x315, x305, 0x6);
  fiat_fp131_subborrowx_u32(&x318, &x319, x317, x307, 0x0);
  fiat_fp131_cmovznz_u32(&x320, x319, x308, x297);
  fiat_fp131_cmovznz_u32(&x321, x319, x310, x299);
  fiat_fp131_cmovznz_u32(&x322, x319, x312, x301);
  fiat_fp131_cmovznz_u32(&x323, x319, x314, x303);
  fiat_fp131_cmovznz_u32(&x324, x319, x316, x305);
  out1[0] = x320;
  out1[1] = x321;
  out1[2] = x322;
  out1[3] = x323;
  out1[4] = x324;
}

/*
 * The function fiat_fp131_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_add(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp131_uint1 x2;
  uint32_t x3;
  fiat_fp131_uint1 x4;
  uint32_t x5;
  fiat_fp131_uint1 x6;
  uint32_t x7;
  fiat_fp131_uint1 x8;
  uint32_t x9;
  fiat_fp131_uint1 x10;
  uint32_t x11;
  fiat_fp131_uint1 x12;
  uint32_t x13;
  fiat_fp131_uint1 x14;
  uint32_t x15;
  fiat_fp131_uint1 x16;
  uint32_t x17;
  fiat_fp131_uint1 x18;
  uint32_t x19;
  fiat_fp131_uint1 x20;
  uint32_t x21;
  fiat_fp131_uint1 x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  fiat_fp131_addcarryx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp131_addcarryx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp131_addcarryx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp131_addcarryx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp131_addcarryx_u32(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_fp131_subborrowx_u32(&x11, &x12, 0x0, x1, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x13, &x14, x12, x3, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x15, &x16, x14, x5, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x17, &x18, x16, x7, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x19, &x20, x18, x9, 0x6);
  fiat_fp131_subborrowx_u32(&x21, &x22, x20, x10, 0x0);
  fiat_fp131_cmovznz_u32(&x23, x22, x11, x1);
  fiat_fp131_cmovznz_u32(&x24, x22, x13, x3);
  fiat_fp131_cmovznz_u32(&x25, x22, x15, x5);
  fiat_fp131_cmovznz_u32(&x26, x22, x17, x7);
  fiat_fp131_cmovznz_u32(&x27, x22, x19, x9);
  out1[0] = x23;
  out1[1] = x24;
  out1[2] = x25;
  out1[3] = x26;
  out1[4] = x27;
}

/*
 * The function fiat_fp131_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_sub(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1, const fiat_fp131_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp131_uint1 x2;
  uint32_t x3;
  fiat_fp131_uint1 x4;
  uint32_t x5;
  fiat_fp131_uint1 x6;
  uint32_t x7;
  fiat_fp131_uint1 x8;
  uint32_t x9;
  fiat_fp131_uint1 x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp131_uint1 x13;
  uint32_t x14;
  fiat_fp131_uint1 x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  fiat_fp131_uint1 x21;
  fiat_fp131_subborrowx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp131_subborrowx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp131_subborrowx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp131_subborrowx_u32(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_fp131_subborrowx_u32(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_fp131_cmovznz_u32(&x11, x10, 0x0, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x12, &x13, 0x0, x1, x11);
  fiat_fp131_addcarryx_u32(&x14, &x15, x13, x3, x11);
  fiat_fp131_addcarryx_u32(&x16, &x17, x15, x5, (x11 & UINT32_C(0x129f1e8c)));
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x7, (x11 & UINT32_C(0x397b18cf)));
  fiat_fp131_addcarryx_u32(&x20, &x21, x19, x9, (x11 & 0x6));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_fp131_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_opp(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint32_t x1;
  fiat_fp131_uint1 x2;
  uint32_t x3;
  fiat_fp131_uint1 x4;
  uint32_t x5;
  fiat_fp131_uint1 x6;
  uint32_t x7;
  fiat_fp131_uint1 x8;
  uint32_t x9;
  fiat_fp131_uint1 x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp131_uint1 x13;
  uint32_t x14;
  fiat_fp131_uint1 x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  fiat_fp131_uint1 x21;
  fiat_fp131_subborrowx_u32(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_fp131_subborrowx_u32(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_fp131_subborrowx_u32(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_fp131_subborrowx_u32(&x7, &x8, x6, 0x0, (arg1[3]));
  fiat_fp131_subborrowx_u32(&x9, &x10, x8, 0x0, (arg1[4]));
  fiat_fp131_cmovznz_u32(&x11, x10, 0x0, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x12, &x13, 0x0, x1, x11);
  fiat_fp131_addcarryx_u32(&x14, &x15, x13, x3, x11);
  fiat_fp131_addcarryx_u32(&x16, &x17, x15, x5, (x11 & UINT32_C(0x129f1e8c)));
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x7, (x11 & UINT32_C(0x397b18cf)));
  fiat_fp131_addcarryx_u32(&x20, &x21, x19, x9, (x11 & 0x6));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_fp131_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^32)⁻¹ mod m)^5) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_from_montgomery(fiat_fp131_non_montgomery_domain_field_element out1, const fiat_fp131_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  fiat_fp131_uint1 x13;
  uint32_t x14;
  fiat_fp131_uint1 x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  fiat_fp131_uint1 x21;
  uint32_t x22;
  fiat_fp131_uint1 x23;
  uint32_t x24;
  fiat_fp131_uint1 x25;
  uint32_t x26;
  fiat_fp131_uint1 x27;
  uint32_t x28;
  fiat_fp131_uint1 x29;
  uint32_t x30;
  fiat_fp131_uint1 x31;
  uint32_t x32;
  fiat_fp131_uint1 x33;
  uint32_t x34;
  fiat_fp131_uint1 x35;
  uint32_t x36;
  fiat_fp131_uint1 x37;
  uint32_t x38;
  uint32_t x39;
  uint32_t x40;
  uint32_t x41;
  uint32_t x42;
  uint32_t x43;
  uint32_t x44;
  uint32_t x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  fiat_fp131_uint1 x49;
  uint32_t x50;
  fiat_fp131_uint1 x51;
  uint32_t x52;
  fiat_fp131_uint1 x53;
  uint32_t x54;
  fiat_fp131_uint1 x55;
  uint32_t x56;
  fiat_fp131_uint1 x57;
  uint32_t x58;
  fiat_fp131_uint1 x59;
  uint32_t x60;
  fiat_fp131_uint1 x61;
  uint32_t x62;
  fiat_fp131_uint1 x63;
  uint32_t x64;
  fiat_fp131_uint1 x65;
  uint32_t x66;
  fiat_fp131_uint1 x67;
  uint32_t x68;
  fiat_fp131_uint1 x69;
  uint32_t x70;
  fiat_fp131_uint1 x71;
  uint32_t x72;
  fiat_fp131_uint1 x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  uint32_t x79;
  uint32_t x80;
  uint32_t x81;
  uint32_t x82;
  uint32_t x83;
  uint32_t x84;
  fiat_fp131_uint1 x85;
  uint32_t x86;
  fiat_fp131_uint1 x87;
  uint32_t x88;
  fiat_fp131_uint1 x89;
  uint32_t x90;
  fiat_fp131_uint1 x91;
  uint32_t x92;
  fiat_fp131_uint1 x93;
  uint32_t x94;
  fiat_fp131_uint1 x95;
  uint32_t x96;
  fiat_fp131_uint1 x97;
  uint32_t x98;
  fiat_fp131_uint1 x99;
  uint32_t x100;
  fiat_fp131_uint1 x101;
  uint32_t x102;
  fiat_fp131_uint1 x103;
  uint32_t x104;
  fiat_fp131_uint1 x105;
  uint32_t x106;
  fiat_fp131_uint1 x107;
  uint32_t x108;
  fiat_fp131_uint1 x109;
  uint32_t x110;
  uint32_t x111;
  uint32_t x112;
  uint32_t x113;
  uint32_t x114;
  uint32_t x115;
  uint32_t x116;
  uint32_t x117;
  uint32_t x118;
  uint32_t x119;
  uint32_t x120;
  fiat_fp131_uint1 x121;
  uint32_t x122;
  fiat_fp131_uint1 x123;
  uint32_t x124;
  fiat_fp131_uint1 x125;
  uint32_t x126;
  fiat_fp131_uint1 x127;
  uint32_t x128;
  fiat_fp131_uint1 x129;
  uint32_t x130;
  fiat_fp131_uint1 x131;
  uint32_t x132;
  fiat_fp131_uint1 x133;
  uint32_t x134;
  fiat_fp131_uint1 x135;
  uint32_t x136;
  fiat_fp131_uint1 x137;
  uint32_t x138;
  fiat_fp131_uint1 x139;
  uint32_t x140;
  fiat_fp131_uint1 x141;
  uint32_t x142;
  fiat_fp131_uint1 x143;
  uint32_t x144;
  fiat_fp131_uint1 x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  uint32_t x156;
  fiat_fp131_uint1 x157;
  uint32_t x158;
  fiat_fp131_uint1 x159;
  uint32_t x160;
  fiat_fp131_uint1 x161;
  uint32_t x162;
  fiat_fp131_uint1 x163;
  uint32_t x164;
  fiat_fp131_uint1 x165;
  uint32_t x166;
  fiat_fp131_uint1 x167;
  uint32_t x168;
  fiat_fp131_uint1 x169;
  uint32_t x170;
  fiat_fp131_uint1 x171;
  uint32_t x172;
  fiat_fp131_uint1 x173;
  uint32_t x174;
  uint32_t x175;
  fiat_fp131_uint1 x176;
  uint32_t x177;
  fiat_fp131_uint1 x178;
  uint32_t x179;
  fiat_fp131_uint1 x180;
  uint32_t x181;
  fiat_fp131_uint1 x182;
  uint32_t x183;
  fiat_fp131_uint1 x184;
  uint32_t x185;
  fiat_fp131_uint1 x186;
  uint32_t x187;
  uint32_t x188;
  uint32_t x189;
  uint32_t x190;
  uint32_t x191;
  x1 = (arg1[0]);
  fiat_fp131_mulx_u32(&x2, &x3, x1, 0x6);
  fiat_fp131_mulx_u32(&x4, &x5, x1, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x6, &x7, x1, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x8, &x9, x1, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x10, &x11, x1, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x12, &x13, 0x0, x11, x8);
  fiat_fp131_addcarryx_u32(&x14, &x15, x13, x9, x6);
  fiat_fp131_addcarryx_u32(&x16, &x17, x15, x7, x4);
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x5, x2);
  fiat_fp131_addcarryx_u32(&x20, &x21, 0x0, x1, x10);
  fiat_fp131_addcarryx_u32(&x22, &x23, x21, 0x0, x12);
  fiat_fp131_addcarryx_u32(&x24, &x25, x23, 0x0, x14);
  fiat_fp131_addcarryx_u32(&x26, &x27, x25, 0x0, x16);
  fiat_fp131_addcarryx_u32(&x28, &x29, x27, 0x0, x18);
  fiat_fp131_addcarryx_u32(&x30, &x31, 0x0, x22, (arg1[1]));
  fiat_fp131_addcarryx_u32(&x32, &x33, x31, x24, 0x0);
  fiat_fp131_addcarryx_u32(&x34, &x35, x33, x26, 0x0);
  fiat_fp131_addcarryx_u32(&x36, &x37, x35, x28, 0x0);
  fiat_fp131_mulx_u32(&x38, &x39, x30, 0x6);
  fiat_fp131_mulx_u32(&x40, &x41, x30, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x42, &x43, x30, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x44, &x45, x30, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x46, &x47, x30, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x48, &x49, 0x0, x47, x44);
  fiat_fp131_addcarryx_u32(&x50, &x51, x49, x45, x42);
  fiat_fp131_addcarryx_u32(&x52, &x53, x51, x43, x40);
  fiat_fp131_addcarryx_u32(&x54, &x55, x53, x41, x38);
  fiat_fp131_addcarryx_u32(&x56, &x57, 0x0, x30, x46);
  fiat_fp131_addcarryx_u32(&x58, &x59, x57, x32, x48);
  fiat_fp131_addcarryx_u32(&x60, &x61, x59, x34, x50);
  fiat_fp131_addcarryx_u32(&x62, &x63, x61, x36, x52);
  fiat_fp131_addcarryx_u32(&x64, &x65, x63, (x37 + (x29 + (x19 + x3))), x54);
  fiat_fp131_addcarryx_u32(&x66, &x67, 0x0, x58, (arg1[2]));
  fiat_fp131_addcarryx_u32(&x68, &x69, x67, x60, 0x0);
  fiat_fp131_addcarryx_u32(&x70, &x71, x69, x62, 0x0);
  fiat_fp131_addcarryx_u32(&x72, &x73, x71, x64, 0x0);
  fiat_fp131_mulx_u32(&x74, &x75, x66, 0x6);
  fiat_fp131_mulx_u32(&x76, &x77, x66, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x78, &x79, x66, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x80, &x81, x66, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x82, &x83, x66, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x84, &x85, 0x0, x83, x80);
  fiat_fp131_addcarryx_u32(&x86, &x87, x85, x81, x78);
  fiat_fp131_addcarryx_u32(&x88, &x89, x87, x79, x76);
  fiat_fp131_addcarryx_u32(&x90, &x91, x89, x77, x74);
  fiat_fp131_addcarryx_u32(&x92, &x93, 0x0, x66, x82);
  fiat_fp131_addcarryx_u32(&x94, &x95, x93, x68, x84);
  fiat_fp131_addcarryx_u32(&x96, &x97, x95, x70, x86);
  fiat_fp131_addcarryx_u32(&x98, &x99, x97, x72, x88);
  fiat_fp131_addcarryx_u32(&x100, &x101, x99, (x73 + (x65 + (x55 + x39))), x90);
  fiat_fp131_addcarryx_u32(&x102, &x103, 0x0, x94, (arg1[3]));
  fiat_fp131_addcarryx_u32(&x104, &x105, x103, x96, 0x0);
  fiat_fp131_addcarryx_u32(&x106, &x107, x105, x98, 0x0);
  fiat_fp131_addcarryx_u32(&x108, &x109, x107, x100, 0x0);
  fiat_fp131_mulx_u32(&x110, &x111, x102, 0x6);
  fiat_fp131_mulx_u32(&x112, &x113, x102, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x114, &x115, x102, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x116, &x117, x102, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x118, &x119, x102, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x120, &x121, 0x0, x119, x116);
  fiat_fp131_addcarryx_u32(&x122, &x123, x121, x117, x114);
  fiat_fp131_addcarryx_u32(&x124, &x125, x123, x115, x112);
  fiat_fp131_addcarryx_u32(&x126, &x127, x125, x113, x110);
  fiat_fp131_addcarryx_u32(&x128, &x129, 0x0, x102, x118);
  fiat_fp131_addcarryx_u32(&x130, &x131, x129, x104, x120);
  fiat_fp131_addcarryx_u32(&x132, &x133, x131, x106, x122);
  fiat_fp131_addcarryx_u32(&x134, &x135, x133, x108, x124);
  fiat_fp131_addcarryx_u32(&x136, &x137, x135, (x109 + (x101 + (x91 + x75))), x126);
  fiat_fp131_addcarryx_u32(&x138, &x139, 0x0, x130, (arg1[4]));
  fiat_fp131_addcarryx_u32(&x140, &x141, x139, x132, 0x0);
  fiat_fp131_addcarryx_u32(&x142, &x143, x141, x134, 0x0);
  fiat_fp131_addcarryx_u32(&x144, &x145, x143, x136, 0x0);
  fiat_fp131_mulx_u32(&x146, &x147, x138, 0x6);
  fiat_fp131_mulx_u32(&x148, &x149, x138, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x150, &x151, x138, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x152, &x153, x138, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x154, &x155, x138, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x156, &x157, 0x0, x155, x152);
  fiat_fp131_addcarryx_u32(&x158, &x159, x157, x153, x150);
  fiat_fp131_addcarryx_u32(&x160, &x161, x159, x151, x148);
  fiat_fp131_addcarryx_u32(&x162, &x163, x161, x149, x146);
  fiat_fp131_addcarryx_u32(&x164, &x165, 0x0, x138, x154);
  fiat_fp131_addcarryx_u32(&x166, &x167, x165, x140, x156);
  fiat_fp131_addcarryx_u32(&x168, &x169, x167, x142, x158);
  fiat_fp131_addcarryx_u32(&x170, &x171, x169, x144, x160);
  fiat_fp131_addcarryx_u32(&x172, &x173, x171, (x145 + (x137 + (x127 + x111))), x162);
  x174 = (x173 + (x163 + x147));
  fiat_fp131_subborrowx_u32(&x175, &x176, 0x0, x166, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x177, &x178, x176, x168, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x179, &x180, x178, x170, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x181, &x182, x180, x172, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x183, &x184, x182, x174, 0x6);
  fiat_fp131_subborrowx_u32(&x185, &x186, x184, 0x0, 0x0);
  fiat_fp131_cmovznz_u32(&x187, x186, x175, x166);
  fiat_fp131_cmovznz_u32(&x188, x186, x177, x168);
  fiat_fp131_cmovznz_u32(&x189, x186, x179, x170);
  fiat_fp131_cmovznz_u32(&x190, x186, x181, x172);
  fiat_fp131_cmovznz_u32(&x191, x186, x183, x174);
  out1[0] = x187;
  out1[1] = x188;
  out1[2] = x189;
  out1[3] = x190;
  out1[4] = x191;
}

/*
 * The function fiat_fp131_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_to_montgomery(fiat_fp131_montgomery_domain_field_element out1, const fiat_fp131_non_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  fiat_fp131_uint1 x15;
  uint32_t x16;
  fiat_fp131_uint1 x17;
  uint32_t x18;
  fiat_fp131_uint1 x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  fiat_fp131_uint1 x31;
  uint32_t x32;
  fiat_fp131_uint1 x33;
  uint32_t x34;
  fiat_fp131_uint1 x35;
  uint32_t x36;
  fiat_fp131_uint1 x37;
  uint32_t x38;
  fiat_fp131_uint1 x39;
  uint32_t x40;
  fiat_fp131_uint1 x41;
  uint32_t x42;
  fiat_fp131_uint1 x43;
  uint32_t x44;
  fiat_fp131_uint1 x45;
  uint32_t x46;
  fiat_fp131_uint1 x47;
  uint32_t x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  uint32_t x53;
  uint32_t x54;
  uint32_t x55;
  uint32_t x56;
  fiat_fp131_uint1 x57;
  uint32_t x58;
  fiat_fp131_uint1 x59;
  uint32_t x60;
  fiat_fp131_uint1 x61;
  uint32_t x62;
  fiat_fp131_uint1 x63;
  uint32_t x64;
  fiat_fp131_uint1 x65;
  uint32_t x66;
  fiat_fp131_uint1 x67;
  uint32_t x68;
  fiat_fp131_uint1 x69;
  uint32_t x70;
  uint32_t x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  uint32_t x79;
  uint32_t x80;
  fiat_fp131_uint1 x81;
  uint32_t x82;
  fiat_fp131_uint1 x83;
  uint32_t x84;
  fiat_fp131_uint1 x85;
  uint32_t x86;
  fiat_fp131_uint1 x87;
  uint32_t x88;
  fiat_fp131_uint1 x89;
  uint32_t x90;
  fiat_fp131_uint1 x91;
  uint32_t x92;
  fiat_fp131_uint1 x93;
  uint32_t x94;
  fiat_fp131_uint1 x95;
  uint32_t x96;
  fiat_fp131_uint1 x97;
  uint32_t x98;
  uint32_t x99;
  uint32_t x100;
  uint32_t x101;
  uint32_t x102;
  uint32_t x103;
  uint32_t x104;
  uint32_t x105;
  uint32_t x106;
  fiat_fp131_uint1 x107;
  uint32_t x108;
  fiat_fp131_uint1 x109;
  uint32_t x110;
  fiat_fp131_uint1 x111;
  uint32_t x112;
  fiat_fp131_uint1 x113;
  uint32_t x114;
  fiat_fp131_uint1 x115;
  uint32_t x116;
  fiat_fp131_uint1 x117;
  uint32_t x118;
  fiat_fp131_uint1 x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  uint32_t x123;
  uint32_t x124;
  uint32_t x125;
  uint32_t x126;
  uint32_t x127;
  uint32_t x128;
  uint32_t x129;
  uint32_t x130;
  fiat_fp131_uint1 x131;
  uint32_t x132;
  fiat_fp131_uint1 x133;
  uint32_t x134;
  fiat_fp131_uint1 x135;
  uint32_t x136;
  fiat_fp131_uint1 x137;
  uint32_t x138;
  fiat_fp131_uint1 x139;
  uint32_t x140;
  fiat_fp131_uint1 x141;
  uint32_t x142;
  fiat_fp131_uint1 x143;
  uint32_t x144;
  fiat_fp131_uint1 x145;
  uint32_t x146;
  fiat_fp131_uint1 x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  uint32_t x153;
  uint32_t x154;
  uint32_t x155;
  uint32_t x156;
  fiat_fp131_uint1 x157;
  uint32_t x158;
  fiat_fp131_uint1 x159;
  uint32_t x160;
  fiat_fp131_uint1 x161;
  uint32_t x162;
  fiat_fp131_uint1 x163;
  uint32_t x164;
  fiat_fp131_uint1 x165;
  uint32_t x166;
  fiat_fp131_uint1 x167;
  uint32_t x168;
  fiat_fp131_uint1 x169;
  uint32_t x170;
  uint32_t x171;
  uint32_t x172;
  uint32_t x173;
  uint32_t x174;
  uint32_t x175;
  uint32_t x176;
  uint32_t x177;
  uint32_t x178;
  uint32_t x179;
  uint32_t x180;
  fiat_fp131_uint1 x181;
  uint32_t x182;
  fiat_fp131_uint1 x183;
  uint32_t x184;
  fiat_fp131_uint1 x185;
  uint32_t x186;
  fiat_fp131_uint1 x187;
  uint32_t x188;
  fiat_fp131_uint1 x189;
  uint32_t x190;
  fiat_fp131_uint1 x191;
  uint32_t x192;
  fiat_fp131_uint1 x193;
  uint32_t x194;
  fiat_fp131_uint1 x195;
  uint32_t x196;
  fiat_fp131_uint1 x197;
  uint32_t x198;
  uint32_t x199;
  uint32_t x200;
  uint32_t x201;
  uint32_t x202;
  uint32_t x203;
  uint32_t x204;
  uint32_t x205;
  uint32_t x206;
  fiat_fp131_uint1 x207;
  uint32_t x208;
  fiat_fp131_uint1 x209;
  uint32_t x210;
  fiat_fp131_uint1 x211;
  uint32_t x212;
  fiat_fp131_uint1 x213;
  uint32_t x214;
  fiat_fp131_uint1 x215;
  uint32_t x216;
  fiat_fp131_uint1 x217;
  uint32_t x218;
  fiat_fp131_uint1 x219;
  uint32_t x220;
  uint32_t x221;
  uint32_t x222;
  uint32_t x223;
  uint32_t x224;
  uint32_t x225;
  uint32_t x226;
  uint32_t x227;
  uint32_t x228;
  uint32_t x229;
  uint32_t x230;
  fiat_fp131_uint1 x231;
  uint32_t x232;
  fiat_fp131_uint1 x233;
  uint32_t x234;
  fiat_fp131_uint1 x235;
  uint32_t x236;
  fiat_fp131_uint1 x237;
  uint32_t x238;
  fiat_fp131_uint1 x239;
  uint32_t x240;
  fiat_fp131_uint1 x241;
  uint32_t x242;
  fiat_fp131_uint1 x243;
  uint32_t x244;
  fiat_fp131_uint1 x245;
  uint32_t x246;
  fiat_fp131_uint1 x247;
  uint32_t x248;
  uint32_t x249;
  fiat_fp131_uint1 x250;
  uint32_t x251;
  fiat_fp131_uint1 x252;
  uint32_t x253;
  fiat_fp131_uint1 x254;
  uint32_t x255;
  fiat_fp131_uint1 x256;
  uint32_t x257;
  fiat_fp131_uint1 x258;
  uint32_t x259;
  fiat_fp131_uint1 x260;
  uint32_t x261;
  uint32_t x262;
  uint32_t x263;
  uint32_t x264;
  uint32_t x265;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_fp131_mulx_u32(&x6, &x7, x5, UINT32_C(0x704e1f69));
  fiat_fp131_mulx_u32(&x8, &x9, x5, UINT32_C(0x52c970ba));
  fiat_fp131_mulx_u32(&x10, &x11, x5, UINT32_C(0x6e509f68));
  fiat_fp131_mulx_u32(&x12, &x13, x5, UINT32_C(0x970d325d));
  fiat_fp131_addcarryx_u32(&x14, &x15, 0x0, x13, x10);
  fiat_fp131_addcarryx_u32(&x16, &x17, x15, x11, x8);
  fiat_fp131_addcarryx_u32(&x18, &x19, x17, x9, x6);
  fiat_fp131_mulx_u32(&x20, &x21, x12, 0x6);
  fiat_fp131_mulx_u32(&x22, &x23, x12, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x24, &x25, x12, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x26, &x27, x12, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x28, &x29, x12, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x30, &x31, 0x0, x29, x26);
  fiat_fp131_addcarryx_u32(&x32, &x33, x31, x27, x24);
  fiat_fp131_addcarryx_u32(&x34, &x35, x33, x25, x22);
  fiat_fp131_addcarryx_u32(&x36, &x37, x35, x23, x20);
  fiat_fp131_addcarryx_u32(&x38, &x39, 0x0, x12, x28);
  fiat_fp131_addcarryx_u32(&x40, &x41, x39, x14, x30);
  fiat_fp131_addcarryx_u32(&x42, &x43, x41, x16, x32);
  fiat_fp131_addcarryx_u32(&x44, &x45, x43, x18, x34);
  fiat_fp131_addcarryx_u32(&x46, &x47, x45, (x19 + x7), x36);
  fiat_fp131_mulx_u32(&x48, &x49, x1, UINT32_C(0x704e1f69));
  fiat_fp131_mulx_u32(&x50, &x51, x1, UINT32_C(0x52c970ba));
  fiat_fp131_mulx_u32(&x52, &x53, x1, UINT32_C(0x6e509f68));
  fiat_fp131_mulx_u32(&x54, &x55, x1, UINT32_C(0x970d325d));
  fiat_fp131_addcarryx_u32(&x56, &x57, 0x0, x55, x52);
  fiat_fp131_addcarryx_u32(&x58, &x59, x57, x53, x50);
  fiat_fp131_addcarryx_u32(&x60, &x61, x59, x51, x48);
  fiat_fp131_addcarryx_u32(&x62, &x63, 0x0, x40, x54);
  fiat_fp131_addcarryx_u32(&x64, &x65, x63, x42, x56);
  fiat_fp131_addcarryx_u32(&x66, &x67, x65, x44, x58);
  fiat_fp131_addcarryx_u32(&x68, &x69, x67, x46, x60);
  fiat_fp131_mulx_u32(&x70, &x71, x62, 0x6);
  fiat_fp131_mulx_u32(&x72, &x73, x62, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x74, &x75, x62, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x76, &x77, x62, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x78, &x79, x62, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x80, &x81, 0x0, x79, x76);
  fiat_fp131_addcarryx_u32(&x82, &x83, x81, x77, x74);
  fiat_fp131_addcarryx_u32(&x84, &x85, x83, x75, x72);
  fiat_fp131_addcarryx_u32(&x86, &x87, x85, x73, x70);
  fiat_fp131_addcarryx_u32(&x88, &x89, 0x0, x62, x78);
  fiat_fp131_addcarryx_u32(&x90, &x91, x89, x64, x80);
  fiat_fp131_addcarryx_u32(&x92, &x93, x91, x66, x82);
  fiat_fp131_addcarryx_u32(&x94, &x95, x93, x68, x84);
  fiat_fp131_addcarryx_u32(&x96, &x97, x95, ((x69 + (x47 + (x37 + x21))) + (x61 + x49)), x86);
  fiat_fp131_mulx_u32(&x98, &x99, x2, UINT32_C(0x704e1f69));
  fiat_fp131_mulx_u32(&x100, &x101, x2, UINT32_C(0x52c970ba));
  fiat_fp131_mulx_u32(&x102, &x103, x2, UINT32_C(0x6e509f68));
  fiat_fp131_mulx_u32(&x104, &x105, x2, UINT32_C(0x970d325d));
  fiat_fp131_addcarryx_u32(&x106, &x107, 0x0, x105, x102);
  fiat_fp131_addcarryx_u32(&x108, &x109, x107, x103, x100);
  fiat_fp131_addcarryx_u32(&x110, &x111, x109, x101, x98);
  fiat_fp131_addcarryx_u32(&x112, &x113, 0x0, x90, x104);
  fiat_fp131_addcarryx_u32(&x114, &x115, x113, x92, x106);
  fiat_fp131_addcarryx_u32(&x116, &x117, x115, x94, x108);
  fiat_fp131_addcarryx_u32(&x118, &x119, x117, x96, x110);
  fiat_fp131_mulx_u32(&x120, &x121, x112, 0x6);
  fiat_fp131_mulx_u32(&x122, &x123, x112, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x124, &x125, x112, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x126, &x127, x112, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x128, &x129, x112, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x130, &x131, 0x0, x129, x126);
  fiat_fp131_addcarryx_u32(&x132, &x133, x131, x127, x124);
  fiat_fp131_addcarryx_u32(&x134, &x135, x133, x125, x122);
  fiat_fp131_addcarryx_u32(&x136, &x137, x135, x123, x120);
  fiat_fp131_addcarryx_u32(&x138, &x139, 0x0, x112, x128);
  fiat_fp131_addcarryx_u32(&x140, &x141, x139, x114, x130);
  fiat_fp131_addcarryx_u32(&x142, &x143, x141, x116, x132);
  fiat_fp131_addcarryx_u32(&x144, &x145, x143, x118, x134);
  fiat_fp131_addcarryx_u32(&x146, &x147, x145, ((x119 + (x97 + (x87 + x71))) + (x111 + x99)), x136);
  fiat_fp131_mulx_u32(&x148, &x149, x3, UINT32_C(0x704e1f69));
  fiat_fp131_mulx_u32(&x150, &x151, x3, UINT32_C(0x52c970ba));
  fiat_fp131_mulx_u32(&x152, &x153, x3, UINT32_C(0x6e509f68));
  fiat_fp131_mulx_u32(&x154, &x155, x3, UINT32_C(0x970d325d));
  fiat_fp131_addcarryx_u32(&x156, &x157, 0x0, x155, x152);
  fiat_fp131_addcarryx_u32(&x158, &x159, x157, x153, x150);
  fiat_fp131_addcarryx_u32(&x160, &x161, x159, x151, x148);
  fiat_fp131_addcarryx_u32(&x162, &x163, 0x0, x140, x154);
  fiat_fp131_addcarryx_u32(&x164, &x165, x163, x142, x156);
  fiat_fp131_addcarryx_u32(&x166, &x167, x165, x144, x158);
  fiat_fp131_addcarryx_u32(&x168, &x169, x167, x146, x160);
  fiat_fp131_mulx_u32(&x170, &x171, x162, 0x6);
  fiat_fp131_mulx_u32(&x172, &x173, x162, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x174, &x175, x162, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x176, &x177, x162, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x178, &x179, x162, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x180, &x181, 0x0, x179, x176);
  fiat_fp131_addcarryx_u32(&x182, &x183, x181, x177, x174);
  fiat_fp131_addcarryx_u32(&x184, &x185, x183, x175, x172);
  fiat_fp131_addcarryx_u32(&x186, &x187, x185, x173, x170);
  fiat_fp131_addcarryx_u32(&x188, &x189, 0x0, x162, x178);
  fiat_fp131_addcarryx_u32(&x190, &x191, x189, x164, x180);
  fiat_fp131_addcarryx_u32(&x192, &x193, x191, x166, x182);
  fiat_fp131_addcarryx_u32(&x194, &x195, x193, x168, x184);
  fiat_fp131_addcarryx_u32(&x196, &x197, x195, ((x169 + (x147 + (x137 + x121))) + (x161 + x149)), x186);
  fiat_fp131_mulx_u32(&x198, &x199, x4, UINT32_C(0x704e1f69));
  fiat_fp131_mulx_u32(&x200, &x201, x4, UINT32_C(0x52c970ba));
  fiat_fp131_mulx_u32(&x202, &x203, x4, UINT32_C(0x6e509f68));
  fiat_fp131_mulx_u32(&x204, &x205, x4, UINT32_C(0x970d325d));
  fiat_fp131_addcarryx_u32(&x206, &x207, 0x0, x205, x202);
  fiat_fp131_addcarryx_u32(&x208, &x209, x207, x203, x200);
  fiat_fp131_addcarryx_u32(&x210, &x211, x209, x201, x198);
  fiat_fp131_addcarryx_u32(&x212, &x213, 0x0, x190, x204);
  fiat_fp131_addcarryx_u32(&x214, &x215, x213, x192, x206);
  fiat_fp131_addcarryx_u32(&x216, &x217, x215, x194, x208);
  fiat_fp131_addcarryx_u32(&x218, &x219, x217, x196, x210);
  fiat_fp131_mulx_u32(&x220, &x221, x212, 0x6);
  fiat_fp131_mulx_u32(&x222, &x223, x212, UINT32_C(0x397b18cf));
  fiat_fp131_mulx_u32(&x224, &x225, x212, UINT32_C(0x129f1e8c));
  fiat_fp131_mulx_u32(&x226, &x227, x212, UINT32_C(0xffffffff));
  fiat_fp131_mulx_u32(&x228, &x229, x212, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x230, &x231, 0x0, x229, x226);
  fiat_fp131_addcarryx_u32(&x232, &x233, x231, x227, x224);
  fiat_fp131_addcarryx_u32(&x234, &x235, x233, x225, x222);
  fiat_fp131_addcarryx_u32(&x236, &x237, x235, x223, x220);
  fiat_fp131_addcarryx_u32(&x238, &x239, 0x0, x212, x228);
  fiat_fp131_addcarryx_u32(&x240, &x241, x239, x214, x230);
  fiat_fp131_addcarryx_u32(&x242, &x243, x241, x216, x232);
  fiat_fp131_addcarryx_u32(&x244, &x245, x243, x218, x234);
  fiat_fp131_addcarryx_u32(&x246, &x247, x245, ((x219 + (x197 + (x187 + x171))) + (x211 + x199)), x236);
  x248 = (x247 + (x237 + x221));
  fiat_fp131_subborrowx_u32(&x249, &x250, 0x0, x240, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x251, &x252, x250, x242, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x253, &x254, x252, x244, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x255, &x256, x254, x246, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x257, &x258, x256, x248, 0x6);
  fiat_fp131_subborrowx_u32(&x259, &x260, x258, 0x0, 0x0);
  fiat_fp131_cmovznz_u32(&x261, x260, x249, x240);
  fiat_fp131_cmovznz_u32(&x262, x260, x251, x242);
  fiat_fp131_cmovznz_u32(&x263, x260, x253, x244);
  fiat_fp131_cmovznz_u32(&x264, x260, x255, x246);
  fiat_fp131_cmovznz_u32(&x265, x260, x257, x248);
  out1[0] = x261;
  out1[1] = x262;
  out1[2] = x263;
  out1[3] = x264;
  out1[4] = x265;
}

/*
 * The function fiat_fp131_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp131_nonzero(uint32_t* out1, const uint32_t arg1[5]) {
  uint32_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | ((arg1[2]) | ((arg1[3]) | (arg1[4])))));
  *out1 = x1;
}

/*
 * The function fiat_fp131_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp131_selectznz(uint32_t out1[5], fiat_fp131_uint1 arg1, const uint32_t arg2[5], const uint32_t arg3[5]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  fiat_fp131_cmovznz_u32(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_fp131_cmovznz_u32(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_fp131_cmovznz_u32(&x3, arg1, (arg2[2]), (arg3[2]));
  fiat_fp131_cmovznz_u32(&x4, arg1, (arg2[3]), (arg3[3]));
  fiat_fp131_cmovznz_u32(&x5, arg1, (arg2[4]), (arg3[4]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
  out1[4] = x5;
}

/*
 * The function fiat_fp131_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..16]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x7]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7]]
 */
void fiat_fp131_to_bytes(uint8_t out1[17], const uint32_t arg1[5]) {
  uint8_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint8_t x6;
  uint32_t x7;
  uint8_t x8;
  uint32_t x9;
  uint8_t x10;
  uint8_t x11;
  uint8_t x12;
  uint32_t x13;
  uint8_t x14;
  uint32_t x15;
  uint8_t x16;
  uint8_t x17;
  uint8_t x18;
  uint32_t x19;
  uint8_t x20;
  uint32_t x21;
  uint8_t x22;
  uint8_t x23;
  uint8_t x24;
  uint32_t x25;
  uint8_t x26;
  uint32_t x27;
  uint8_t x28;
  uint8_t x29;
  x1 = (uint8_t)(arg1[4]);
  x2 = (arg1[3]);
  x3 = (arg1[2]);
  x4 = (arg1[1]);
  x5 = (arg1[0]);
  x6 = (uint8_t)(x5 & UINT8_C(0xff));
  x7 = (x5 >> 8);
  x8 = (uint8_t)(x7 & UINT8_C(0xff));
  x9 = (x7 >> 8);
  x10 = (uint8_t)(x9 & UINT8_C(0xff));
  x11 = (uint8_t)(x9 >> 8);
  x12 = (uint8_t)(x4 & UINT8_C(0xff));
  x13 = (x4 >> 8);
  x14 = (uint8_t)(x13 & UINT8_C(0xff));
  x15 = (x13 >> 8);
  x16 = (uint8_t)(x15 & UINT8_C(0xff));
  x17 = (uint8_t)(x15 >> 8);
  x18 = (uint8_t)(x3 & UINT8_C(0xff));
  x19 = (x3 >> 8);
  x20 = (uint8_t)(x19 & UINT8_C(0xff));
  x21 = (x19 >> 8);
  x22 = (uint8_t)(x21 & UINT8_C(0xff));
  x23 = (uint8_t)(x21 >> 8);
  x24 = (uint8_t)(x2 & UINT8_C(0xff));
  x25 = (x2 >> 8);
  x26 = (uint8_t)(x25 & UINT8_C(0xff));
  x27 = (x25 >> 8);
  x28 = (uint8_t)(x27 & UINT8_C(0xff));
  x29 = (uint8_t)(x27 >> 8);
  out1[0] = x6;
  out1[1] = x8;
  out1[2] = x10;
  out1[3] = x11;
  out1[4] = x12;
  out1[5] = x14;
  out1[6] = x16;
  out1[7] = x17;
  out1[8] = x18;
  out1[9] = x20;
  out1[10] = x22;
  out1[11] = x23;
  out1[12] = x24;
  out1[13] = x26;
  out1[14] = x28;
  out1[15] = x29;
  out1[16] = x1;
}

/*
 * The function fiat_fp131_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0x7]]
 */
void fiat_fp131_from_bytes(uint32_t out1[5], const uint8_t arg1[17]) {
  uint8_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint8_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint8_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint8_t x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  uint8_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  x1 = (arg1[16]);
  x2 = ((uint32_t)(arg1[15]) << 24);
  x3 = ((uint32_t)(arg1[14]) << 16);
  x4 = ((uint32_t)(arg1[13]) << 8);
  x5 = (arg1[12]);
  x6 = ((uint32_t)(arg1[11]) << 24);
  x7 = ((uint32_t)(arg1[10]) << 16);
  x8 = ((uint32_t)(arg1[9]) << 8);
  x9 = (arg1[8]);
  x10 = ((uint32_t)(arg1[7]) << 24);
  x11 = ((uint32_t)(arg1[6]) << 16);
  x12 = ((uint32_t)(arg1[5]) << 8);
  x13 = (arg1[4]);
  x14 = ((uint32_t)(arg1[3]) << 24);
  x15 = ((uint32_t)(arg1[2]) << 16);
  x16 = ((uint32_t)(arg1[1]) << 8);
  x17 = (arg1[0]);
  x18 = (x16 + (uint32_t)x17);
  x19 = (x15 + x18);
  x20 = (x14 + x19);
  x21 = (x12 + (uint32_t)x13);
  x22 = (x11 + x21);
  x23 = (x10 + x22);
  x24 = (x8 + (uint32_t)x9);
  x25 = (x7 + x24);
  x26 = (x6 + x25);
  x27 = (x4 + (uint32_t)x5);
  x28 = (x3 + x27);
  x29 = (x2 + x28);
  out1[0] = x20;
  out1[1] = x23;
  out1[2] = x26;
  out1[3] = x29;
  out1[4] = x1;
}

/*
 * The function fiat_fp131_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp131_set_one(fiat_fp131_montgomery_domain_field_element out1) {
  out1[0] = UINT32_C(0x2920a8a1);
  out1[1] = 0x0;
  out1[2] = UINT32_C(0x77414153);
  out1[3] = UINT32_C(0xcd6fb1c4);
  out1[4] = 0x0;
}

/*
 * The function fiat_fp131_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp131_msat(uint32_t out1[6]) {
  out1[0] = UINT32_C(0xffffffff);
  out1[1] = UINT32_C(0xffffffff);
  out1[2] = UINT32_C(0x129f1e8c);
  out1[3] = UINT32_C(0x397b18cf);
  out1[4] = 0x6;
  out1[5] = 0x0;
}

/*
 * The function fiat_fp131_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp131_divstep_precomp(uint32_t out1[5]) {
  out1[0] = UINT32_C(0xf71f43f0);
  out1[1] = UINT32_C(0x2e1c3622);
  out1[2] = UINT32_C(0x31f1faf0);
  out1[3] = UINT32_C(0xf62b2cf0);
  out1[4] = 0x2;
}

/*
 * The function fiat_fp131_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp131_divstep(uint32_t* out1, uint32_t out2[6], uint32_t out3[6], uint32_t out4[5], uint32_t out5[5], uint32_t arg1, const uint32_t arg2[6], const uint32_t arg3[6], const uint32_t arg4[5], const uint32_t arg5[5]) {
  uint32_t x1;
  fiat_fp131_uint1 x2;
  fiat_fp131_uint1 x3;
  uint32_t x4;
  fiat_fp131_uint1 x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  fiat_fp131_uint1 x14;
  uint32_t x15;
  fiat_fp131_uint1 x16;
  uint32_t x17;
  fiat_fp131_uint1 x18;
  uint32_t x19;
  fiat_fp131_uint1 x20;
  uint32_t x21;
  fiat_fp131_uint1 x22;
  uint32_t x23;
  fiat_fp131_uint1 x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  uint32_t x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  fiat_fp131_uint1 x37;
  uint32_t x38;
  fiat_fp131_uint1 x39;
  uint32_t x40;
  fiat_fp131_uint1 x41;
  uint32_t x42;
  fiat_fp131_uint1 x43;
  uint32_t x44;
  fiat_fp131_uint1 x45;
  uint32_t x46;
  fiat_fp131_uint1 x47;
  uint32_t x48;
  fiat_fp131_uint1 x49;
  uint32_t x50;
  fiat_fp131_uint1 x51;
  uint32_t x52;
  fiat_fp131_uint1 x53;
  uint32_t x54;
  fiat_fp131_uint1 x55;
  uint32_t x56;
  fiat_fp131_uint1 x57;
  uint32_t x58;
  uint32_t x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  fiat_fp131_uint1 x64;
  uint32_t x65;
  fiat_fp131_uint1 x66;
  uint32_t x67;
  fiat_fp131_uint1 x68;
  uint32_t x69;
  fiat_fp131_uint1 x70;
  uint32_t x71;
  fiat_fp131_uint1 x72;
  uint32_t x73;
  uint32_t x74;
  fiat_fp131_uint1 x75;
  uint32_t x76;
  fiat_fp131_uint1 x77;
  uint32_t x78;
  fiat_fp131_uint1 x79;
  uint32_t x80;
  fiat_fp131_uint1 x81;
  uint32_t x82;
  fiat_fp131_uint1 x83;
  uint32_t x84;
  uint32_t x85;
  uint32_t x86;
  uint32_t x87;
  uint32_t x88;
  fiat_fp131_uint1 x89;
  uint32_t x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  fiat_fp131_uint1 x97;
  uint32_t x98;
  fiat_fp131_uint1 x99;
  uint32_t x100;
  fiat_fp131_uint1 x101;
  uint32_t x102;
  fiat_fp131_uint1 x103;
  uint32_t x104;
  fiat_fp131_uint1 x105;
  uint32_t x106;
  fiat_fp131_uint1 x107;
  uint32_t x108;
  uint32_t x109;
  uint32_t x110;
  uint32_t x111;
  uint32_t x112;
  uint32_t x113;
  fiat_fp131_uint1 x114;
  uint32_t x115;
  fiat_fp131_uint1 x116;
  uint32_t x117;
  fiat_fp131_uint1 x118;
  uint32_t x119;
  fiat_fp131_uint1 x120;
  uint32_t x121;
  fiat_fp131_uint1 x122;
  uint32_t x123;
  fiat_fp131_uint1 x124;
  uint32_t x125;
  fiat_fp131_uint1 x126;
  uint32_t x127;
  fiat_fp131_uint1 x128;
  uint32_t x129;
  fiat_fp131_uint1 x130;
  uint32_t x131;
  fiat_fp131_uint1 x132;
  uint32_t x133;
  fiat_fp131_uint1 x134;
  uint32_t x135;
  fiat_fp131_uint1 x136;
  uint32_t x137;
  uint32_t x138;
  uint32_t x139;
  uint32_t x140;
  uint32_t x141;
  uint32_t x142;
  uint32_t x143;
  uint32_t x144;
  uint32_t x145;
  uint32_t x146;
  uint32_t x147;
  uint32_t x148;
  uint32_t x149;
  uint32_t x150;
  uint32_t x151;
  uint32_t x152;
  fiat_fp131_addcarryx_u32(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_fp131_uint1)((fiat_fp131_uint1)(x1 >> 31) & (fiat_fp131_uint1)((arg3[0]) & 0x1));
  fiat_fp131_addcarryx_u32(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_fp131_cmovznz_u32(&x6, x3, arg1, x4);
  fiat_fp131_cmovznz_u32(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_fp131_cmovznz_u32(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_fp131_cmovznz_u32(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_fp131_cmovznz_u32(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_fp131_cmovznz_u32(&x11, x3, (arg2[4]), (arg3[4]));
  fiat_fp131_cmovznz_u32(&x12, x3, (arg2[5]), (arg3[5]));
  fiat_fp131_addcarryx_u32(&x13, &x14, 0x0, 0x1, (~(arg2[0])));
  fiat_fp131_addcarryx_u32(&x15, &x16, x14, 0x0, (~(arg2[1])));
  fiat_fp131_addcarryx_u32(&x17, &x18, x16, 0x0, (~(arg2[2])));
  fiat_fp131_addcarryx_u32(&x19, &x20, x18, 0x0, (~(arg2[3])));
  fiat_fp131_addcarryx_u32(&x21, &x22, x20, 0x0, (~(arg2[4])));
  fiat_fp131_addcarryx_u32(&x23, &x24, x22, 0x0, (~(arg2[5])));
  fiat_fp131_cmovznz_u32(&x25, x3, (arg3[0]), x13);
  fiat_fp131_cmovznz_u32(&x26, x3, (arg3[1]), x15);
  fiat_fp131_cmovznz_u32(&x27, x3, (arg3[2]), x17);
  fiat_fp131_cmovznz_u32(&x28, x3, (arg3[3]), x19);
  fiat_fp131_cmovznz_u32(&x29, x3, (arg3[4]), x21);
  fiat_fp131_cmovznz_u32(&x30, x3, (arg3[5]), x23);
  fiat_fp131_cmovznz_u32(&x31, x3, (arg4[0]), (arg5[0]));
  fiat_fp131_cmovznz_u32(&x32, x3, (arg4[1]), (arg5[1]));
  fiat_fp131_cmovznz_u32(&x33, x3, (arg4[2]), (arg5[2]));
  fiat_fp131_cmovznz_u32(&x34, x3, (arg4[3]), (arg5[3]));
  fiat_fp131_cmovznz_u32(&x35, x3, (arg4[4]), (arg5[4]));
  fiat_fp131_addcarryx_u32(&x36, &x37, 0x0, x31, x31);
  fiat_fp131_addcarryx_u32(&x38, &x39, x37, x32, x32);
  fiat_fp131_addcarryx_u32(&x40, &x41, x39, x33, x33);
  fiat_fp131_addcarryx_u32(&x42, &x43, x41, x34, x34);
  fiat_fp131_addcarryx_u32(&x44, &x45, x43, x35, x35);
  fiat_fp131_subborrowx_u32(&x46, &x47, 0x0, x36, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x48, &x49, x47, x38, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x50, &x51, x49, x40, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x52, &x53, x51, x42, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x54, &x55, x53, x44, 0x6);
  fiat_fp131_subborrowx_u32(&x56, &x57, x55, x45, 0x0);
  x58 = (arg4[4]);
  x59 = (arg4[3]);
  x60 = (arg4[2]);
  x61 = (arg4[1]);
  x62 = (arg4[0]);
  fiat_fp131_subborrowx_u32(&x63, &x64, 0x0, 0x0, x62);
  fiat_fp131_subborrowx_u32(&x65, &x66, x64, 0x0, x61);
  fiat_fp131_subborrowx_u32(&x67, &x68, x66, 0x0, x60);
  fiat_fp131_subborrowx_u32(&x69, &x70, x68, 0x0, x59);
  fiat_fp131_subborrowx_u32(&x71, &x72, x70, 0x0, x58);
  fiat_fp131_cmovznz_u32(&x73, x72, 0x0, UINT32_C(0xffffffff));
  fiat_fp131_addcarryx_u32(&x74, &x75, 0x0, x63, x73);
  fiat_fp131_addcarryx_u32(&x76, &x77, x75, x65, x73);
  fiat_fp131_addcarryx_u32(&x78, &x79, x77, x67, (x73 & UINT32_C(0x129f1e8c)));
  fiat_fp131_addcarryx_u32(&x80, &x81, x79, x69, (x73 & UINT32_C(0x397b18cf)));
  fiat_fp131_addcarryx_u32(&x82, &x83, x81, x71, (x73 & 0x6));
  fiat_fp131_cmovznz_u32(&x84, x3, (arg5[0]), x74);
  fiat_fp131_cmovznz_u32(&x85, x3, (arg5[1]), x76);
  fiat_fp131_cmovznz_u32(&x86, x3, (arg5[2]), x78);
  fiat_fp131_cmovznz_u32(&x87, x3, (arg5[3]), x80);
  fiat_fp131_cmovznz_u32(&x88, x3, (arg5[4]), x82);
  x89 = (fiat_fp131_uint1)(x25 & 0x1);
  fiat_fp131_cmovznz_u32(&x90, x89, 0x0, x7);
  fiat_fp131_cmovznz_u32(&x91, x89, 0x0, x8);
  fiat_fp131_cmovznz_u32(&x92, x89, 0x0, x9);
  fiat_fp131_cmovznz_u32(&x93, x89, 0x0, x10);
  fiat_fp131_cmovznz_u32(&x94, x89, 0x0, x11);
  fiat_fp131_cmovznz_u32(&x95, x89, 0x0, x12);
  fiat_fp131_addcarryx_u32(&x96, &x97, 0x0, x25, x90);
  fiat_fp131_addcarryx_u32(&x98, &x99, x97, x26, x91);
  fiat_fp131_addcarryx_u32(&x100, &x101, x99, x27, x92);
  fiat_fp131_addcarryx_u32(&x102, &x103, x101, x28, x93);
  fiat_fp131_addcarryx_u32(&x104, &x105, x103, x29, x94);
  fiat_fp131_addcarryx_u32(&x106, &x107, x105, x30, x95);
  fiat_fp131_cmovznz_u32(&x108, x89, 0x0, x31);
  fiat_fp131_cmovznz_u32(&x109, x89, 0x0, x32);
  fiat_fp131_cmovznz_u32(&x110, x89, 0x0, x33);
  fiat_fp131_cmovznz_u32(&x111, x89, 0x0, x34);
  fiat_fp131_cmovznz_u32(&x112, x89, 0x0, x35);
  fiat_fp131_addcarryx_u32(&x113, &x114, 0x0, x84, x108);
  fiat_fp131_addcarryx_u32(&x115, &x116, x114, x85, x109);
  fiat_fp131_addcarryx_u32(&x117, &x118, x116, x86, x110);
  fiat_fp131_addcarryx_u32(&x119, &x120, x118, x87, x111);
  fiat_fp131_addcarryx_u32(&x121, &x122, x120, x88, x112);
  fiat_fp131_subborrowx_u32(&x123, &x124, 0x0, x113, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x125, &x126, x124, x115, UINT32_C(0xffffffff));
  fiat_fp131_subborrowx_u32(&x127, &x128, x126, x117, UINT32_C(0x129f1e8c));
  fiat_fp131_subborrowx_u32(&x129, &x130, x128, x119, UINT32_C(0x397b18cf));
  fiat_fp131_subborrowx_u32(&x131, &x132, x130, x121, 0x6);
  fiat_fp131_subborrowx_u32(&x133, &x134, x132, x122, 0x0);
  fiat_fp131_addcarryx_u32(&x135, &x136, 0x0, x6, 0x1);
  x137 = ((x96 >> 1) | ((x98 << 31) & UINT32_C(0xffffffff)));
  x138 = ((x98 >> 1) | ((x100 << 31) & UINT32_C(0xffffffff)));
  x139 = ((x100 >> 1) | ((x102 << 31) & UINT32_C(0xffffffff)));
  x140 = ((x102 >> 1) | ((x104 << 31) & UINT32_C(0xffffffff)));
  x141 = ((x104 >> 1) | ((x106 << 31) & UINT32_C(0xffffffff)));
  x142 = ((x106 & UINT32_C(0x80000000)) | (x106 >> 1));
  fiat_fp131_cmovznz_u32(&x143, x57, x46, x36);
  fiat_fp131_cmovznz_u32(&x144, x57, x48, x38);
  fiat_fp131_cmovznz_u32(&x145, x57, x50, x40);
  fiat_fp131_cmovznz_u32(&x146, x57, x52, x42);
  fiat_fp131_cmovznz_u32(&x147, x57, x54, x44);
  fiat_fp131_cmovznz_u32(&x148, x134, x123, x113);
  fiat_fp131_cmovznz_u32(&x149, x134, x125, x115);
  fiat_fp131_cmovznz_u32(&x150, x134, x127, x117);
  fiat_fp131_cmovznz_u32(&x151, x134, x129, x119);
  fiat_fp131_cmovznz_u32(&x152, x134, x131, x121);
  *out1 = x135;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out2[4] = x11;
  out2[5] = x12;
  out3[0] = x137;
  out3[1] = x138;
  out3[2] = x139;
  out3[3] = x140;
  out3[4] = x141;
  out3[5] = x142;
  out4[0] = x143;
  out4[1] = x144;
  out4[2] = x145;
  out4[3] = x146;
  out4[4] = x147;
  out5[0] = x148;
  out5[1] = x149;
  out5[2] = x150;
  out5[3] = x151;
  out5[4] = x152;
}
