/* Autogenerated: word_by_word_montgomery fp72 32 0x92212361f3ffffffff */
/* curve description: fp72 */
/* machine_wordsize = 32 (from "32") */
/* requested operations: (all) */
/* m = 0x92212361f3ffffffff (from "0x92212361f3ffffffff") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 32) + (z[2] << 64) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 32) + (z[2] << 64) in */
/*                            if x1 & (2^96-1) < 2^95 then x1 & (2^96-1) else (x1 & (2^96-1)) - 2^96 */

#include <stdint.h>
typedef unsigned char fiat_fp72_uint1;
typedef signed char fiat_fp72_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_FP72_FIAT_INLINE __inline__
#else
#  define FIAT_FP72_FIAT_INLINE
#endif

/* The type fiat_fp72_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp72_montgomery_domain_field_element[3];

/* The type fiat_fp72_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]] */
typedef uint32_t fiat_fp72_non_montgomery_domain_field_element[3];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_fp72_addcarryx_u32 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^32
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp72_addcarryx_u32(uint32_t* out1, fiat_fp72_uint1* out2, fiat_fp72_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  uint64_t x1;
  uint32_t x2;
  fiat_fp72_uint1 x3;
  x1 = ((arg1 + (uint64_t)arg2) + arg3);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (fiat_fp72_uint1)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp72_subborrowx_u32 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^32
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_fp72_subborrowx_u32(uint32_t* out1, fiat_fp72_uint1* out2, fiat_fp72_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  int64_t x1;
  fiat_fp72_int1 x2;
  uint32_t x3;
  x1 = ((arg2 - (int64_t)arg1) - arg3);
  x2 = (fiat_fp72_int1)(x1 >> 32);
  x3 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  *out1 = x3;
  *out2 = (fiat_fp72_uint1)(0x0 - x2);
}

/*
 * The function fiat_fp72_mulx_u32 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^32
 *   out2 = ⌊arg1 * arg2 / 2^32⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [0x0 ~> 0xffffffff]
 */
void fiat_fp72_mulx_u32(uint32_t* out1, uint32_t* out2, uint32_t arg1, uint32_t arg2) {
  uint64_t x1;
  uint32_t x2;
  uint32_t x3;
  x1 = ((uint64_t)arg1 * arg2);
  x2 = (uint32_t)(x1 & UINT32_C(0xffffffff));
  x3 = (uint32_t)(x1 >> 32);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_fp72_cmovznz_u32 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffff]
 *   arg3: [0x0 ~> 0xffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp72_cmovznz_u32(uint32_t* out1, fiat_fp72_uint1 arg1, uint32_t arg2, uint32_t arg3) {
  fiat_fp72_uint1 x1;
  uint32_t x2;
  uint32_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_fp72_int1)(0x0 - x1) & UINT32_C(0xffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_fp72_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_mul(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1, const fiat_fp72_montgomery_domain_field_element arg2) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  uint32_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  fiat_fp72_uint1 x22;
  uint32_t x23;
  fiat_fp72_uint1 x24;
  uint32_t x25;
  uint32_t x26;
  fiat_fp72_uint1 x27;
  uint32_t x28;
  fiat_fp72_uint1 x29;
  uint32_t x30;
  fiat_fp72_uint1 x31;
  uint32_t x32;
  fiat_fp72_uint1 x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  uint32_t x37;
  uint32_t x38;
  uint32_t x39;
  uint32_t x40;
  fiat_fp72_uint1 x41;
  uint32_t x42;
  fiat_fp72_uint1 x43;
  uint32_t x44;
  uint32_t x45;
  fiat_fp72_uint1 x46;
  uint32_t x47;
  fiat_fp72_uint1 x48;
  uint32_t x49;
  fiat_fp72_uint1 x50;
  uint32_t x51;
  fiat_fp72_uint1 x52;
  uint32_t x53;
  uint32_t x54;
  uint32_t x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  fiat_fp72_uint1 x60;
  uint32_t x61;
  fiat_fp72_uint1 x62;
  uint32_t x63;
  uint32_t x64;
  fiat_fp72_uint1 x65;
  uint32_t x66;
  fiat_fp72_uint1 x67;
  uint32_t x68;
  fiat_fp72_uint1 x69;
  uint32_t x70;
  fiat_fp72_uint1 x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  uint32_t x79;
  fiat_fp72_uint1 x80;
  uint32_t x81;
  fiat_fp72_uint1 x82;
  uint32_t x83;
  uint32_t x84;
  fiat_fp72_uint1 x85;
  uint32_t x86;
  fiat_fp72_uint1 x87;
  uint32_t x88;
  fiat_fp72_uint1 x89;
  uint32_t x90;
  fiat_fp72_uint1 x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  fiat_fp72_uint1 x99;
  uint32_t x100;
  fiat_fp72_uint1 x101;
  uint32_t x102;
  uint32_t x103;
  fiat_fp72_uint1 x104;
  uint32_t x105;
  fiat_fp72_uint1 x106;
  uint32_t x107;
  fiat_fp72_uint1 x108;
  uint32_t x109;
  fiat_fp72_uint1 x110;
  uint32_t x111;
  uint32_t x112;
  fiat_fp72_uint1 x113;
  uint32_t x114;
  fiat_fp72_uint1 x115;
  uint32_t x116;
  fiat_fp72_uint1 x117;
  uint32_t x118;
  fiat_fp72_uint1 x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp72_mulx_u32(&x4, &x5, x3, (arg2[2]));
  fiat_fp72_mulx_u32(&x6, &x7, x3, (arg2[1]));
  fiat_fp72_mulx_u32(&x8, &x9, x3, (arg2[0]));
  fiat_fp72_addcarryx_u32(&x10, &x11, 0x0, x9, x6);
  fiat_fp72_addcarryx_u32(&x12, &x13, x11, x7, x4);
  x14 = (x13 + x5);
  fiat_fp72_mulx_u32(&x15, &x16, x8, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x17, &x18, x8, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x19, &x20, x8, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x21, &x22, 0x0, x20, x17);
  fiat_fp72_addcarryx_u32(&x23, &x24, x22, x18, x15);
  x25 = (x24 + x16);
  fiat_fp72_addcarryx_u32(&x26, &x27, 0x0, x8, x19);
  fiat_fp72_addcarryx_u32(&x28, &x29, x27, x10, x21);
  fiat_fp72_addcarryx_u32(&x30, &x31, x29, x12, x23);
  fiat_fp72_addcarryx_u32(&x32, &x33, x31, x14, x25);
  fiat_fp72_mulx_u32(&x34, &x35, x1, (arg2[2]));
  fiat_fp72_mulx_u32(&x36, &x37, x1, (arg2[1]));
  fiat_fp72_mulx_u32(&x38, &x39, x1, (arg2[0]));
  fiat_fp72_addcarryx_u32(&x40, &x41, 0x0, x39, x36);
  fiat_fp72_addcarryx_u32(&x42, &x43, x41, x37, x34);
  x44 = (x43 + x35);
  fiat_fp72_addcarryx_u32(&x45, &x46, 0x0, x28, x38);
  fiat_fp72_addcarryx_u32(&x47, &x48, x46, x30, x40);
  fiat_fp72_addcarryx_u32(&x49, &x50, x48, x32, x42);
  fiat_fp72_addcarryx_u32(&x51, &x52, x50, x33, x44);
  fiat_fp72_mulx_u32(&x53, &x54, x45, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x55, &x56, x45, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x57, &x58, x45, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x59, &x60, 0x0, x58, x55);
  fiat_fp72_addcarryx_u32(&x61, &x62, x60, x56, x53);
  x63 = (x62 + x54);
  fiat_fp72_addcarryx_u32(&x64, &x65, 0x0, x45, x57);
  fiat_fp72_addcarryx_u32(&x66, &x67, x65, x47, x59);
  fiat_fp72_addcarryx_u32(&x68, &x69, x67, x49, x61);
  fiat_fp72_addcarryx_u32(&x70, &x71, x69, x51, x63);
  x72 = ((uint32_t)x71 + x52);
  fiat_fp72_mulx_u32(&x73, &x74, x2, (arg2[2]));
  fiat_fp72_mulx_u32(&x75, &x76, x2, (arg2[1]));
  fiat_fp72_mulx_u32(&x77, &x78, x2, (arg2[0]));
  fiat_fp72_addcarryx_u32(&x79, &x80, 0x0, x78, x75);
  fiat_fp72_addcarryx_u32(&x81, &x82, x80, x76, x73);
  x83 = (x82 + x74);
  fiat_fp72_addcarryx_u32(&x84, &x85, 0x0, x66, x77);
  fiat_fp72_addcarryx_u32(&x86, &x87, x85, x68, x79);
  fiat_fp72_addcarryx_u32(&x88, &x89, x87, x70, x81);
  fiat_fp72_addcarryx_u32(&x90, &x91, x89, x72, x83);
  fiat_fp72_mulx_u32(&x92, &x93, x84, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x94, &x95, x84, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x96, &x97, x84, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x98, &x99, 0x0, x97, x94);
  fiat_fp72_addcarryx_u32(&x100, &x101, x99, x95, x92);
  x102 = (x101 + x93);
  fiat_fp72_addcarryx_u32(&x103, &x104, 0x0, x84, x96);
  fiat_fp72_addcarryx_u32(&x105, &x106, x104, x86, x98);
  fiat_fp72_addcarryx_u32(&x107, &x108, x106, x88, x100);
  fiat_fp72_addcarryx_u32(&x109, &x110, x108, x90, x102);
  x111 = ((uint32_t)x110 + x91);
  fiat_fp72_subborrowx_u32(&x112, &x113, 0x0, x105, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x114, &x115, x113, x107, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x116, &x117, x115, x109, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x118, &x119, x117, x111, 0x0);
  fiat_fp72_cmovznz_u32(&x120, x119, x112, x105);
  fiat_fp72_cmovznz_u32(&x121, x119, x114, x107);
  fiat_fp72_cmovznz_u32(&x122, x119, x116, x109);
  out1[0] = x120;
  out1[1] = x121;
  out1[2] = x122;
}

/*
 * The function fiat_fp72_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_square(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  uint32_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  fiat_fp72_uint1 x22;
  uint32_t x23;
  fiat_fp72_uint1 x24;
  uint32_t x25;
  uint32_t x26;
  fiat_fp72_uint1 x27;
  uint32_t x28;
  fiat_fp72_uint1 x29;
  uint32_t x30;
  fiat_fp72_uint1 x31;
  uint32_t x32;
  fiat_fp72_uint1 x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  uint32_t x37;
  uint32_t x38;
  uint32_t x39;
  uint32_t x40;
  fiat_fp72_uint1 x41;
  uint32_t x42;
  fiat_fp72_uint1 x43;
  uint32_t x44;
  uint32_t x45;
  fiat_fp72_uint1 x46;
  uint32_t x47;
  fiat_fp72_uint1 x48;
  uint32_t x49;
  fiat_fp72_uint1 x50;
  uint32_t x51;
  fiat_fp72_uint1 x52;
  uint32_t x53;
  uint32_t x54;
  uint32_t x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  uint32_t x59;
  fiat_fp72_uint1 x60;
  uint32_t x61;
  fiat_fp72_uint1 x62;
  uint32_t x63;
  uint32_t x64;
  fiat_fp72_uint1 x65;
  uint32_t x66;
  fiat_fp72_uint1 x67;
  uint32_t x68;
  fiat_fp72_uint1 x69;
  uint32_t x70;
  fiat_fp72_uint1 x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  uint32_t x76;
  uint32_t x77;
  uint32_t x78;
  uint32_t x79;
  fiat_fp72_uint1 x80;
  uint32_t x81;
  fiat_fp72_uint1 x82;
  uint32_t x83;
  uint32_t x84;
  fiat_fp72_uint1 x85;
  uint32_t x86;
  fiat_fp72_uint1 x87;
  uint32_t x88;
  fiat_fp72_uint1 x89;
  uint32_t x90;
  fiat_fp72_uint1 x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  fiat_fp72_uint1 x99;
  uint32_t x100;
  fiat_fp72_uint1 x101;
  uint32_t x102;
  uint32_t x103;
  fiat_fp72_uint1 x104;
  uint32_t x105;
  fiat_fp72_uint1 x106;
  uint32_t x107;
  fiat_fp72_uint1 x108;
  uint32_t x109;
  fiat_fp72_uint1 x110;
  uint32_t x111;
  uint32_t x112;
  fiat_fp72_uint1 x113;
  uint32_t x114;
  fiat_fp72_uint1 x115;
  uint32_t x116;
  fiat_fp72_uint1 x117;
  uint32_t x118;
  fiat_fp72_uint1 x119;
  uint32_t x120;
  uint32_t x121;
  uint32_t x122;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp72_mulx_u32(&x4, &x5, x3, (arg1[2]));
  fiat_fp72_mulx_u32(&x6, &x7, x3, (arg1[1]));
  fiat_fp72_mulx_u32(&x8, &x9, x3, (arg1[0]));
  fiat_fp72_addcarryx_u32(&x10, &x11, 0x0, x9, x6);
  fiat_fp72_addcarryx_u32(&x12, &x13, x11, x7, x4);
  x14 = (x13 + x5);
  fiat_fp72_mulx_u32(&x15, &x16, x8, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x17, &x18, x8, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x19, &x20, x8, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x21, &x22, 0x0, x20, x17);
  fiat_fp72_addcarryx_u32(&x23, &x24, x22, x18, x15);
  x25 = (x24 + x16);
  fiat_fp72_addcarryx_u32(&x26, &x27, 0x0, x8, x19);
  fiat_fp72_addcarryx_u32(&x28, &x29, x27, x10, x21);
  fiat_fp72_addcarryx_u32(&x30, &x31, x29, x12, x23);
  fiat_fp72_addcarryx_u32(&x32, &x33, x31, x14, x25);
  fiat_fp72_mulx_u32(&x34, &x35, x1, (arg1[2]));
  fiat_fp72_mulx_u32(&x36, &x37, x1, (arg1[1]));
  fiat_fp72_mulx_u32(&x38, &x39, x1, (arg1[0]));
  fiat_fp72_addcarryx_u32(&x40, &x41, 0x0, x39, x36);
  fiat_fp72_addcarryx_u32(&x42, &x43, x41, x37, x34);
  x44 = (x43 + x35);
  fiat_fp72_addcarryx_u32(&x45, &x46, 0x0, x28, x38);
  fiat_fp72_addcarryx_u32(&x47, &x48, x46, x30, x40);
  fiat_fp72_addcarryx_u32(&x49, &x50, x48, x32, x42);
  fiat_fp72_addcarryx_u32(&x51, &x52, x50, x33, x44);
  fiat_fp72_mulx_u32(&x53, &x54, x45, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x55, &x56, x45, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x57, &x58, x45, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x59, &x60, 0x0, x58, x55);
  fiat_fp72_addcarryx_u32(&x61, &x62, x60, x56, x53);
  x63 = (x62 + x54);
  fiat_fp72_addcarryx_u32(&x64, &x65, 0x0, x45, x57);
  fiat_fp72_addcarryx_u32(&x66, &x67, x65, x47, x59);
  fiat_fp72_addcarryx_u32(&x68, &x69, x67, x49, x61);
  fiat_fp72_addcarryx_u32(&x70, &x71, x69, x51, x63);
  x72 = ((uint32_t)x71 + x52);
  fiat_fp72_mulx_u32(&x73, &x74, x2, (arg1[2]));
  fiat_fp72_mulx_u32(&x75, &x76, x2, (arg1[1]));
  fiat_fp72_mulx_u32(&x77, &x78, x2, (arg1[0]));
  fiat_fp72_addcarryx_u32(&x79, &x80, 0x0, x78, x75);
  fiat_fp72_addcarryx_u32(&x81, &x82, x80, x76, x73);
  x83 = (x82 + x74);
  fiat_fp72_addcarryx_u32(&x84, &x85, 0x0, x66, x77);
  fiat_fp72_addcarryx_u32(&x86, &x87, x85, x68, x79);
  fiat_fp72_addcarryx_u32(&x88, &x89, x87, x70, x81);
  fiat_fp72_addcarryx_u32(&x90, &x91, x89, x72, x83);
  fiat_fp72_mulx_u32(&x92, &x93, x84, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x94, &x95, x84, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x96, &x97, x84, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x98, &x99, 0x0, x97, x94);
  fiat_fp72_addcarryx_u32(&x100, &x101, x99, x95, x92);
  x102 = (x101 + x93);
  fiat_fp72_addcarryx_u32(&x103, &x104, 0x0, x84, x96);
  fiat_fp72_addcarryx_u32(&x105, &x106, x104, x86, x98);
  fiat_fp72_addcarryx_u32(&x107, &x108, x106, x88, x100);
  fiat_fp72_addcarryx_u32(&x109, &x110, x108, x90, x102);
  x111 = ((uint32_t)x110 + x91);
  fiat_fp72_subborrowx_u32(&x112, &x113, 0x0, x105, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x114, &x115, x113, x107, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x116, &x117, x115, x109, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x118, &x119, x117, x111, 0x0);
  fiat_fp72_cmovznz_u32(&x120, x119, x112, x105);
  fiat_fp72_cmovznz_u32(&x121, x119, x114, x107);
  fiat_fp72_cmovznz_u32(&x122, x119, x116, x109);
  out1[0] = x120;
  out1[1] = x121;
  out1[2] = x122;
}

/*
 * The function fiat_fp72_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_add(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1, const fiat_fp72_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp72_uint1 x2;
  uint32_t x3;
  fiat_fp72_uint1 x4;
  uint32_t x5;
  fiat_fp72_uint1 x6;
  uint32_t x7;
  fiat_fp72_uint1 x8;
  uint32_t x9;
  fiat_fp72_uint1 x10;
  uint32_t x11;
  fiat_fp72_uint1 x12;
  uint32_t x13;
  fiat_fp72_uint1 x14;
  uint32_t x15;
  uint32_t x16;
  uint32_t x17;
  fiat_fp72_addcarryx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp72_addcarryx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp72_addcarryx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp72_subborrowx_u32(&x7, &x8, 0x0, x1, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x9, &x10, x8, x3, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x11, &x12, x10, x5, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x13, &x14, x12, x6, 0x0);
  fiat_fp72_cmovznz_u32(&x15, x14, x7, x1);
  fiat_fp72_cmovznz_u32(&x16, x14, x9, x3);
  fiat_fp72_cmovznz_u32(&x17, x14, x11, x5);
  out1[0] = x15;
  out1[1] = x16;
  out1[2] = x17;
}

/*
 * The function fiat_fp72_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_sub(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1, const fiat_fp72_montgomery_domain_field_element arg2) {
  uint32_t x1;
  fiat_fp72_uint1 x2;
  uint32_t x3;
  fiat_fp72_uint1 x4;
  uint32_t x5;
  fiat_fp72_uint1 x6;
  uint32_t x7;
  uint32_t x8;
  fiat_fp72_uint1 x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  fiat_fp72_subborrowx_u32(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_fp72_subborrowx_u32(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_fp72_subborrowx_u32(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_fp72_cmovznz_u32(&x7, x6, 0x0, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x8, &x9, 0x0, x1, x7);
  fiat_fp72_addcarryx_u32(&x10, &x11, x9, x3, (x7 & UINT32_C(0x212361f3)));
  fiat_fp72_addcarryx_u32(&x12, &x13, x11, x5, (x7 & UINT8_C(0x92)));
  out1[0] = x8;
  out1[1] = x10;
  out1[2] = x12;
}

/*
 * The function fiat_fp72_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_opp(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1) {
  uint32_t x1;
  fiat_fp72_uint1 x2;
  uint32_t x3;
  fiat_fp72_uint1 x4;
  uint32_t x5;
  fiat_fp72_uint1 x6;
  uint32_t x7;
  uint32_t x8;
  fiat_fp72_uint1 x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  fiat_fp72_subborrowx_u32(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_fp72_subborrowx_u32(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_fp72_subborrowx_u32(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_fp72_cmovznz_u32(&x7, x6, 0x0, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x8, &x9, 0x0, x1, x7);
  fiat_fp72_addcarryx_u32(&x10, &x11, x9, x3, (x7 & UINT32_C(0x212361f3)));
  fiat_fp72_addcarryx_u32(&x12, &x13, x11, x5, (x7 & UINT8_C(0x92)));
  out1[0] = x8;
  out1[1] = x10;
  out1[2] = x12;
}

/*
 * The function fiat_fp72_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^32)⁻¹ mod m)^3) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_from_montgomery(fiat_fp72_non_montgomery_domain_field_element out1, const fiat_fp72_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  fiat_fp72_uint1 x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  uint32_t x14;
  fiat_fp72_uint1 x15;
  uint32_t x16;
  fiat_fp72_uint1 x17;
  uint32_t x18;
  fiat_fp72_uint1 x19;
  uint32_t x20;
  fiat_fp72_uint1 x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  uint32_t x27;
  uint32_t x28;
  fiat_fp72_uint1 x29;
  uint32_t x30;
  fiat_fp72_uint1 x31;
  uint32_t x32;
  fiat_fp72_uint1 x33;
  uint32_t x34;
  fiat_fp72_uint1 x35;
  uint32_t x36;
  fiat_fp72_uint1 x37;
  uint32_t x38;
  fiat_fp72_uint1 x39;
  uint32_t x40;
  fiat_fp72_uint1 x41;
  uint32_t x42;
  uint32_t x43;
  uint32_t x44;
  uint32_t x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  fiat_fp72_uint1 x49;
  uint32_t x50;
  fiat_fp72_uint1 x51;
  uint32_t x52;
  fiat_fp72_uint1 x53;
  uint32_t x54;
  fiat_fp72_uint1 x55;
  uint32_t x56;
  fiat_fp72_uint1 x57;
  uint32_t x58;
  uint32_t x59;
  fiat_fp72_uint1 x60;
  uint32_t x61;
  fiat_fp72_uint1 x62;
  uint32_t x63;
  fiat_fp72_uint1 x64;
  uint32_t x65;
  fiat_fp72_uint1 x66;
  uint32_t x67;
  uint32_t x68;
  uint32_t x69;
  x1 = (arg1[0]);
  fiat_fp72_mulx_u32(&x2, &x3, x1, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x4, &x5, x1, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x6, &x7, x1, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x8, &x9, 0x0, x7, x4);
  fiat_fp72_addcarryx_u32(&x10, &x11, x9, x5, x2);
  fiat_fp72_addcarryx_u32(&x12, &x13, 0x0, x1, x6);
  fiat_fp72_addcarryx_u32(&x14, &x15, x13, 0x0, x8);
  fiat_fp72_addcarryx_u32(&x16, &x17, x15, 0x0, x10);
  fiat_fp72_addcarryx_u32(&x18, &x19, 0x0, x14, (arg1[1]));
  fiat_fp72_addcarryx_u32(&x20, &x21, x19, x16, 0x0);
  fiat_fp72_mulx_u32(&x22, &x23, x18, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x24, &x25, x18, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x26, &x27, x18, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x28, &x29, 0x0, x27, x24);
  fiat_fp72_addcarryx_u32(&x30, &x31, x29, x25, x22);
  fiat_fp72_addcarryx_u32(&x32, &x33, 0x0, x18, x26);
  fiat_fp72_addcarryx_u32(&x34, &x35, x33, x20, x28);
  fiat_fp72_addcarryx_u32(&x36, &x37, x35, (x21 + (x17 + (x11 + x3))), x30);
  fiat_fp72_addcarryx_u32(&x38, &x39, 0x0, x34, (arg1[2]));
  fiat_fp72_addcarryx_u32(&x40, &x41, x39, x36, 0x0);
  fiat_fp72_mulx_u32(&x42, &x43, x38, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x44, &x45, x38, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x46, &x47, x38, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x48, &x49, 0x0, x47, x44);
  fiat_fp72_addcarryx_u32(&x50, &x51, x49, x45, x42);
  fiat_fp72_addcarryx_u32(&x52, &x53, 0x0, x38, x46);
  fiat_fp72_addcarryx_u32(&x54, &x55, x53, x40, x48);
  fiat_fp72_addcarryx_u32(&x56, &x57, x55, (x41 + (x37 + (x31 + x23))), x50);
  x58 = (x57 + (x51 + x43));
  fiat_fp72_subborrowx_u32(&x59, &x60, 0x0, x54, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x61, &x62, x60, x56, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x63, &x64, x62, x58, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x65, &x66, x64, 0x0, 0x0);
  fiat_fp72_cmovznz_u32(&x67, x66, x59, x54);
  fiat_fp72_cmovznz_u32(&x68, x66, x61, x56);
  fiat_fp72_cmovznz_u32(&x69, x66, x63, x58);
  out1[0] = x67;
  out1[1] = x68;
  out1[2] = x69;
}

/*
 * The function fiat_fp72_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_to_montgomery(fiat_fp72_montgomery_domain_field_element out1, const fiat_fp72_non_montgomery_domain_field_element arg1) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  fiat_fp72_uint1 x11;
  uint32_t x12;
  fiat_fp72_uint1 x13;
  uint32_t x14;
  uint32_t x15;
  uint32_t x16;
  uint32_t x17;
  uint32_t x18;
  uint32_t x19;
  uint32_t x20;
  fiat_fp72_uint1 x21;
  uint32_t x22;
  fiat_fp72_uint1 x23;
  uint32_t x24;
  fiat_fp72_uint1 x25;
  uint32_t x26;
  fiat_fp72_uint1 x27;
  uint32_t x28;
  fiat_fp72_uint1 x29;
  uint32_t x30;
  uint32_t x31;
  uint32_t x32;
  uint32_t x33;
  uint32_t x34;
  uint32_t x35;
  uint32_t x36;
  fiat_fp72_uint1 x37;
  uint32_t x38;
  fiat_fp72_uint1 x39;
  uint32_t x40;
  fiat_fp72_uint1 x41;
  uint32_t x42;
  fiat_fp72_uint1 x43;
  uint32_t x44;
  fiat_fp72_uint1 x45;
  uint32_t x46;
  uint32_t x47;
  uint32_t x48;
  uint32_t x49;
  uint32_t x50;
  uint32_t x51;
  uint32_t x52;
  fiat_fp72_uint1 x53;
  uint32_t x54;
  fiat_fp72_uint1 x55;
  uint32_t x56;
  fiat_fp72_uint1 x57;
  uint32_t x58;
  fiat_fp72_uint1 x59;
  uint32_t x60;
  fiat_fp72_uint1 x61;
  uint32_t x62;
  uint32_t x63;
  uint32_t x64;
  uint32_t x65;
  uint32_t x66;
  uint32_t x67;
  uint32_t x68;
  fiat_fp72_uint1 x69;
  uint32_t x70;
  fiat_fp72_uint1 x71;
  uint32_t x72;
  fiat_fp72_uint1 x73;
  uint32_t x74;
  fiat_fp72_uint1 x75;
  uint32_t x76;
  fiat_fp72_uint1 x77;
  uint32_t x78;
  uint32_t x79;
  uint32_t x80;
  uint32_t x81;
  uint32_t x82;
  uint32_t x83;
  uint32_t x84;
  fiat_fp72_uint1 x85;
  uint32_t x86;
  fiat_fp72_uint1 x87;
  uint32_t x88;
  fiat_fp72_uint1 x89;
  uint32_t x90;
  fiat_fp72_uint1 x91;
  uint32_t x92;
  fiat_fp72_uint1 x93;
  uint32_t x94;
  uint32_t x95;
  fiat_fp72_uint1 x96;
  uint32_t x97;
  fiat_fp72_uint1 x98;
  uint32_t x99;
  fiat_fp72_uint1 x100;
  uint32_t x101;
  fiat_fp72_uint1 x102;
  uint32_t x103;
  uint32_t x104;
  uint32_t x105;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[0]);
  fiat_fp72_mulx_u32(&x4, &x5, x3, UINT8_C(0x87));
  fiat_fp72_mulx_u32(&x6, &x7, x3, UINT32_C(0x8c9b5dd3));
  fiat_fp72_mulx_u32(&x8, &x9, x3, UINT32_C(0x4066a812));
  fiat_fp72_addcarryx_u32(&x10, &x11, 0x0, x9, x6);
  fiat_fp72_addcarryx_u32(&x12, &x13, x11, x7, x4);
  fiat_fp72_mulx_u32(&x14, &x15, x8, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x16, &x17, x8, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x18, &x19, x8, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x20, &x21, 0x0, x19, x16);
  fiat_fp72_addcarryx_u32(&x22, &x23, x21, x17, x14);
  fiat_fp72_addcarryx_u32(&x24, &x25, 0x0, x8, x18);
  fiat_fp72_addcarryx_u32(&x26, &x27, x25, x10, x20);
  fiat_fp72_addcarryx_u32(&x28, &x29, x27, x12, x22);
  fiat_fp72_mulx_u32(&x30, &x31, x1, UINT8_C(0x87));
  fiat_fp72_mulx_u32(&x32, &x33, x1, UINT32_C(0x8c9b5dd3));
  fiat_fp72_mulx_u32(&x34, &x35, x1, UINT32_C(0x4066a812));
  fiat_fp72_addcarryx_u32(&x36, &x37, 0x0, x35, x32);
  fiat_fp72_addcarryx_u32(&x38, &x39, x37, x33, x30);
  fiat_fp72_addcarryx_u32(&x40, &x41, 0x0, x26, x34);
  fiat_fp72_addcarryx_u32(&x42, &x43, x41, x28, x36);
  fiat_fp72_addcarryx_u32(&x44, &x45, x43, ((x29 + (x13 + x5)) + (x23 + x15)), x38);
  fiat_fp72_mulx_u32(&x46, &x47, x40, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x48, &x49, x40, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x50, &x51, x40, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x52, &x53, 0x0, x51, x48);
  fiat_fp72_addcarryx_u32(&x54, &x55, x53, x49, x46);
  fiat_fp72_addcarryx_u32(&x56, &x57, 0x0, x40, x50);
  fiat_fp72_addcarryx_u32(&x58, &x59, x57, x42, x52);
  fiat_fp72_addcarryx_u32(&x60, &x61, x59, x44, x54);
  fiat_fp72_mulx_u32(&x62, &x63, x2, UINT8_C(0x87));
  fiat_fp72_mulx_u32(&x64, &x65, x2, UINT32_C(0x8c9b5dd3));
  fiat_fp72_mulx_u32(&x66, &x67, x2, UINT32_C(0x4066a812));
  fiat_fp72_addcarryx_u32(&x68, &x69, 0x0, x67, x64);
  fiat_fp72_addcarryx_u32(&x70, &x71, x69, x65, x62);
  fiat_fp72_addcarryx_u32(&x72, &x73, 0x0, x58, x66);
  fiat_fp72_addcarryx_u32(&x74, &x75, x73, x60, x68);
  fiat_fp72_addcarryx_u32(&x76, &x77, x75, ((x61 + (x45 + (x39 + x31))) + (x55 + x47)), x70);
  fiat_fp72_mulx_u32(&x78, &x79, x72, UINT8_C(0x92));
  fiat_fp72_mulx_u32(&x80, &x81, x72, UINT32_C(0x212361f3));
  fiat_fp72_mulx_u32(&x82, &x83, x72, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x84, &x85, 0x0, x83, x80);
  fiat_fp72_addcarryx_u32(&x86, &x87, x85, x81, x78);
  fiat_fp72_addcarryx_u32(&x88, &x89, 0x0, x72, x82);
  fiat_fp72_addcarryx_u32(&x90, &x91, x89, x74, x84);
  fiat_fp72_addcarryx_u32(&x92, &x93, x91, x76, x86);
  x94 = ((x93 + (x77 + (x71 + x63))) + (x87 + x79));
  fiat_fp72_subborrowx_u32(&x95, &x96, 0x0, x90, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x97, &x98, x96, x92, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x99, &x100, x98, x94, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x101, &x102, x100, 0x0, 0x0);
  fiat_fp72_cmovznz_u32(&x103, x102, x95, x90);
  fiat_fp72_cmovznz_u32(&x104, x102, x97, x92);
  fiat_fp72_cmovznz_u32(&x105, x102, x99, x94);
  out1[0] = x103;
  out1[1] = x104;
  out1[2] = x105;
}

/*
 * The function fiat_fp72_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 */
void fiat_fp72_nonzero(uint32_t* out1, const uint32_t arg1[3]) {
  uint32_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | (arg1[2])));
  *out1 = x1;
}

/*
 * The function fiat_fp72_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp72_selectznz(uint32_t out1[3], fiat_fp72_uint1 arg1, const uint32_t arg2[3], const uint32_t arg3[3]) {
  uint32_t x1;
  uint32_t x2;
  uint32_t x3;
  fiat_fp72_cmovznz_u32(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_fp72_cmovznz_u32(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_fp72_cmovznz_u32(&x3, arg1, (arg2[2]), (arg3[2]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
}

/*
 * The function fiat_fp72_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..8]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff]]
 */
void fiat_fp72_to_bytes(uint8_t out1[9], const uint32_t arg1[3]) {
  uint8_t x1;
  uint32_t x2;
  uint32_t x3;
  uint8_t x4;
  uint32_t x5;
  uint8_t x6;
  uint32_t x7;
  uint8_t x8;
  uint8_t x9;
  uint8_t x10;
  uint32_t x11;
  uint8_t x12;
  uint32_t x13;
  uint8_t x14;
  uint8_t x15;
  x1 = (uint8_t)(arg1[2]);
  x2 = (arg1[1]);
  x3 = (arg1[0]);
  x4 = (uint8_t)(x3 & UINT8_C(0xff));
  x5 = (x3 >> 8);
  x6 = (uint8_t)(x5 & UINT8_C(0xff));
  x7 = (x5 >> 8);
  x8 = (uint8_t)(x7 & UINT8_C(0xff));
  x9 = (uint8_t)(x7 >> 8);
  x10 = (uint8_t)(x2 & UINT8_C(0xff));
  x11 = (x2 >> 8);
  x12 = (uint8_t)(x11 & UINT8_C(0xff));
  x13 = (x11 >> 8);
  x14 = (uint8_t)(x13 & UINT8_C(0xff));
  x15 = (uint8_t)(x13 >> 8);
  out1[0] = x4;
  out1[1] = x6;
  out1[2] = x8;
  out1[3] = x9;
  out1[4] = x10;
  out1[5] = x12;
  out1[6] = x14;
  out1[7] = x15;
  out1[8] = x1;
}

/*
 * The function fiat_fp72_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xff]]
 */
void fiat_fp72_from_bytes(uint32_t out1[3], const uint8_t arg1[9]) {
  uint8_t x1;
  uint32_t x2;
  uint32_t x3;
  uint32_t x4;
  uint8_t x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint8_t x9;
  uint32_t x10;
  uint32_t x11;
  uint32_t x12;
  uint32_t x13;
  uint32_t x14;
  uint32_t x15;
  x1 = (arg1[8]);
  x2 = ((uint32_t)(arg1[7]) << 24);
  x3 = ((uint32_t)(arg1[6]) << 16);
  x4 = ((uint32_t)(arg1[5]) << 8);
  x5 = (arg1[4]);
  x6 = ((uint32_t)(arg1[3]) << 24);
  x7 = ((uint32_t)(arg1[2]) << 16);
  x8 = ((uint32_t)(arg1[1]) << 8);
  x9 = (arg1[0]);
  x10 = (x8 + (uint32_t)x9);
  x11 = (x7 + x10);
  x12 = (x6 + x11);
  x13 = (x4 + (uint32_t)x5);
  x14 = (x3 + x13);
  x15 = (x2 + x14);
  out1[0] = x12;
  out1[1] = x15;
  out1[2] = x1;
}

/*
 * The function fiat_fp72_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_fp72_set_one(fiat_fp72_montgomery_domain_field_element out1) {
  out1[0] = UINT32_C(0x1c07aa5);
  out1[1] = UINT32_C(0x5c8395bc);
  out1[2] = UINT8_C(0x1a);
}

/*
 * The function fiat_fp72_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp72_msat(uint32_t out1[4]) {
  out1[0] = UINT32_C(0xffffffff);
  out1[1] = UINT32_C(0x212361f3);
  out1[2] = UINT8_C(0x92);
  out1[3] = 0x0;
}

/*
 * The function fiat_fp72_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp72_divstep_precomp(uint32_t out1[3]) {
  out1[0] = UINT32_C(0x6e391372);
  out1[1] = UINT32_C(0x8bf0945f);
  out1[2] = UINT8_C(0x75);
}

/*
 * The function fiat_fp72_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffff]
 *   arg2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   arg5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffff]
 *   out2: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out3: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out4: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 *   out5: [[0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff], [0x0 ~> 0xffffffff]]
 */
void fiat_fp72_divstep(uint32_t* out1, uint32_t out2[4], uint32_t out3[4], uint32_t out4[3], uint32_t out5[3], uint32_t arg1, const uint32_t arg2[4], const uint32_t arg3[4], const uint32_t arg4[3], const uint32_t arg5[3]) {
  uint32_t x1;
  fiat_fp72_uint1 x2;
  fiat_fp72_uint1 x3;
  uint32_t x4;
  fiat_fp72_uint1 x5;
  uint32_t x6;
  uint32_t x7;
  uint32_t x8;
  uint32_t x9;
  uint32_t x10;
  uint32_t x11;
  fiat_fp72_uint1 x12;
  uint32_t x13;
  fiat_fp72_uint1 x14;
  uint32_t x15;
  fiat_fp72_uint1 x16;
  uint32_t x17;
  fiat_fp72_uint1 x18;
  uint32_t x19;
  uint32_t x20;
  uint32_t x21;
  uint32_t x22;
  uint32_t x23;
  uint32_t x24;
  uint32_t x25;
  uint32_t x26;
  fiat_fp72_uint1 x27;
  uint32_t x28;
  fiat_fp72_uint1 x29;
  uint32_t x30;
  fiat_fp72_uint1 x31;
  uint32_t x32;
  fiat_fp72_uint1 x33;
  uint32_t x34;
  fiat_fp72_uint1 x35;
  uint32_t x36;
  fiat_fp72_uint1 x37;
  uint32_t x38;
  fiat_fp72_uint1 x39;
  uint32_t x40;
  uint32_t x41;
  uint32_t x42;
  uint32_t x43;
  fiat_fp72_uint1 x44;
  uint32_t x45;
  fiat_fp72_uint1 x46;
  uint32_t x47;
  fiat_fp72_uint1 x48;
  uint32_t x49;
  uint32_t x50;
  fiat_fp72_uint1 x51;
  uint32_t x52;
  fiat_fp72_uint1 x53;
  uint32_t x54;
  fiat_fp72_uint1 x55;
  uint32_t x56;
  uint32_t x57;
  uint32_t x58;
  fiat_fp72_uint1 x59;
  uint32_t x60;
  uint32_t x61;
  uint32_t x62;
  uint32_t x63;
  uint32_t x64;
  fiat_fp72_uint1 x65;
  uint32_t x66;
  fiat_fp72_uint1 x67;
  uint32_t x68;
  fiat_fp72_uint1 x69;
  uint32_t x70;
  fiat_fp72_uint1 x71;
  uint32_t x72;
  uint32_t x73;
  uint32_t x74;
  uint32_t x75;
  fiat_fp72_uint1 x76;
  uint32_t x77;
  fiat_fp72_uint1 x78;
  uint32_t x79;
  fiat_fp72_uint1 x80;
  uint32_t x81;
  fiat_fp72_uint1 x82;
  uint32_t x83;
  fiat_fp72_uint1 x84;
  uint32_t x85;
  fiat_fp72_uint1 x86;
  uint32_t x87;
  fiat_fp72_uint1 x88;
  uint32_t x89;
  fiat_fp72_uint1 x90;
  uint32_t x91;
  uint32_t x92;
  uint32_t x93;
  uint32_t x94;
  uint32_t x95;
  uint32_t x96;
  uint32_t x97;
  uint32_t x98;
  uint32_t x99;
  uint32_t x100;
  fiat_fp72_addcarryx_u32(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_fp72_uint1)((fiat_fp72_uint1)(x1 >> 31) & (fiat_fp72_uint1)((arg3[0]) & 0x1));
  fiat_fp72_addcarryx_u32(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_fp72_cmovznz_u32(&x6, x3, arg1, x4);
  fiat_fp72_cmovznz_u32(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_fp72_cmovznz_u32(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_fp72_cmovznz_u32(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_fp72_cmovznz_u32(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_fp72_addcarryx_u32(&x11, &x12, 0x0, 0x1, (~(arg2[0])));
  fiat_fp72_addcarryx_u32(&x13, &x14, x12, 0x0, (~(arg2[1])));
  fiat_fp72_addcarryx_u32(&x15, &x16, x14, 0x0, (~(arg2[2])));
  fiat_fp72_addcarryx_u32(&x17, &x18, x16, 0x0, (~(arg2[3])));
  fiat_fp72_cmovznz_u32(&x19, x3, (arg3[0]), x11);
  fiat_fp72_cmovznz_u32(&x20, x3, (arg3[1]), x13);
  fiat_fp72_cmovznz_u32(&x21, x3, (arg3[2]), x15);
  fiat_fp72_cmovznz_u32(&x22, x3, (arg3[3]), x17);
  fiat_fp72_cmovznz_u32(&x23, x3, (arg4[0]), (arg5[0]));
  fiat_fp72_cmovznz_u32(&x24, x3, (arg4[1]), (arg5[1]));
  fiat_fp72_cmovznz_u32(&x25, x3, (arg4[2]), (arg5[2]));
  fiat_fp72_addcarryx_u32(&x26, &x27, 0x0, x23, x23);
  fiat_fp72_addcarryx_u32(&x28, &x29, x27, x24, x24);
  fiat_fp72_addcarryx_u32(&x30, &x31, x29, x25, x25);
  fiat_fp72_subborrowx_u32(&x32, &x33, 0x0, x26, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x34, &x35, x33, x28, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x36, &x37, x35, x30, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x38, &x39, x37, x31, 0x0);
  x40 = (arg4[2]);
  x41 = (arg4[1]);
  x42 = (arg4[0]);
  fiat_fp72_subborrowx_u32(&x43, &x44, 0x0, 0x0, x42);
  fiat_fp72_subborrowx_u32(&x45, &x46, x44, 0x0, x41);
  fiat_fp72_subborrowx_u32(&x47, &x48, x46, 0x0, x40);
  fiat_fp72_cmovznz_u32(&x49, x48, 0x0, UINT32_C(0xffffffff));
  fiat_fp72_addcarryx_u32(&x50, &x51, 0x0, x43, x49);
  fiat_fp72_addcarryx_u32(&x52, &x53, x51, x45, (x49 & UINT32_C(0x212361f3)));
  fiat_fp72_addcarryx_u32(&x54, &x55, x53, x47, (x49 & UINT8_C(0x92)));
  fiat_fp72_cmovznz_u32(&x56, x3, (arg5[0]), x50);
  fiat_fp72_cmovznz_u32(&x57, x3, (arg5[1]), x52);
  fiat_fp72_cmovznz_u32(&x58, x3, (arg5[2]), x54);
  x59 = (fiat_fp72_uint1)(x19 & 0x1);
  fiat_fp72_cmovznz_u32(&x60, x59, 0x0, x7);
  fiat_fp72_cmovznz_u32(&x61, x59, 0x0, x8);
  fiat_fp72_cmovznz_u32(&x62, x59, 0x0, x9);
  fiat_fp72_cmovznz_u32(&x63, x59, 0x0, x10);
  fiat_fp72_addcarryx_u32(&x64, &x65, 0x0, x19, x60);
  fiat_fp72_addcarryx_u32(&x66, &x67, x65, x20, x61);
  fiat_fp72_addcarryx_u32(&x68, &x69, x67, x21, x62);
  fiat_fp72_addcarryx_u32(&x70, &x71, x69, x22, x63);
  fiat_fp72_cmovznz_u32(&x72, x59, 0x0, x23);
  fiat_fp72_cmovznz_u32(&x73, x59, 0x0, x24);
  fiat_fp72_cmovznz_u32(&x74, x59, 0x0, x25);
  fiat_fp72_addcarryx_u32(&x75, &x76, 0x0, x56, x72);
  fiat_fp72_addcarryx_u32(&x77, &x78, x76, x57, x73);
  fiat_fp72_addcarryx_u32(&x79, &x80, x78, x58, x74);
  fiat_fp72_subborrowx_u32(&x81, &x82, 0x0, x75, UINT32_C(0xffffffff));
  fiat_fp72_subborrowx_u32(&x83, &x84, x82, x77, UINT32_C(0x212361f3));
  fiat_fp72_subborrowx_u32(&x85, &x86, x84, x79, UINT8_C(0x92));
  fiat_fp72_subborrowx_u32(&x87, &x88, x86, x80, 0x0);
  fiat_fp72_addcarryx_u32(&x89, &x90, 0x0, x6, 0x1);
  x91 = ((x64 >> 1) | ((x66 << 31) & UINT32_C(0xffffffff)));
  x92 = ((x66 >> 1) | ((x68 << 31) & UINT32_C(0xffffffff)));
  x93 = ((x68 >> 1) | ((x70 << 31) & UINT32_C(0xffffffff)));
  x94 = ((x70 & UINT32_C(0x80000000)) | (x70 >> 1));
  fiat_fp72_cmovznz_u32(&x95, x39, x32, x26);
  fiat_fp72_cmovznz_u32(&x96, x39, x34, x28);
  fiat_fp72_cmovznz_u32(&x97, x39, x36, x30);
  fiat_fp72_cmovznz_u32(&x98, x88, x81, x75);
  fiat_fp72_cmovznz_u32(&x99, x88, x83, x77);
  fiat_fp72_cmovznz_u32(&x100, x88, x85, x79);
  *out1 = x89;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out3[0] = x91;
  out3[1] = x92;
  out3[2] = x93;
  out3[3] = x94;
  out4[0] = x95;
  out4[1] = x96;
  out4[2] = x97;
  out5[0] = x98;
  out5[1] = x99;
  out5[2] = x100;
}
